import type { CollaborationState } from "./collaboration.types";

/** Fictional September 24 scenario normalized from mockups/assets/mock-data.js. */
const SAMPLE_STATE: CollaborationState = {
	today: "2026-09-24",
	topics: [
		{
			id: "t-geng",
			name: "Google - Engineering partnership",
			short: "Google Eng",
			accountId: "google",
			kind: "client",
			color: "#2d6fd0",
			status: "active",
			description:
				"Joint engineering work with Google Cloud AI: agent architecture review, sandbox access, integration pilot for two use cases.",
			goals: [
				{
					text: "Present agent architecture at Google eng review (Oct 15)",
					status: "open",
					noteId: "t-geng-goal-1",
				},
				{
					text: "Sandbox access for the pilot team",
					status: "open",
					noteId: "t-geng-goal-2",
				},
				{
					text: "Mutual NDA signed",
					status: "done",
					noteId: "t-geng-goal-3",
				},
			],
			notes: [
				{
					text: "Priya prefers a written pre-read 48h before any review.",
					by: "you",
					date: "2026-09-18T16:00:00.000Z",
					status: "confirmed",
					noteId: "t-geng-note-1",
					kind: "note",
				},
				{
					text: "Pilot scope is limited to 2 use cases (claims triage, contract Q&A).",
					by: "assistant",
					date: "2026-09-20T16:00:00.000Z",
					status: "draft",
					source: "Email from Raj Mehta, Sep 20",
					noteId: "t-geng-note-2",
					kind: "note",
				},
			],
			keywords: [
				"agent architecture",
				"sandbox",
				"eng review",
				"Vertex",
				"pilot",
			],
			people: [
				{
					personId: "p-priya",
					role: "Google lead",
					engagement: 94,
					state: "member",
					origin: "brain",
				},
				{
					personId: "p-marcus",
					role: "Google engineer",
					engagement: 71,
					state: "member",
					origin: "brain",
				},
				{
					personId: "p-raj",
					role: "Deloitte demo owner",
					engagement: 66,
					state: "member",
					origin: "you",
				},
				{
					personId: "p-elena",
					role: "Google PM",
					engagement: 38,
					state: "suggested",
					origin: "brain",
					reason: "On 2 threads this week",
				},
				{
					personId: "p-tom",
					role: "Google events",
					engagement: 12,
					state: "removed",
					origin: "you",
					reason: "Removed by you Sep 22",
				},
			],
			calendarSeries: ["Google eng weekly (Tue 1:00 PM)"],
			stats: {
				threads: 3,
				openItems: 2,
				lastActivity: "2026-09-24T15:40:00.000Z",
			},
			isSample: true,
		},
		{
			id: "t-gsales",
			name: "Google - Sales / GTM",
			short: "Google Sales",
			accountId: "google",
			kind: "client",
			color: "#1f8a5b",
			status: "active",
			description:
				"Commercial track with Google partner sales: pricing, procurement, security questionnaire, joint GTM plan.",
			goals: [
				{
					text: "Answer procurement pricing questions",
					status: "open",
					noteId: "t-gsales-goal-1",
				},
				{
					text: "Agree joint GTM motion for Q1",
					status: "open",
					noteId: "t-gsales-goal-2",
				},
			],
			notes: [
				{
					text: "Ken Watanabe (procurement) needs pricing in their template, not ours.",
					by: "assistant",
					date: "2026-09-23T16:00:00.000Z",
					status: "draft",
					source: "Email from Ken Watanabe, Sep 23",
					noteId: "t-gsales-note-1",
					kind: "note",
				},
			],
			keywords: [
				"pricing",
				"procurement",
				"GTM",
				"security questionnaire",
				"MSA",
			],
			people: [
				{
					personId: "p-dana",
					role: "Google partner sales lead",
					engagement: 88,
					state: "member",
					origin: "brain",
				},
				{
					personId: "p-luis",
					role: "Google account exec",
					engagement: 57,
					state: "member",
					origin: "brain",
				},
				{
					personId: "p-ken",
					role: "Google procurement",
					engagement: 41,
					state: "suggested",
					origin: "brain",
					reason: "New on 3 Sales threads",
				},
				{
					personId: "p-raj",
					role: "Deloitte",
					engagement: 35,
					state: "member",
					origin: "brain",
				},
			],
			calendarSeries: [],
			stats: {
				threads: 4,
				openItems: 4,
				lastActivity: "2026-09-24T15:40:00.000Z",
			},
			isSample: true,
		},
		{
			id: "t-trip",
			name: "Google onsite - Mountain View, Oct 14-15",
			short: "Google onsite",
			accountId: "google",
			kind: "event",
			color: "#d17a16",
			status: "active",
			description:
				"Logistics for the Mountain View onsite: flights, hotel, happy hour with the Google sales team, client dinner for 6.",
			goals: [
				{
					text: "Arrive Mountain View evening of Oct 13",
					status: "open",
					noteId: "t-trip-goal-1",
				},
				{
					text: "Host Google sales happy hour Oct 14, 5-6 PM",
					status: "open",
					noteId: "t-trip-goal-2",
				},
				{
					text: "Client dinner for 6 on Oct 14",
					status: "open",
					noteId: "t-trip-goal-3",
				},
			],
			notes: [
				{
					text: "Keep dinner under the client-entertainment limit; one guest is vegetarian.",
					by: "you",
					date: "2026-09-23T16:00:00.000Z",
					status: "confirmed",
					noteId: "t-trip-note-1",
					kind: "note",
				},
			],
			keywords: [
				"flight",
				"hotel",
				"itinerary",
				"dinner",
				"happy hour",
				"Mountain View",
			],
			people: [
				{
					personId: "p-jordan",
					role: "Your EA",
					engagement: 80,
					state: "member",
					origin: "you",
				},
				{
					personId: "p-dana",
					role: "Happy hour host (Google)",
					engagement: 30,
					state: "member",
					origin: "brain",
				},
			],
			calendarSeries: [],
			stats: {
				threads: 3,
				openItems: 5,
				lastActivity: "2026-09-24T16:40:00.000Z",
			},
			isSample: true,
		},
		{
			id: "t-oslt",
			name: "OSLT - AI platform investment",
			short: "OSLT",
			accountId: "deloitte",
			kind: "internal",
			color: "#7a4fc2",
			status: "active",
			description:
				"Internal leadership forum (OSLT). Current ask: build vs buy recommendation for the AI platform before Friday's session.",
			goals: [
				{
					text: "Give Pete a build vs buy recommendation before Fri OSLT",
					status: "open",
					noteId: "t-oslt-goal-1",
				},
			],
			notes: [
				{
					text: "Pete wants one page, numbers first.",
					by: "you",
					date: "2026-09-10T16:00:00.000Z",
					status: "confirmed",
					noteId: "t-oslt-note-1",
					kind: "note",
				},
			],
			keywords: ["OSLT", "platform", "build vs buy", "investment"],
			people: [
				{
					personId: "p-pete",
					role: "Exec sponsor",
					engagement: 90,
					state: "member",
					origin: "brain",
				},
				{
					personId: "p-sarah",
					role: "Principal",
					engagement: 52,
					state: "member",
					origin: "brain",
				},
				{
					personId: "p-laura",
					role: "Finance",
					engagement: 34,
					state: "member",
					origin: "brain",
				},
			],
			calendarSeries: ["OSLT (Fri 8:30 AM, biweekly)"],
			stats: {
				threads: 2,
				openItems: 1,
				lastActivity: "2026-09-24T16:15:00.000Z",
			},
			isSample: true,
		},
		{
			id: "t-board",
			name: "Board readout - Q4",
			short: "Board",
			accountId: "deloitte",
			kind: "internal",
			color: "#c43d3d",
			status: "active",
			description: "Q4 board readout. Owner of the AI slide.",
			goals: [
				{
					text: "Deliver AI slide to Sarah by Mon Sep 28",
					status: "open",
					noteId: "t-board-goal-1",
				},
			],
			notes: [],
			keywords: ["board", "readout", "slide", "deck"],
			people: [
				{
					personId: "p-sarah",
					role: "Deck owner",
					engagement: 85,
					state: "member",
					origin: "brain",
				},
				{
					personId: "p-pete",
					role: "Reviewer",
					engagement: 40,
					state: "member",
					origin: "brain",
				},
			],
			calendarSeries: [],
			stats: {
				threads: 2,
				openItems: 1,
				lastActivity: "2026-09-24T16:15:00.000Z",
			},
			isSample: true,
		},
		{
			id: "t-budget",
			name: "FY27 Budget",
			short: "Budget",
			accountId: "deloitte",
			kind: "internal",
			color: "#0f8a8a",
			status: "active",
			description:
				"FY27 planning: tooling and platform line items owned by the AI engineering team.",
			goals: [
				{
					text: "Approve tooling line items",
					status: "open",
					noteId: "t-budget-goal-1",
				},
			],
			notes: [],
			keywords: ["FY27", "budget", "line items", "tooling", "forecast"],
			people: [
				{
					personId: "p-laura",
					role: "Finance director",
					engagement: 82,
					state: "member",
					origin: "brain",
				},
				{
					personId: "p-pete",
					role: "Approver",
					engagement: 45,
					state: "member",
					origin: "brain",
				},
			],
			calendarSeries: [],
			stats: {
				threads: 3,
				openItems: 3,
				lastActivity: "2026-09-24T16:15:00.000Z",
			},
			isSample: true,
		},
		{
			id: "t-nvidia",
			name: "Nvidia - GPU capacity",
			short: "Nvidia",
			accountId: "nvidia",
			kind: "client",
			color: "#5f8a1e",
			status: "active",
			description:
				"GPU capacity reservation and alliance follow-ups with Nvidia.",
			goals: [
				{
					text: "Decide on Q1 capacity reservation",
					status: "open",
					noteId: "t-nvidia-goal-1",
				},
			],
			notes: [],
			keywords: ["GPU", "capacity", "reservation", "DGX"],
			people: [
				{
					personId: "p-chris",
					role: "Alliance manager",
					engagement: 76,
					state: "member",
					origin: "brain",
				},
			],
			calendarSeries: [],
			stats: {
				threads: 1,
				openItems: 1,
				lastActivity: "2026-09-22T19:15:00.000Z",
			},
			isSample: true,
		},
	],
	people: [
		{
			id: "p-priya",
			name: "Priya Raman",
			initials: "PR",
			email: "priya.raman@google.com",
			accountId: "google",
			title: "Director, Cloud AI Engineering",
			relationship: "Client lead",
			color: "#2d6fd0",
			vip: true,
			neverIngest: false,
			strength: 92,
			lastContact: "2026-09-24T16:00:00.000Z",
			channels: {
				email: 41,
				teams: 0,
				meetings: 6,
			},
			topics: ["t-geng"],
			isSample: true,
		},
		{
			id: "p-marcus",
			name: "Marcus Chen",
			initials: "MC",
			email: "marcus.chen@google.com",
			accountId: "google",
			title: "Staff Software Engineer",
			relationship: "Client",
			color: "#4a86e0",
			vip: false,
			neverIngest: false,
			strength: 70,
			lastContact: "2026-09-23T16:00:00.000Z",
			channels: {
				email: 18,
				teams: 0,
				meetings: 4,
			},
			topics: ["t-geng"],
			isSample: true,
		},
		{
			id: "p-elena",
			name: "Elena Sokolova",
			initials: "ES",
			email: "elena.sokolova@google.com",
			accountId: "google",
			title: "Product Manager, Agents",
			relationship: "Client",
			color: "#6a9be8",
			vip: false,
			neverIngest: false,
			strength: 35,
			lastContact: "2026-09-22T16:00:00.000Z",
			channels: {
				email: 4,
				teams: 0,
				meetings: 1,
			},
			topics: [],
			isSample: true,
		},
		{
			id: "p-tom",
			name: "Tom Becker",
			initials: "TB",
			email: "tom.becker@google.com",
			accountId: "google",
			title: "Partner Events",
			relationship: "Noise",
			color: "#9aa7b8",
			vip: false,
			neverIngest: false,
			strength: 10,
			lastContact: "2026-09-23T16:00:00.000Z",
			channels: {
				email: 9,
				teams: 0,
				meetings: 0,
			},
			topics: [],
			isSample: true,
		},
		{
			id: "p-dana",
			name: "Dana Whitfield",
			initials: "DW",
			email: "dana.whitfield@google.com",
			accountId: "google",
			title: "Partner Sales Director",
			relationship: "Client lead",
			color: "#1f8a5b",
			vip: true,
			neverIngest: false,
			strength: 84,
			lastContact: "2026-09-24T16:00:00.000Z",
			channels: {
				email: 33,
				teams: 0,
				meetings: 3,
			},
			topics: ["t-gsales", "t-trip"],
			isSample: true,
		},
		{
			id: "p-luis",
			name: "Luis Ortega",
			initials: "LO",
			email: "luis.ortega@google.com",
			accountId: "google",
			title: "Account Executive",
			relationship: "Client",
			color: "#3aa373",
			vip: false,
			neverIngest: false,
			strength: 55,
			lastContact: "2026-09-22T16:00:00.000Z",
			channels: {
				email: 12,
				teams: 0,
				meetings: 2,
			},
			topics: ["t-gsales"],
			isSample: true,
		},
		{
			id: "p-ken",
			name: "Ken Watanabe",
			initials: "KW",
			email: "ken.watanabe@google.com",
			accountId: "google",
			title: "Procurement Manager",
			relationship: "Client",
			color: "#58b88b",
			vip: false,
			neverIngest: false,
			strength: 40,
			lastContact: "2026-09-23T16:00:00.000Z",
			channels: {
				email: 6,
				teams: 0,
				meetings: 0,
			},
			topics: [],
			isSample: true,
		},
		{
			id: "p-raj",
			name: "Raj Mehta",
			initials: "RM",
			email: "rajmehta@deloitte.com",
			accountId: "deloitte",
			title: "Senior Manager",
			relationship: "Peer",
			color: "#3d7a57",
			vip: false,
			neverIngest: false,
			strength: 88,
			lastContact: "2026-09-24T16:00:00.000Z",
			channels: {
				email: 52,
				teams: 140,
				meetings: 12,
			},
			topics: ["t-geng", "t-gsales"],
			isSample: true,
		},
		{
			id: "p-pete",
			name: "Pete Olsen",
			initials: "PO",
			email: "peolsen@deloitte.com",
			accountId: "deloitte",
			title: "Managing Director",
			relationship: "Exec sponsor",
			color: "#7a4fc2",
			vip: true,
			neverIngest: false,
			strength: 81,
			lastContact: "2026-09-24T16:00:00.000Z",
			channels: {
				email: 28,
				teams: 35,
				meetings: 9,
			},
			topics: ["t-oslt", "t-board", "t-budget"],
			isSample: true,
		},
		{
			id: "p-sarah",
			name: "Sarah Kim",
			initials: "SK",
			email: "sarahkim@deloitte.com",
			accountId: "deloitte",
			title: "Principal",
			relationship: "Senior stakeholder",
			color: "#b04a8c",
			vip: true,
			neverIngest: false,
			strength: 74,
			lastContact: "2026-09-23T16:00:00.000Z",
			channels: {
				email: 22,
				teams: 18,
				meetings: 7,
			},
			topics: ["t-oslt", "t-board"],
			isSample: true,
		},
		{
			id: "p-laura",
			name: "Laura Brooks",
			initials: "LB",
			email: "labrooks@deloitte.com",
			accountId: "deloitte",
			title: "Finance Director",
			relationship: "Stakeholder",
			color: "#0f8a8a",
			vip: false,
			neverIngest: false,
			strength: 58,
			lastContact: "2026-09-24T16:00:00.000Z",
			channels: {
				email: 15,
				teams: 4,
				meetings: 3,
			},
			topics: ["t-oslt", "t-budget"],
			isSample: true,
		},
		{
			id: "p-jordan",
			name: "Jordan Blake",
			initials: "JB",
			email: "jorblake@deloitte.com",
			accountId: "deloitte",
			title: "Executive Assistant",
			relationship: "Your EA",
			color: "#d17a16",
			vip: false,
			neverIngest: false,
			strength: 79,
			lastContact: "2026-09-24T16:40:00.000Z",
			channels: {
				email: 20,
				teams: 95,
				meetings: 0,
			},
			topics: ["t-trip"],
			isSample: true,
		},
		{
			id: "p-anika",
			name: "Anika Shah",
			initials: "AS",
			email: "anishah@deloitte.com",
			accountId: "deloitte",
			title: "Senior Consultant",
			relationship: "Your team",
			color: "#5a9270",
			vip: false,
			neverIngest: false,
			strength: 69,
			lastContact: "2026-09-24T16:00:00.000Z",
			channels: {
				email: 30,
				teams: 210,
				meetings: 15,
			},
			topics: [],
			isSample: true,
		},
		{
			id: "p-chris",
			name: "Chris Alvarez",
			initials: "CA",
			email: "calvarez@nvidia.com",
			accountId: "nvidia",
			title: "Alliance Manager",
			relationship: "Client",
			color: "#5f8a1e",
			vip: false,
			neverIngest: false,
			strength: 49,
			lastContact: "2026-09-22T16:00:00.000Z",
			channels: {
				email: 11,
				teams: 0,
				meetings: 2,
			},
			topics: ["t-nvidia"],
			isSample: true,
		},
		{
			id: "p-concur",
			name: "Concur Travel",
			initials: "CT",
			email: "noreply@concur.com",
			accountId: "other",
			title: "Automated",
			relationship: "Automated",
			color: "#8a9099",
			vip: false,
			neverIngest: false,
			strength: 0,
			lastContact: "2026-09-24T16:00:00.000Z",
			channels: {
				email: 7,
				teams: 0,
				meetings: 0,
			},
			topics: [],
			automated: true,
			isSample: true,
		},
	],
	threads: [
		{
			id: "th-geng-review",
			channel: "email",
			subject: "Agent architecture at our Oct 15 eng review?",
			topicLinks: [
				{
					topicId: "t-geng",
					source: "confirmed",
					confidence: 93,
					primary: true,
				},
				{
					topicId: "t-trip",
					source: "suggested",
					confidence: 48,
					primary: false,
				},
			],
			participants: [
				{
					personId: "p-priya",
					role: "from",
					included: true,
				},
				{
					personId: "me",
					role: "to",
					included: true,
				},
				{
					personId: "p-marcus",
					role: "cc",
					included: true,
				},
				{
					personId: "p-raj",
					role: "cc",
					included: true,
				},
				{
					personId: "p-tom",
					role: "cc",
					included: false,
					excludedBy: "you",
					excludedOn: "2026-09-22T16:00:00.000Z",
					hiddenCount: 2,
				},
			],
			muted: false,
			messageCount: 5,
			lastAt: "2026-09-24T13:02:00.000Z",
			roomId: null,
			summary:
				"Priya offered a 45-min slot at Google's Oct 15 eng leadership review for the agent architecture. Raj can demo the two pilot use cases. Marcus wants to see server-side tool permission enforcement. Priya needs an answer by Friday.",
			isSample: true,
		},
		{
			id: "th-sandbox",
			channel: "email",
			subject: "Sandbox access for pilot team",
			topicLinks: [
				{
					topicId: "t-geng",
					source: "confirmed",
					confidence: 96,
					primary: true,
				},
			],
			participants: [
				{
					personId: "me",
					role: "from",
					included: true,
				},
				{
					personId: "p-marcus",
					role: "to",
					included: true,
				},
				{
					personId: "p-anika",
					role: "cc",
					included: true,
				},
			],
			muted: false,
			messageCount: 2,
			lastAt: "2026-09-21T20:10:00.000Z",
			roomId: null,
			summary:
				"You asked Marcus for sandbox access for Anika and Raj on Monday. No reply yet.",
			isSample: true,
		},
		{
			id: "th-raj-chat",
			channel: "teams",
			subject: "Raj Mehta (chat)",
			topicLinks: [
				{
					topicId: "t-geng",
					source: "suggested",
					confidence: 61,
					primary: true,
				},
				{
					topicId: "t-gsales",
					source: "suggested",
					confidence: 55,
					primary: false,
				},
			],
			needsTopicChoice: true,
			participants: [
				{
					personId: "p-raj",
					role: "member",
					included: true,
				},
				{
					personId: "me",
					role: "member",
					included: true,
				},
			],
			muted: false,
			messageCount: 14,
			lastAt: "2026-09-24T15:40:00.000Z",
			roomId: null,
			summary:
				"Raj is splitting time between the demo environment for the eng review and pricing inputs Dana asked for.",
			isSample: true,
		},
		{
			id: "th-procurement",
			channel: "email",
			subject: "Procurement questions: pricing and security",
			topicLinks: [
				{
					topicId: "t-gsales",
					source: "confirmed",
					confidence: 90,
					primary: true,
				},
				{
					topicId: "t-budget",
					source: "you",
					confidence: 100,
					primary: false,
				},
			],
			participants: [
				{
					personId: "p-ken",
					role: "from",
					included: true,
				},
				{
					personId: "p-dana",
					role: "to",
					included: true,
				},
				{
					personId: "me",
					role: "to",
					included: true,
				},
				{
					personId: "p-luis",
					role: "cc",
					included: true,
				},
			],
			muted: false,
			messageCount: 3,
			lastAt: "2026-09-23T21:22:00.000Z",
			roomId: null,
			summary:
				"Ken sent 6 pricing questions in Google's template and a 40-question security questionnaire. Dana asked you to own the pricing answers.",
			isSample: true,
		},
		{
			id: "th-gtm-invite",
			channel: "calendar",
			subject: "Google x Deloitte GTM sync",
			topicLinks: [
				{
					topicId: "t-gsales",
					source: "confirmed",
					confidence: 88,
					primary: true,
				},
			],
			participants: [
				{
					personId: "p-dana",
					role: "organizer",
					included: true,
				},
				{
					personId: "p-luis",
					role: "required",
					included: true,
				},
				{
					personId: "p-raj",
					role: "required",
					included: true,
				},
				{
					personId: "me",
					role: "required",
					included: true,
				},
			],
			muted: false,
			messageCount: 1,
			lastAt: "2026-09-24T11:55:00.000Z",
			roomId: null,
			when: "Tue Sep 29, 2:00 - 2:45 PM ET",
			conflict: "Overlaps 'Anika 1:1' (2:00 - 2:30 PM)",
			summary:
				"Dana invited you to a 45-min GTM sync. It overlaps your 1:1 with Anika.",
			isSample: true,
		},
		{
			id: "th-oslt-chat",
			channel: "teams",
			subject: "OSLT prep (group chat)",
			topicLinks: [
				{
					topicId: "t-oslt",
					source: "confirmed",
					confidence: 95,
					primary: true,
				},
				{
					topicId: "t-budget",
					source: "confirmed",
					confidence: 58,
					primary: false,
				},
				{
					topicId: "t-board",
					source: "suggested",
					confidence: 41,
					primary: false,
				},
			],
			participants: [
				{
					personId: "p-pete",
					role: "member",
					included: true,
				},
				{
					personId: "p-sarah",
					role: "member",
					included: true,
				},
				{
					personId: "p-laura",
					role: "member",
					included: true,
				},
				{
					personId: "me",
					role: "member",
					included: true,
				},
			],
			muted: false,
			messageCount: 23,
			lastAt: "2026-09-24T16:15:00.000Z",
			roomId: null,
			summary:
				"Pete wants your build vs buy view on the AI platform before Friday's OSLT, including the FY27 impact. Sarah will reuse the outcome on the board slide.",
			isSample: true,
		},
		{
			id: "th-board-deck",
			channel: "email",
			subject: "Board deck - AI slide by Monday",
			topicLinks: [
				{
					topicId: "t-board",
					source: "confirmed",
					confidence: 97,
					primary: true,
				},
			],
			participants: [
				{
					personId: "p-sarah",
					role: "from",
					included: true,
				},
				{
					personId: "me",
					role: "to",
					included: true,
				},
				{
					personId: "p-pete",
					role: "cc",
					included: true,
				},
			],
			muted: false,
			messageCount: 2,
			lastAt: "2026-09-23T22:40:00.000Z",
			roomId: null,
			summary:
				"Sarah needs one AI slide for the Q4 board readout by Monday, using the OSLT recommendation.",
			isSample: true,
		},
		{
			id: "th-budget-lines",
			channel: "email",
			subject: "FY27 tooling line items - approval needed",
			topicLinks: [
				{
					topicId: "t-budget",
					source: "confirmed",
					confidence: 94,
					primary: true,
				},
				{
					topicId: "t-oslt",
					source: "suggested",
					confidence: 52,
					primary: false,
				},
			],
			participants: [
				{
					personId: "p-laura",
					role: "from",
					included: true,
				},
				{
					personId: "me",
					role: "to",
					included: true,
				},
				{
					personId: "p-pete",
					role: "cc",
					included: true,
				},
			],
			muted: false,
			messageCount: 1,
			lastAt: "2026-09-24T14:05:00.000Z",
			roomId: null,
			summary:
				"Laura needs approval of 4 tooling line items ($412K total) by Wednesday.",
			isSample: true,
		},
		{
			id: "th-jordan-chat",
			channel: "teams",
			subject: "Jordan Blake (chat)",
			topicLinks: [
				{
					topicId: "t-trip",
					source: "confirmed",
					confidence: 91,
					primary: true,
				},
			],
			participants: [
				{
					personId: "p-jordan",
					role: "member",
					included: true,
				},
				{
					personId: "me",
					role: "member",
					included: true,
				},
			],
			muted: false,
			messageCount: 9,
			lastAt: "2026-09-24T16:40:00.000Z",
			roomId: null,
			summary:
				"Jordan offered to hold 5-6 PM Oct 14 for the Google sales happy hour and asked about flights.",
			isSample: true,
		},
		{
			id: "th-concur",
			channel: "email",
			subject: "Trip to San Francisco: itinerary pending approval",
			topicLinks: [
				{
					topicId: "t-trip",
					source: "confirmed",
					confidence: 89,
					primary: true,
				},
			],
			participants: [
				{
					personId: "p-concur",
					role: "from",
					included: true,
				},
				{
					personId: "me",
					role: "to",
					included: true,
				},
			],
			muted: false,
			messageCount: 1,
			lastAt: "2026-09-24T12:30:00.000Z",
			roomId: null,
			automated: true,
			summary:
				"Concur itinerary created; approval needed before tickets are issued.",
			isSample: true,
		},
		{
			id: "th-nvidia",
			channel: "email",
			subject: "Follow-up: Q1 GPU capacity reservation",
			topicLinks: [
				{
					topicId: "t-nvidia",
					source: "confirmed",
					confidence: 95,
					primary: true,
				},
			],
			participants: [
				{
					personId: "p-chris",
					role: "from",
					included: true,
				},
				{
					personId: "me",
					role: "to",
					included: true,
				},
			],
			muted: false,
			messageCount: 2,
			lastAt: "2026-09-22T19:15:00.000Z",
			roomId: null,
			summary: "Chris needs a yes/no on holding 64 GPUs for Q1 by Oct 1.",
			isSample: true,
		},
		{
			id: "th-security-q",
			channel: "email",
			subject: "Security questionnaire - vendor onboarding",
			topicLinks: [
				{
					topicId: "t-gsales",
					source: "suggested",
					confidence: 44,
					primary: true,
				},
			],
			needsTopicChoice: true,
			participants: [
				{
					personId: "p-ken",
					role: "from",
					included: true,
				},
				{
					personId: "me",
					role: "to",
					included: true,
				},
			],
			muted: false,
			messageCount: 1,
			lastAt: "2026-09-23T21:30:00.000Z",
			roomId: null,
			summary:
				"Separate security questionnaire thread; Brain suggests a new topic 'Google - Security review'.",
			isSample: true,
		},
		{
			id: "th-newsletter",
			channel: "email",
			subject: "Cloud Next recap: 12 launches you missed",
			topicLinks: [],
			participants: [
				{
					personId: "p-tom",
					role: "from",
					included: false,
					excludedBy: "rule",
					excludedOn: "2026-09-01T12:00:00.000Z",
				},
			],
			muted: true,
			messageCount: 1,
			lastAt: "2026-09-24T10:00:00.000Z",
			roomId: null,
			automated: true,
			summary: "Marketing newsletter. Skipped.",
			isSample: true,
		},
	],
	items: [
		{
			id: "i1",
			threadId: "th-geng-review",
			channel: "email",
			actorId: "p-priya",
			title: "Confirm Oct 15 architecture review slot with Priya",
			askType: "reply",
			priority: "P0",
			score: 91,
			reasons: [
				"Direct ask to you",
				"VIP client",
				"Due Fri",
				"Unanswered 28h",
			],
			due: "2026-09-25T16:00:00.000Z",
			received: "2026-09-22T13:14:00.000Z",
			status: "open",
			topicIds: ["t-geng", "t-trip"],
			isSample: true,
		},
		{
			id: "i2",
			threadId: "th-oslt-chat",
			channel: "teams",
			actorId: "p-pete",
			title: "Give Pete your build vs buy view on the AI platform",
			askType: "reply",
			priority: "P1",
			score: 84,
			reasons: [
				"Exec asked you directly",
				"Due today",
				"OSLT tomorrow 8:30 AM",
			],
			due: "2026-09-24T21:00:00.000Z",
			received: "2026-09-24T16:15:00.000Z",
			status: "open",
			topicIds: ["t-oslt", "t-budget"],
			isSample: true,
		},
		{
			id: "i3",
			threadId: "th-procurement",
			channel: "email",
			actorId: "p-ken",
			title: "Answer Google procurement pricing questions",
			askType: "review",
			priority: "P1",
			score: 78,
			reasons: ["Dana assigned you", "Client", "6 open questions"],
			due: "2026-09-28T16:00:00.000Z",
			received: "2026-09-23T21:22:00.000Z",
			status: "open",
			topicIds: ["t-gsales", "t-budget"],
			isSample: true,
		},
		{
			id: "i4",
			threadId: "th-gtm-invite",
			channel: "calendar",
			actorId: "p-dana",
			title: "Respond: Google x Deloitte GTM sync (Tue 2 PM)",
			askType: "attend",
			priority: "P1",
			score: 72,
			reasons: [
				"Invite not answered",
				"Conflict with Anika 1:1",
				"VIP organizer",
			],
			due: "2026-09-29T16:00:00.000Z",
			received: "2026-09-24T11:55:00.000Z",
			status: "open",
			topicIds: ["t-gsales"],
			isSample: true,
		},
		{
			id: "i5",
			threadId: "th-board-deck",
			channel: "email",
			actorId: "p-sarah",
			title: "Send AI slide for the Q4 board deck",
			askType: "review",
			priority: "P1",
			score: 70,
			reasons: ["VIP", "Due Mon", "Depends on OSLT outcome"],
			due: "2026-09-28T16:00:00.000Z",
			received: "2026-09-23T22:40:00.000Z",
			status: "open",
			topicIds: ["t-board"],
			isSample: true,
		},
		{
			id: "i6",
			threadId: "th-jordan-chat",
			channel: "teams",
			actorId: "p-jordan",
			title: "Tell Jordan whether to hold Oct 14 happy hour",
			askType: "reply",
			priority: "P2",
			score: 61,
			reasons: ["Direct question", "Trip in 20 days"],
			due: "2026-09-25T16:00:00.000Z",
			received: "2026-09-24T16:40:00.000Z",
			status: "open",
			topicIds: ["t-trip", "t-gsales"],
			isSample: true,
		},
		{
			id: "i7",
			threadId: "th-jordan-chat",
			channel: "task",
			actorId: "assistant",
			title: "Book flights to SFO (arrive Oct 13 evening)",
			askType: "errand",
			priority: "P2",
			score: 58,
			reasons: [
				"Suggested by assistant",
				"Fares rising",
				"Concur approval pending",
			],
			due: "2026-09-30T16:00:00.000Z",
			received: "2026-09-24T16:00:00.000Z",
			status: "open",
			topicIds: ["t-trip"],
			suggested: true,
			isSample: true,
		},
		{
			id: "i8",
			threadId: "th-jordan-chat",
			channel: "task",
			actorId: "assistant",
			title: "Dinner for 6 near Google Mountain View, Oct 14",
			askType: "errand",
			priority: "P2",
			score: 55,
			reasons: ["Suggested by assistant", "Goal on Google onsite"],
			due: "2026-10-07T16:00:00.000Z",
			received: "2026-09-24T16:00:00.000Z",
			status: "open",
			topicIds: ["t-trip", "t-gsales"],
			suggested: true,
			isSample: true,
		},
		{
			id: "i9",
			threadId: "th-budget-lines",
			channel: "email",
			actorId: "p-laura",
			title: "Approve FY27 tooling line items ($412K)",
			askType: "approve",
			priority: "P2",
			score: 57,
			reasons: ["Approval requested", "Due Wed"],
			due: "2026-09-30T16:00:00.000Z",
			received: "2026-09-24T14:05:00.000Z",
			status: "open",
			topicIds: ["t-budget"],
			isSample: true,
		},
		{
			id: "i10",
			threadId: "th-concur",
			channel: "email",
			actorId: "p-concur",
			title: "Approve Concur itinerary (SFO, Oct 13-15)",
			askType: "approve",
			priority: "P2",
			score: 50,
			reasons: ["Automated but needs action", "Blocks ticketing"],
			due: "2026-09-25T16:00:00.000Z",
			received: "2026-09-24T12:30:00.000Z",
			status: "open",
			topicIds: ["t-trip"],
			isSample: true,
		},
		{
			id: "i11",
			threadId: "th-nvidia",
			channel: "email",
			actorId: "p-chris",
			title: "Yes/no on holding 64 GPUs for Q1",
			askType: "reply",
			priority: "P2",
			score: 48,
			reasons: ["Direct ask", "Due Oct 1"],
			due: "2026-10-01T16:00:00.000Z",
			received: "2026-09-22T19:15:00.000Z",
			status: "open",
			topicIds: ["t-nvidia"],
			isSample: true,
		},
		{
			id: "i12",
			threadId: "th-sandbox",
			channel: "email",
			actorId: "p-marcus",
			title: "Waiting on Marcus: sandbox access",
			askType: "waiting_on",
			priority: "P3",
			score: 35,
			reasons: ["You asked 3 days ago", "Blocks demo prep"],
			due: null,
			received: "2026-09-21T20:10:00.000Z",
			status: "waiting",
			topicIds: ["t-geng"],
			isSample: true,
		},
	],
	reviews: [
		{
			id: "r1",
			kind: "new_topic",
			text: "New topic suggested: Google - Security review",
			detail: "6 threads, 3 new google.com people",
			refId: "st-gsec",
			actions: ["Accept", "Merge into Google - Sales / GTM", "Ignore"],
			status: "open",
			candidate: {
				name: "Google - Security review",
				accountId: "google",
				mergeCandidate: "t-gsales",
			},
		},
		{
			id: "r2",
			kind: "topic_choice",
			text: "Raj Mehta's Teams chat fits two topics",
			detail: "Google Eng 61% / Google Sales 55%",
			refId: "th-raj-chat",
			actions: ["Both", "Google Eng", "Google Sales"],
			status: "open",
		},
		{
			id: "r3",
			kind: "add_person",
			text: "Add Ken Watanabe to Google - Sales / GTM?",
			detail: "New on 3 Sales threads this week",
			refId: "p-ken",
			actions: ["Add", "Not now"],
			status: "open",
			topicId: "t-gsales",
		},
		{
			id: "r5",
			kind: "unassigned",
			text: "One loaded thread has no topic",
			detail: "Review the sample newsletter and decide whether to file it.",
			refId: null,
			actions: ["Review"],
			status: "open",
		},
	],
	accounts: [
		{
			id: "google",
			name: "Google",
			domain: "google.com",
			kind: "client",
			color: "#2d6fd0",
		},
		{
			id: "nvidia",
			name: "Nvidia",
			domain: "nvidia.com",
			kind: "client",
			color: "#5f8a1e",
		},
		{
			id: "deloitte",
			name: "Deloitte (internal)",
			domain: "deloitte.com",
			kind: "internal",
			color: "#3d7a57",
		},
		{
			id: "other",
			name: "Other / vendors",
			domain: "",
			kind: "other",
			color: "#8a9099",
		},
	],
	profile: {
		id: "me",
		name: "Kunal Patel",
		initials: "KP",
		email: "kunalppatel9@deloitte.com",
		org: "Deloitte",
		role: {
			value: "AI engineering lead",
			source: "learned",
			note: "From email signature - confirm",
		},
		timezone: "America/New_York",
		workingHours: "8:00 - 18:30 ET",
		vips: ["p-priya", "p-pete", "p-sarah", "p-dana"],
		style: {
			summary:
				"Short and direct. Warm one-line opener, bullets for asks, signs off '- Kunal'.",
			source: "learned",
			confirmed: true,
			examples: [
				"Thanks Priya - quick answers below.",
				"Can you confirm by Fri?",
			],
		},
	},
	liveProfile: null,
	settings: {
		classifierEngineId: "",
		fileAt: 85,
		askAt: 40,
		sourcesJson: {
			email: false,
			calendar: false,
			teams: false,
		},
		version: 1,
	},
	rules: [
		{
			id: "sample-rule-1",
			kind: "never_folder",
			value: "Personal",
			createdBy: "you",
			createdAt: "2026-08-01T00:00:00.000Z",
			isSample: true,
		},
		{
			id: "sample-rule-2",
			kind: "never_sender",
			value: "benefits@deloitte.com",
			note: "HR / benefits",
			createdBy: "you",
			createdAt: "2026-08-01T00:00:00.000Z",
			isSample: true,
		},
		{
			id: "sample-rule-3",
			kind: "never_keyword",
			value: "performance review",
			createdBy: "you",
			createdAt: "2026-08-01T00:00:00.000Z",
			isSample: true,
		},
	],
	sources: [
		{
			id: "email",
			label: "Outlook mail",
			mark: "E",
			status: "connected",
			lastSync: "2026-09-24T16:00:00.000Z",
			scope: "Inbox + Sent Items, last 90 days",
			volume: "4,212 messages",
			permission: "Mail.Read (delegated)",
			isSample: true,
		},
		{
			id: "calendar",
			label: "Outlook calendar",
			mark: "C",
			status: "connected",
			lastSync: "2026-09-24T16:00:00.000Z",
			scope: "Primary calendar, -30 / +60 days",
			volume: "318 events",
			permission: "Calendars.Read (delegated)",
			isSample: true,
		},
		{
			id: "teams",
			label: "Teams chats",
			mark: "T",
			status: "needs_permission",
			lastSync: null,
			scope: "1:1 and group chats",
			volume: null,
			permission: "Chat.Read (delegated) - pending approval",
			isSample: true,
		},
		{
			id: "teamsChannels",
			label: "Teams channels",
			mark: "T",
			status: "off",
			lastSync: null,
			scope: "Not in pilot scope",
			volume: null,
			permission: "ChannelMessage.Read.All - not requested",
			isSample: true,
		},
		{
			id: "files",
			label: "OneDrive / SharePoint",
			mark: "F",
			status: "off",
			lastSync: null,
			scope: "Attachments only for now",
			volume: null,
			permission: "Sites.Selected - later",
			isSample: true,
		},
	],
	workspaces: {
		"th-geng-review": {
			goal: "Lock the Oct 15 review: 45-min slot, attendee list, pre-read to Priya by Oct 13.",
			facts: [
				{
					text: "Priya prefers a written pre-read 48h before reviews.",
					from: "Topic note - Google Eng (you)",
					status: "confirmed",
					id: "th-geng-review-fact-1",
				},
				{
					text: "Pilot scope is limited to 2 use cases.",
					from: "Email from Raj, Sep 20",
					status: "draft",
					id: "th-geng-review-fact-2",
					sourcePersonId: "p-raj",
				},
				{
					text: "You are onsite in Mountain View Oct 14-15.",
					from: "Topic - Google onsite",
					status: "confirmed",
					id: "th-geng-review-fact-3",
				},
				{
					text: "Raj owns the demo environment.",
					from: "Brain - people",
					status: "confirmed",
					id: "th-geng-review-fact-4",
				},
			],
			messages: [
				{
					id: "m1",
					fromId: "p-priya",
					at: "2026-09-22T13:14:00.000Z",
					text: "Hi Kunal - our eng leadership review on Oct 15 has a slot open. Could your team walk us through the agent architecture? 45 min, about 12 attendees. Let me know by Friday if that works.",
				},
				{
					id: "m2",
					fromId: "p-tom",
					at: "2026-09-22T14:02:00.000Z",
					text: "Reminder: registration for the Google Cloud Partner Summit closes Friday!",
					excluded: true,
				},
				{
					id: "m3",
					fromId: "p-raj",
					at: "2026-09-22T15:30:00.000Z",
					text: "I can drive the live demo if we keep it to the two pilot use cases.",
				},
				{
					id: "m4",
					fromId: "p-marcus",
					at: "2026-09-23T20:45:00.000Z",
					text: "We'd want to see how tool permissions are enforced server-side, not just in the UI.",
				},
				{
					id: "m5",
					fromId: "p-tom",
					at: "2026-09-23T21:00:00.000Z",
					text: "Last call for Partner Summit sessions - reply to reserve a seat.",
					excluded: true,
				},
			],
			steps: [
				{
					id: "a1",
					text: "Reply to Priya confirming Oct 15",
					ownerId: "me",
					due: "2026-09-25T16:00:00.000Z",
					status: "draft_ready",
					kind: "reply",
					itemId: "i1",
				},
				{
					id: "a2",
					text: "Send pre-read to Priya's team",
					ownerId: "me",
					due: "2026-10-13T16:00:00.000Z",
					status: "open",
					kind: "task",
				},
				{
					id: "a3",
					text: "Ask Raj to confirm demo env covers both use cases",
					ownerId: "p-raj",
					due: null,
					status: "suggested",
					kind: "task",
				},
				{
					id: "a4",
					text: "Sandbox access for pilot team",
					ownerId: "p-marcus",
					due: null,
					status: "waiting",
					kind: "waiting_on",
					itemId: "i12",
				},
				{
					id: "a5",
					text: "Book flights to SFO (arrive Oct 13)",
					ownerId: "me",
					due: "2026-09-30T16:00:00.000Z",
					status: "open",
					kind: "errand",
					linkTopicId: "t-trip",
					itemId: "i7",
				},
				{
					id: "a6",
					text: "Share mutual NDA with Google legal",
					ownerId: "me",
					due: null,
					status: "done",
					kind: "task",
				},
			],
			assets: [
				{
					name: "Agent architecture v3.pptx",
					kind: "pptx",
					size: "4.2 MB",
					source: "dropped",
					by: "you",
					when: "2026-09-23T16:00:00.000Z",
					id: "th-geng-review-asset-1",
					isSample: true,
				},
				{
					name: "Pilot use cases.docx",
					kind: "docx",
					size: "220 KB",
					source: "attachment",
					by: "Raj Mehta",
					when: "2026-09-20T16:00:00.000Z",
					id: "th-geng-review-asset-2",
					isSample: true,
				},
				{
					name: "Reply to Priya (draft)",
					kind: "draft",
					size: "",
					source: "generated",
					by: "assistant",
					when: "2026-09-24T16:00:00.000Z",
					id: "th-geng-review-asset-3",
					isSample: true,
				},
			],
			drafts: [
				{
					to: "Priya Raman",
					cc: "Marcus Chen, Raj Mehta",
					subject: "Re: Agent architecture at our Oct 15 eng review?",
					body: "Hi Priya,\n\nThanks for the slot - Oct 15 works, and 45 minutes is right.\n\n- Raj will run a live demo of the two pilot use cases.\n- We will send a pre-read by Oct 13.\n- Marcus: we will walk through how tool permissions are enforced server-side.\n\nCould you share the attendee list so we can tailor the depth?\n\n- Kunal",
					id: "th-geng-review-draft-2",
					isSample: true,
				},
			],
			suggestions: [
				"Outline the pre-read",
				"Hold Oct 15 10:00 PT on my calendar",
				"Ask Raj to confirm the demo environment",
			],
			sampleChat: [
				{
					id: "th-geng-review-chat-1",
					role: "user",
					text: "Draft a reply to Priya: yes for Oct 15, 45 min works, Raj demos, pre-read by Oct 13. Ask for the attendee list.",
				},
				{
					id: "th-geng-review-chat-2",
					role: "assistant",
					text: "Draft ready. I kept your usual tone with Priya (warm, brief). I left out Tom Becker's two messages because you excluded him from this thread. Marcus asked about server-side tool permissions, so I added one line saying we will cover it.",
					citations: [
						"Priya, Tue 9:14 AM",
						"Raj, Tue 11:30 AM",
						"Marcus, Wed 4:45 PM",
						"Topic note: pre-read 48h",
					],
				},
			],
			related: [
				{
					threadId: "th-sandbox",
					why: "Same topic, blocks demo prep",
				},
				{
					threadId: "th-gtm-invite",
					why: "Same account (Google)",
				},
				{
					threadId: "th-jordan-chat",
					why: "Onsite logistics for Oct 14-15",
				},
			],
			meetings: [
				{
					title: "Google eng leadership review",
					when: "Thu Oct 15, 10:00 - 10:45 AM PT",
					state: "Tentative hold",
				},
			],
		},
		"th-oslt-chat": {
			goal: "Give Pete a one-page build vs buy recommendation, numbers first, before Friday's OSLT.",
			facts: [
				{
					text: "Pete wants one page, numbers first.",
					from: "Topic note - OSLT (you)",
					status: "confirmed",
					id: "th-oslt-chat-fact-1",
				},
				{
					text: "Tooling line items total $412K for FY27.",
					from: "Email from Laura, today",
					status: "confirmed",
					id: "th-oslt-chat-fact-2",
					sourcePersonId: "p-laura",
				},
				{
					text: "Sarah will reuse the recommendation on the board slide.",
					from: "OSLT prep chat",
					status: "draft",
					id: "th-oslt-chat-fact-3",
				},
			],
			messages: [
				{
					id: "o1",
					fromId: "p-pete",
					at: "2026-09-24T15:50:00.000Z",
					text: "Kunal, need your view on the platform ask before Fri. Build vs buy, and what it does to FY27.",
				},
				{
					id: "o2",
					fromId: "p-laura",
					at: "2026-09-24T16:02:00.000Z",
					text: "Tooling lines are in my email from this morning - $412K as proposed.",
				},
				{
					id: "o3",
					fromId: "p-sarah",
					at: "2026-09-24T16:15:00.000Z",
					text: "Whatever we land here goes on the board slide, so keep it crisp.",
				},
			],
			steps: [
				{
					id: "b1",
					text: "Reply to Pete with recommendation",
					ownerId: "me",
					due: "2026-09-24T21:00:00.000Z",
					status: "open",
					kind: "reply",
					itemId: "i2",
				},
				{
					id: "b2",
					text: "Confirm 3-year cost assumption with Laura",
					ownerId: "p-laura",
					due: null,
					status: "suggested",
					kind: "task",
				},
				{
					id: "b3",
					text: "Reuse for board AI slide",
					ownerId: "me",
					due: "2026-09-21T16:00:00.000Z",
					status: "open",
					kind: "task",
					linkTopicId: "t-board",
					itemId: "i5",
				},
			],
			assets: [
				{
					name: "Platform options v2.xlsx",
					kind: "xlsx",
					size: "88 KB",
					source: "attachment",
					by: "Laura Brooks",
					when: "2026-09-24T16:00:00.000Z",
					id: "th-oslt-chat-asset-1",
					isSample: true,
				},
			],
			drafts: [],
			suggestions: [
				"Turn this into a reply to Pete",
				"Draft the board slide from this",
				"What did Pete push back on last time?",
			],
			sampleChat: [
				{
					id: "th-oslt-chat-chat-1",
					role: "user",
					text: "Summarize build vs buy tradeoffs from the last 3 OSLT threads and Laura's budget email. One page, numbers first.",
				},
				{
					id: "th-oslt-chat-chat-2",
					role: "assistant",
					text: "Here is a one-page outline. Buy is faster (8 weeks) but 1.6x the 3-year cost; build reuses the platform team and fits inside the $412K tooling line if we defer one hire. I flagged one number I could not source.",
					citations: [
						"OSLT prep chat",
						"Laura, today 10:05 AM",
						"OSLT notes Sep 10",
					],
				},
			],
			related: [
				{
					threadId: "th-budget-lines",
					why: "FY27 numbers",
				},
				{
					threadId: "th-board-deck",
					why: "Reuses this outcome",
				},
			],
			meetings: [
				{
					title: "OSLT",
					when: "Fri Sep 25, 8:30 - 9:30 AM ET",
					state: "Accepted",
				},
			],
		},
		"th-jordan-chat": {
			goal: "Arrive Mountain View Oct 13 evening; host the Google sales happy hour Oct 14 5-6 PM; dinner for 6 at 7:30 PM.",
			facts: [
				{
					text: "Keep dinner under the client-entertainment limit; one guest is vegetarian.",
					from: "Topic note - Google onsite (you)",
					status: "confirmed",
					id: "th-jordan-chat-fact-1",
				},
				{
					text: "Concur itinerary is waiting for your approval.",
					from: "Concur email, today",
					status: "confirmed",
					id: "th-jordan-chat-fact-2",
				},
			],
			messages: [
				{
					id: "j1",
					fromId: "p-jordan",
					at: "2026-09-24T16:40:00.000Z",
					text: "Want me to hold 5-6 PM on Oct 14 for a happy hour with Dana's team? Also - do you want the 5:10 PM or 7:45 PM flight on the 13th?",
				},
			],
			steps: [
				{
					id: "c1",
					text: "Reply to Jordan about the happy hour hold",
					ownerId: "me",
					due: "2026-09-25T16:00:00.000Z",
					status: "open",
					kind: "reply",
					itemId: "i6",
				},
				{
					id: "c2",
					text: "Pick flight (5:10 PM vs 7:45 PM, Oct 13)",
					ownerId: "me",
					due: "2026-09-30T16:00:00.000Z",
					status: "open",
					kind: "errand",
					itemId: "i7",
				},
				{
					id: "c3",
					text: "Dinner for 6, Oct 14 7:30 PM",
					ownerId: "p-jordan",
					due: "2026-10-07T16:00:00.000Z",
					status: "suggested",
					kind: "errand",
					itemId: "i8",
				},
				{
					id: "c4",
					text: "Approve Concur itinerary",
					ownerId: "me",
					due: "2026-09-25T16:00:00.000Z",
					status: "open",
					kind: "approve",
					itemId: "i10",
				},
			],
			assets: [
				{
					name: "Concur itinerary SFO Oct 13-15.pdf",
					kind: "pdf",
					size: "130 KB",
					source: "attachment",
					by: "Concur",
					when: "2026-09-24T16:00:00.000Z",
					id: "th-jordan-chat-asset-1",
					isSample: true,
				},
			],
			drafts: [],
			suggestions: [
				"Draft a note to Jordan: hold happy hour + Option A",
				"Compare the two flights",
				"Approve the Concur itinerary",
			],
			sampleChat: [
				{
					id: "th-jordan-chat-chat-1",
					role: "user",
					text: "Find dinner options for 6 near Google Mountain View on Oct 14 at 7:30 PM. Private-ish, client appropriate, one vegetarian.",
				},
				{
					id: "th-jordan-chat-chat-2",
					role: "assistant",
					text: "Three options below. I cannot book: there is no reservation connector. I can draft a note to Jordan with your pick, or open the booking page.",
					options: [
						{
							name: "Option A - Californian, private room for 8",
							meta: "0.9 mi, $$$, vegetarian tasting menu",
						},
						{
							name: "Option B - Italian, semi-private booth",
							meta: "1.4 mi, $$, strong vegetarian options",
						},
						{
							name: "Option C - Japanese, chef counter for 6",
							meta: "2.1 mi, $$$$, over the entertainment limit",
						},
					],
				},
			],
			related: [
				{
					threadId: "th-concur",
					why: "Itinerary approval",
				},
				{
					threadId: "th-geng-review",
					why: "Reason for the trip",
				},
			],
			meetings: [
				{
					title: "Hold: Google sales happy hour",
					when: "Wed Oct 14, 5:00 - 6:00 PM PT",
					state: "Proposed by Jordan",
				},
			],
		},
	},
	openThreadIds: ["th-geng-review", "th-oslt-chat", "th-jordan-chat"],
	sequence: 1,
};

/** Return a fresh session; no sample room ID is sent to the backend. */
export function createInitialCollaborationState(): CollaborationState {
	return structuredClone(SAMPLE_STATE);
}
