import type { CollaborationState } from "./collaboration.types";

/** Fictional September 24 scenario normalized from mockups/assets/mock-data.js. */
const SAMPLE_STATE: CollaborationState = {
	today: "2026-09-24",
	topics: [
		{
			id: "t-geng",
			name: "Northwind - Engineering partnership",
			short: "Northwind Eng",
			accountId: "northwind",
			kind: "client",
			color: "#2d6fd0",
			status: "active",
			description:
				"Joint engineering work with Northwind Cloud AI: agent architecture review, sandbox access, integration pilot for two use cases.",
			goals: [
				{
					text: "Present agent architecture at Northwind eng review (Oct 15)",
					status: "open",
					noteId: "t-geng-goal-1",
				},
				{
					text: "Sandbox access for the pilot team",
					status: "open",
					noteId: "t-geng-goal-2",
				},
				{
					text: "Mutual NDA signed",
					status: "done",
					noteId: "t-geng-goal-3",
				},
			],
			keywords: [
				"agent architecture",
				"sandbox",
				"eng review",
				"Vertex",
				"pilot",
			],
			people: [
				{
					personId: "p-ava",
					role: "Northwind lead",
					engagement: 94,
					state: "member",
					origin: "brain",
				},
				{
					personId: "p-ben",
					role: "Northwind engineer",
					engagement: 71,
					state: "member",
					origin: "brain",
				},
				{
					personId: "p-hugo",
					role: "Contoso demo owner",
					engagement: 66,
					state: "member",
					origin: "you",
				},
				{
					personId: "p-chloe",
					role: "Northwind PM",
					engagement: 38,
					state: "suggested",
					origin: "brain",
					reason: "On 2 threads this week",
				},
				{
					personId: "p-dan",
					role: "Northwind events",
					engagement: 12,
					state: "removed",
					origin: "you",
					reason: "Removed by you Sep 22",
				},
			],
			calendarSeries: ["Northwind eng weekly (Tue 1:00 PM)"],
			stats: {
				threads: 3,
				openItems: 2,
				lastActivity: "2026-09-24T15:40:00.000Z",
			},
			isSample: true,
		},
		{
			id: "t-gsales",
			name: "Northwind - Sales / GTM",
			short: "Northwind Sales",
			accountId: "northwind",
			kind: "client",
			color: "#1f8a5b",
			status: "active",
			description:
				"Commercial track with Northwind partner sales: pricing, procurement, security questionnaire, joint GTM plan.",
			goals: [
				{
					text: "Answer procurement pricing questions",
					status: "open",
					noteId: "t-gsales-goal-1",
				},
				{
					text: "Agree joint GTM motion for Q1",
					status: "open",
					noteId: "t-gsales-goal-2",
				},
			],
			keywords: [
				"pricing",
				"procurement",
				"GTM",
				"security questionnaire",
				"MSA",
			],
			people: [
				{
					personId: "p-erin",
					role: "Northwind partner sales lead",
					engagement: 88,
					state: "member",
					origin: "brain",
				},
				{
					personId: "p-finn",
					role: "Northwind account exec",
					engagement: 57,
					state: "member",
					origin: "brain",
				},
				{
					personId: "p-gia",
					role: "Northwind procurement",
					engagement: 41,
					state: "suggested",
					origin: "brain",
					reason: "New on 3 Sales threads",
				},
				{
					personId: "p-hugo",
					role: "Contoso",
					engagement: 35,
					state: "member",
					origin: "brain",
				},
			],
			calendarSeries: [],
			stats: {
				threads: 4,
				openItems: 4,
				lastActivity: "2026-09-24T15:40:00.000Z",
			},
			isSample: true,
		},
		{
			id: "t-trip",
			name: "Northwind onsite - Seattle, Oct 14-15",
			short: "Northwind onsite",
			accountId: "northwind",
			kind: "event",
			color: "#d17a16",
			status: "active",
			description:
				"Logistics for the Seattle onsite: flights, hotel, happy hour with the Northwind sales team, client dinner for 6.",
			goals: [
				{
					text: "Arrive Seattle evening of Oct 13",
					status: "open",
					noteId: "t-trip-goal-1",
				},
				{
					text: "Host Northwind sales happy hour Oct 14, 5-6 PM",
					status: "open",
					noteId: "t-trip-goal-2",
				},
				{
					text: "Client dinner for 6 on Oct 14",
					status: "open",
					noteId: "t-trip-goal-3",
				},
			],
			keywords: [
				"flight",
				"hotel",
				"itinerary",
				"dinner",
				"happy hour",
				"Seattle",
			],
			people: [
				{
					personId: "p-leo",
					role: "Your EA",
					engagement: 80,
					state: "member",
					origin: "you",
				},
				{
					personId: "p-erin",
					role: "Happy hour host (Northwind)",
					engagement: 30,
					state: "member",
					origin: "brain",
				},
			],
			calendarSeries: [],
			stats: {
				threads: 3,
				openItems: 5,
				lastActivity: "2026-09-24T16:40:00.000Z",
			},
			isSample: true,
		},
		{
			id: "t-elt",
			name: "ELT - AI platform investment",
			short: "ELT",
			accountId: "contoso",
			kind: "internal",
			color: "#7a4fc2",
			status: "active",
			description:
				"Internal leadership forum (ELT). Current ask: build vs buy recommendation for the AI platform before Friday's session.",
			goals: [
				{
					text: "Give Ian a build vs buy recommendation before Fri ELT",
					status: "open",
					noteId: "t-elt-goal-1",
				},
			],
			keywords: ["ELT", "platform", "build vs buy", "investment"],
			people: [
				{
					personId: "p-ian",
					role: "Exec sponsor",
					engagement: 90,
					state: "member",
					origin: "brain",
				},
				{
					personId: "p-jade",
					role: "Principal",
					engagement: 52,
					state: "member",
					origin: "brain",
				},
				{
					personId: "p-kira",
					role: "Finance",
					engagement: 34,
					state: "member",
					origin: "brain",
				},
			],
			calendarSeries: ["ELT (Fri 8:30 AM, biweekly)"],
			stats: {
				threads: 2,
				openItems: 1,
				lastActivity: "2026-09-24T16:15:00.000Z",
			},
			isSample: true,
		},
		{
			id: "t-board",
			name: "Board readout - Q4",
			short: "Board",
			accountId: "contoso",
			kind: "internal",
			color: "#c43d3d",
			status: "active",
			description: "Q4 board readout. Owner of the AI slide.",
			goals: [
				{
					text: "Deliver AI slide to Jade by Mon Sep 28",
					status: "open",
					noteId: "t-board-goal-1",
				},
			],
			keywords: ["board", "readout", "slide", "deck"],
			people: [
				{
					personId: "p-jade",
					role: "Deck owner",
					engagement: 85,
					state: "member",
					origin: "brain",
				},
				{
					personId: "p-ian",
					role: "Reviewer",
					engagement: 40,
					state: "member",
					origin: "brain",
				},
			],
			calendarSeries: [],
			stats: {
				threads: 2,
				openItems: 1,
				lastActivity: "2026-09-24T16:15:00.000Z",
			},
			isSample: true,
		},
		{
			id: "t-budget",
			name: "FY27 Budget",
			short: "Budget",
			accountId: "contoso",
			kind: "internal",
			color: "#0f8a8a",
			status: "active",
			description:
				"FY27 planning: tooling and platform line items owned by the AI engineering team.",
			goals: [
				{
					text: "Approve tooling line items",
					status: "open",
					noteId: "t-budget-goal-1",
				},
			],
			keywords: ["FY27", "budget", "line items", "tooling", "forecast"],
			people: [
				{
					personId: "p-kira",
					role: "Finance director",
					engagement: 82,
					state: "member",
					origin: "brain",
				},
				{
					personId: "p-ian",
					role: "Approver",
					engagement: 45,
					state: "member",
					origin: "brain",
				},
			],
			calendarSeries: [],
			stats: {
				threads: 3,
				openItems: 3,
				lastActivity: "2026-09-24T16:15:00.000Z",
			},
			isSample: true,
		},
		{
			id: "t-fabrikam",
			name: "Fabrikam - GPU capacity",
			short: "Fabrikam",
			accountId: "fabrikam",
			kind: "client",
			color: "#5f8a1e",
			status: "active",
			description:
				"GPU capacity reservation and alliance follow-ups with Fabrikam.",
			goals: [
				{
					text: "Decide on Q1 capacity reservation",
					status: "open",
					noteId: "t-fabrikam-goal-1",
				},
			],
			keywords: ["GPU", "capacity", "reservation", "DGX"],
			people: [
				{
					personId: "p-noah",
					role: "Alliance manager",
					engagement: 76,
					state: "member",
					origin: "brain",
				},
			],
			calendarSeries: [],
			stats: {
				threads: 1,
				openItems: 1,
				lastActivity: "2026-09-22T19:15:00.000Z",
			},
			isSample: true,
		},
	],
	people: [
		{
			id: "p-ava",
			name: "Ava Reed",
			initials: "AR",
			email: "ava.reed@northwind.example",
			accountId: "northwind",
			title: "Director, Cloud AI Engineering",
			relationship: "Client lead",
			color: "#2d6fd0",
			vip: true,
			neverIngest: false,
			strength: 92,
			lastContact: "2026-09-24T16:00:00.000Z",
			channels: {
				email: 41,
				teams: 0,
				meetings: 6,
			},
			topics: ["t-geng"],
			isSample: true,
		},
		{
			id: "p-ben",
			name: "Ben Carter",
			initials: "BC",
			email: "ben.carter@northwind.example",
			accountId: "northwind",
			title: "Staff Software Engineer",
			relationship: "Client",
			color: "#4a86e0",
			vip: false,
			neverIngest: false,
			strength: 70,
			lastContact: "2026-09-23T16:00:00.000Z",
			channels: {
				email: 18,
				teams: 0,
				meetings: 4,
			},
			topics: ["t-geng"],
			isSample: true,
		},
		{
			id: "p-chloe",
			name: "Chloe Hart",
			initials: "CH",
			email: "chloe.hart@northwind.example",
			accountId: "northwind",
			title: "Product Manager, Agents",
			relationship: "Client",
			color: "#6a9be8",
			vip: false,
			neverIngest: false,
			strength: 35,
			lastContact: "2026-09-22T16:00:00.000Z",
			channels: {
				email: 4,
				teams: 0,
				meetings: 1,
			},
			topics: [],
			isSample: true,
		},
		{
			id: "p-dan",
			name: "Dan Price",
			initials: "DP",
			email: "dan.price@northwind.example",
			accountId: "northwind",
			title: "Partner Events",
			relationship: "Noise",
			color: "#9aa7b8",
			vip: false,
			neverIngest: false,
			strength: 10,
			lastContact: "2026-09-23T16:00:00.000Z",
			channels: {
				email: 9,
				teams: 0,
				meetings: 0,
			},
			topics: [],
			isSample: true,
		},
		{
			id: "p-erin",
			name: "Erin Lowe",
			initials: "EL",
			email: "erin.lowe@northwind.example",
			accountId: "northwind",
			title: "Partner Sales Director",
			relationship: "Client lead",
			color: "#1f8a5b",
			vip: true,
			neverIngest: false,
			strength: 84,
			lastContact: "2026-09-24T16:00:00.000Z",
			channels: {
				email: 33,
				teams: 0,
				meetings: 3,
			},
			topics: ["t-gsales", "t-trip"],
			isSample: true,
		},
		{
			id: "p-finn",
			name: "Finn Walsh",
			initials: "FW",
			email: "finn.walsh@northwind.example",
			accountId: "northwind",
			title: "Account Executive",
			relationship: "Client",
			color: "#3aa373",
			vip: false,
			neverIngest: false,
			strength: 55,
			lastContact: "2026-09-22T16:00:00.000Z",
			channels: {
				email: 12,
				teams: 0,
				meetings: 2,
			},
			topics: ["t-gsales"],
			isSample: true,
		},
		{
			id: "p-gia",
			name: "Gia Moreno",
			initials: "GM",
			email: "gia.moreno@northwind.example",
			accountId: "northwind",
			title: "Procurement Manager",
			relationship: "Client",
			color: "#58b88b",
			vip: false,
			neverIngest: false,
			strength: 40,
			lastContact: "2026-09-23T16:00:00.000Z",
			channels: {
				email: 6,
				teams: 0,
				meetings: 0,
			},
			topics: [],
			isSample: true,
		},
		{
			id: "p-hugo",
			name: "Hugo Lane",
			initials: "HL",
			email: "hugo.lane@contoso.example",
			accountId: "contoso",
			title: "Senior Manager",
			relationship: "Peer",
			color: "#3d7a57",
			vip: false,
			neverIngest: false,
			strength: 88,
			lastContact: "2026-09-24T16:00:00.000Z",
			channels: {
				email: 52,
				teams: 140,
				meetings: 12,
			},
			topics: ["t-geng", "t-gsales"],
			isSample: true,
		},
		{
			id: "p-ian",
			name: "Ian Foster",
			initials: "IF",
			email: "ian.foster@contoso.example",
			accountId: "contoso",
			title: "Managing Director",
			relationship: "Exec sponsor",
			color: "#7a4fc2",
			vip: true,
			neverIngest: false,
			strength: 81,
			lastContact: "2026-09-24T16:00:00.000Z",
			channels: {
				email: 28,
				teams: 35,
				meetings: 9,
			},
			topics: ["t-elt", "t-board", "t-budget"],
			isSample: true,
		},
		{
			id: "p-jade",
			name: "Jade Nolan",
			initials: "JN",
			email: "jade.nolan@contoso.example",
			accountId: "contoso",
			title: "Principal",
			relationship: "Senior stakeholder",
			color: "#b04a8c",
			vip: true,
			neverIngest: false,
			strength: 74,
			lastContact: "2026-09-23T16:00:00.000Z",
			channels: {
				email: 22,
				teams: 18,
				meetings: 7,
			},
			topics: ["t-elt", "t-board"],
			isSample: true,
		},
		{
			id: "p-kira",
			name: "Kira Stone",
			initials: "KS",
			email: "kira.stone@contoso.example",
			accountId: "contoso",
			title: "Finance Director",
			relationship: "Stakeholder",
			color: "#0f8a8a",
			vip: false,
			neverIngest: false,
			strength: 58,
			lastContact: "2026-09-24T16:00:00.000Z",
			channels: {
				email: 15,
				teams: 4,
				meetings: 3,
			},
			topics: ["t-elt", "t-budget"],
			isSample: true,
		},
		{
			id: "p-leo",
			name: "Leo Grant",
			initials: "LG",
			email: "leo.grant@contoso.example",
			accountId: "contoso",
			title: "Executive Assistant",
			relationship: "Your EA",
			color: "#d17a16",
			vip: false,
			neverIngest: false,
			strength: 79,
			lastContact: "2026-09-24T16:40:00.000Z",
			channels: {
				email: 20,
				teams: 95,
				meetings: 0,
			},
			topics: ["t-trip"],
			isSample: true,
		},
		{
			id: "p-mia",
			name: "Mia Cole",
			initials: "MC",
			email: "mia.cole@contoso.example",
			accountId: "contoso",
			title: "Senior Consultant",
			relationship: "Your team",
			color: "#5a9270",
			vip: false,
			neverIngest: false,
			strength: 69,
			lastContact: "2026-09-24T16:00:00.000Z",
			channels: {
				email: 30,
				teams: 210,
				meetings: 15,
			},
			topics: [],
			isSample: true,
		},
		{
			id: "p-noah",
			name: "Noah Webb",
			initials: "NW",
			email: "noah.webb@fabrikam.example",
			accountId: "fabrikam",
			title: "Alliance Manager",
			relationship: "Client",
			color: "#5f8a1e",
			vip: false,
			neverIngest: false,
			strength: 49,
			lastContact: "2026-09-22T16:00:00.000Z",
			channels: {
				email: 11,
				teams: 0,
				meetings: 2,
			},
			topics: ["t-fabrikam"],
			isSample: true,
		},
		{
			id: "p-traveldesk",
			name: "Travel Desk",
			initials: "TD",
			email: "noreply@travel.example",
			accountId: "other",
			title: "Automated",
			relationship: "Automated",
			color: "#8a9099",
			vip: false,
			neverIngest: false,
			strength: 0,
			lastContact: "2026-09-24T16:00:00.000Z",
			channels: {
				email: 7,
				teams: 0,
				meetings: 0,
			},
			topics: [],
			automated: true,
			isSample: true,
		},
	],
	threads: [
		{
			id: "th-geng-review",
			channel: "email",
			subject: "Agent architecture at our Oct 15 eng review?",
			topicLinks: [
				{
					topicId: "t-geng",
					source: "confirmed",
					confidence: 93,
					primary: true,
				},
				{
					topicId: "t-trip",
					source: "suggested",
					confidence: 48,
					primary: false,
				},
			],
			participants: [
				{
					personId: "p-ava",
					role: "from",
					included: true,
				},
				{
					personId: "me",
					role: "to",
					included: true,
				},
				{
					personId: "p-ben",
					role: "cc",
					included: true,
				},
				{
					personId: "p-hugo",
					role: "cc",
					included: true,
				},
				{
					personId: "p-dan",
					role: "cc",
					included: false,
					excludedBy: "you",
					excludedOn: "2026-09-22T16:00:00.000Z",
					hiddenCount: 2,
				},
			],
			muted: false,
			messageCount: 5,
			lastAt: "2026-09-24T13:02:00.000Z",
			roomId: null,
			summary:
				"Ava offered a 45-min slot at Northwind's Oct 15 eng leadership review for the agent architecture. Hugo can demo the two pilot use cases. Ben wants to see server-side tool permission enforcement. Ava needs an answer by Friday.",
			isSample: true,
		},
		{
			id: "th-sandbox",
			channel: "email",
			subject: "Sandbox access for pilot team",
			topicLinks: [
				{
					topicId: "t-geng",
					source: "confirmed",
					confidence: 96,
					primary: true,
				},
			],
			participants: [
				{
					personId: "me",
					role: "from",
					included: true,
				},
				{
					personId: "p-ben",
					role: "to",
					included: true,
				},
				{
					personId: "p-mia",
					role: "cc",
					included: true,
				},
			],
			muted: false,
			messageCount: 2,
			lastAt: "2026-09-21T20:10:00.000Z",
			roomId: null,
			summary:
				"You asked Ben for sandbox access for Mia and Hugo on Monday. No reply yet.",
			isSample: true,
		},
		{
			id: "th-hugo-chat",
			channel: "teams",
			subject: "Hugo Lane (chat)",
			topicLinks: [
				{
					topicId: "t-geng",
					source: "suggested",
					confidence: 61,
					primary: true,
				},
				{
					topicId: "t-gsales",
					source: "suggested",
					confidence: 55,
					primary: false,
				},
			],
			needsTopicChoice: true,
			participants: [
				{
					personId: "p-hugo",
					role: "member",
					included: true,
				},
				{
					personId: "me",
					role: "member",
					included: true,
				},
			],
			muted: false,
			messageCount: 14,
			lastAt: "2026-09-24T15:40:00.000Z",
			roomId: null,
			summary:
				"Hugo is splitting time between the demo environment for the eng review and pricing inputs Erin asked for.",
			isSample: true,
		},
		{
			id: "th-procurement",
			channel: "email",
			subject: "Procurement questions: pricing and security",
			topicLinks: [
				{
					topicId: "t-gsales",
					source: "confirmed",
					confidence: 90,
					primary: true,
				},
				{
					topicId: "t-budget",
					source: "you",
					confidence: 100,
					primary: false,
				},
			],
			participants: [
				{
					personId: "p-gia",
					role: "from",
					included: true,
				},
				{
					personId: "p-erin",
					role: "to",
					included: true,
				},
				{
					personId: "me",
					role: "to",
					included: true,
				},
				{
					personId: "p-finn",
					role: "cc",
					included: true,
				},
			],
			muted: false,
			messageCount: 3,
			lastAt: "2026-09-23T21:22:00.000Z",
			roomId: null,
			summary:
				"Gia sent 6 pricing questions in Northwind's template and a 40-question security questionnaire. Erin asked you to own the pricing answers.",
			isSample: true,
		},
		{
			id: "th-gtm-invite",
			channel: "calendar",
			subject: "Northwind x Contoso GTM sync",
			topicLinks: [
				{
					topicId: "t-gsales",
					source: "confirmed",
					confidence: 88,
					primary: true,
				},
			],
			participants: [
				{
					personId: "p-erin",
					role: "organizer",
					included: true,
				},
				{
					personId: "p-finn",
					role: "required",
					included: true,
				},
				{
					personId: "p-hugo",
					role: "required",
					included: true,
				},
				{
					personId: "me",
					role: "required",
					included: true,
				},
			],
			muted: false,
			messageCount: 1,
			lastAt: "2026-09-24T11:55:00.000Z",
			roomId: null,
			when: "Tue Sep 29, 2:00 - 2:45 PM ET",
			conflict: "Overlaps 'Mia 1:1' (2:00 - 2:30 PM)",
			summary:
				"Erin invited you to a 45-min GTM sync. It overlaps your 1:1 with Mia.",
			isSample: true,
		},
		{
			id: "th-elt-chat",
			channel: "teams",
			subject: "ELT prep (group chat)",
			topicLinks: [
				{
					topicId: "t-elt",
					source: "confirmed",
					confidence: 95,
					primary: true,
				},
				{
					topicId: "t-budget",
					source: "confirmed",
					confidence: 58,
					primary: false,
				},
				{
					topicId: "t-board",
					source: "suggested",
					confidence: 41,
					primary: false,
				},
			],
			participants: [
				{
					personId: "p-ian",
					role: "member",
					included: true,
				},
				{
					personId: "p-jade",
					role: "member",
					included: true,
				},
				{
					personId: "p-kira",
					role: "member",
					included: true,
				},
				{
					personId: "me",
					role: "member",
					included: true,
				},
			],
			muted: false,
			messageCount: 23,
			lastAt: "2026-09-24T16:15:00.000Z",
			roomId: null,
			summary:
				"Ian wants your build vs buy view on the AI platform before Friday's ELT, including the FY27 impact. Jade will reuse the outcome on the board slide.",
			isSample: true,
		},
		{
			id: "th-board-deck",
			channel: "email",
			subject: "Board deck - AI slide by Monday",
			topicLinks: [
				{
					topicId: "t-board",
					source: "confirmed",
					confidence: 97,
					primary: true,
				},
			],
			participants: [
				{
					personId: "p-jade",
					role: "from",
					included: true,
				},
				{
					personId: "me",
					role: "to",
					included: true,
				},
				{
					personId: "p-ian",
					role: "cc",
					included: true,
				},
			],
			muted: false,
			messageCount: 2,
			lastAt: "2026-09-23T22:40:00.000Z",
			roomId: null,
			summary:
				"Jade needs one AI slide for the Q4 board readout by Monday, using the ELT recommendation.",
			isSample: true,
		},
		{
			id: "th-budget-lines",
			channel: "email",
			subject: "FY27 tooling line items - approval needed",
			topicLinks: [
				{
					topicId: "t-budget",
					source: "confirmed",
					confidence: 94,
					primary: true,
				},
				{
					topicId: "t-elt",
					source: "suggested",
					confidence: 52,
					primary: false,
				},
			],
			participants: [
				{
					personId: "p-kira",
					role: "from",
					included: true,
				},
				{
					personId: "me",
					role: "to",
					included: true,
				},
				{
					personId: "p-ian",
					role: "cc",
					included: true,
				},
			],
			muted: false,
			messageCount: 1,
			lastAt: "2026-09-24T14:05:00.000Z",
			roomId: null,
			summary:
				"Kira needs approval of 4 tooling line items ($412K total) by Wednesday.",
			isSample: true,
		},
		{
			id: "th-leo-chat",
			channel: "teams",
			subject: "Leo Grant (chat)",
			topicLinks: [
				{
					topicId: "t-trip",
					source: "confirmed",
					confidence: 91,
					primary: true,
				},
			],
			participants: [
				{
					personId: "p-leo",
					role: "member",
					included: true,
				},
				{
					personId: "me",
					role: "member",
					included: true,
				},
			],
			muted: false,
			messageCount: 9,
			lastAt: "2026-09-24T16:40:00.000Z",
			roomId: null,
			summary:
				"Leo offered to hold 5-6 PM Oct 14 for the Northwind sales happy hour and asked about flights.",
			isSample: true,
		},
		{
			id: "th-traveldesk",
			channel: "email",
			subject: "Trip to San Francisco: itinerary pending approval",
			topicLinks: [
				{
					topicId: "t-trip",
					source: "confirmed",
					confidence: 89,
					primary: true,
				},
			],
			participants: [
				{
					personId: "p-traveldesk",
					role: "from",
					included: true,
				},
				{
					personId: "me",
					role: "to",
					included: true,
				},
			],
			muted: false,
			messageCount: 1,
			lastAt: "2026-09-24T12:30:00.000Z",
			roomId: null,
			automated: true,
			summary:
				"Travel Desk itinerary created; approval needed before tickets are issued.",
			isSample: true,
		},
		{
			id: "th-fabrikam",
			channel: "email",
			subject: "Follow-up: Q1 GPU capacity reservation",
			topicLinks: [
				{
					topicId: "t-fabrikam",
					source: "confirmed",
					confidence: 95,
					primary: true,
				},
			],
			participants: [
				{
					personId: "p-noah",
					role: "from",
					included: true,
				},
				{
					personId: "me",
					role: "to",
					included: true,
				},
			],
			muted: false,
			messageCount: 2,
			lastAt: "2026-09-22T19:15:00.000Z",
			roomId: null,
			summary: "Noah needs a yes/no on holding 64 GPUs for Q1 by Oct 1.",
			isSample: true,
		},
		{
			id: "th-security-q",
			channel: "email",
			subject: "Security questionnaire - vendor onboarding",
			topicLinks: [
				{
					topicId: "t-gsales",
					source: "suggested",
					confidence: 44,
					primary: true,
				},
			],
			needsTopicChoice: true,
			participants: [
				{
					personId: "p-gia",
					role: "from",
					included: true,
				},
				{
					personId: "me",
					role: "to",
					included: true,
				},
			],
			muted: false,
			messageCount: 1,
			lastAt: "2026-09-23T21:30:00.000Z",
			roomId: null,
			summary:
				"Separate security questionnaire thread; Brain suggests a new topic 'Northwind - Security review'.",
			isSample: true,
		},
		{
			id: "th-newsletter",
			channel: "email",
			subject: "Partner Summit recap: 12 launches you missed",
			topicLinks: [],
			participants: [
				{
					personId: "p-dan",
					role: "from",
					included: false,
					excludedBy: "rule",
					excludedOn: "2026-09-01T12:00:00.000Z",
				},
			],
			muted: true,
			messageCount: 1,
			lastAt: "2026-09-24T10:00:00.000Z",
			roomId: null,
			automated: true,
			summary: "Marketing newsletter. Skipped.",
			isSample: true,
		},
	],
	items: [
		{
			id: "i1",
			threadId: "th-geng-review",
			channel: "email",
			actorId: "p-ava",
			title: "Confirm Oct 15 architecture review slot with Ava",
			askType: "reply",
			priority: "P0",
			score: 91,
			reasons: [
				"Direct ask to you",
				"VIP client",
				"Due Fri",
				"Unanswered 28h",
			],
			due: "2026-09-25T16:00:00.000Z",
			received: "2026-09-22T13:14:00.000Z",
			status: "open",
			topicIds: ["t-geng", "t-trip"],
			isSample: true,
		},
		{
			id: "i2",
			threadId: "th-elt-chat",
			channel: "teams",
			actorId: "p-ian",
			title: "Give Ian your build vs buy view on the AI platform",
			askType: "reply",
			priority: "P1",
			score: 84,
			reasons: [
				"Exec asked you directly",
				"Due today",
				"ELT tomorrow 8:30 AM",
			],
			due: "2026-09-24T21:00:00.000Z",
			received: "2026-09-24T16:15:00.000Z",
			status: "open",
			topicIds: ["t-elt", "t-budget"],
			isSample: true,
		},
		{
			id: "i3",
			threadId: "th-procurement",
			channel: "email",
			actorId: "p-gia",
			title: "Answer Northwind procurement pricing questions",
			askType: "review",
			priority: "P1",
			score: 78,
			reasons: ["Erin assigned you", "Client", "6 open questions"],
			due: "2026-09-28T16:00:00.000Z",
			received: "2026-09-23T21:22:00.000Z",
			status: "open",
			topicIds: ["t-gsales", "t-budget"],
			isSample: true,
		},
		{
			id: "i4",
			threadId: "th-gtm-invite",
			channel: "calendar",
			actorId: "p-erin",
			title: "Respond: Northwind x Contoso GTM sync (Tue 2 PM)",
			askType: "attend",
			priority: "P1",
			score: 72,
			reasons: [
				"Invite not answered",
				"Conflict with Mia 1:1",
				"VIP organizer",
			],
			due: "2026-09-29T16:00:00.000Z",
			received: "2026-09-24T11:55:00.000Z",
			status: "open",
			topicIds: ["t-gsales"],
			isSample: true,
		},
		{
			id: "i5",
			threadId: "th-board-deck",
			channel: "email",
			actorId: "p-jade",
			title: "Send AI slide for the Q4 board deck",
			askType: "review",
			priority: "P1",
			score: 70,
			reasons: ["VIP", "Due Mon", "Depends on ELT outcome"],
			due: "2026-09-28T16:00:00.000Z",
			received: "2026-09-23T22:40:00.000Z",
			status: "open",
			topicIds: ["t-board"],
			isSample: true,
		},
		{
			id: "i6",
			threadId: "th-leo-chat",
			channel: "teams",
			actorId: "p-leo",
			title: "Tell Leo whether to hold Oct 14 happy hour",
			askType: "reply",
			priority: "P2",
			score: 61,
			reasons: ["Direct question", "Trip in 20 days"],
			due: "2026-09-25T16:00:00.000Z",
			received: "2026-09-24T16:40:00.000Z",
			status: "open",
			topicIds: ["t-trip", "t-gsales"],
			isSample: true,
		},
		{
			id: "i7",
			threadId: "th-leo-chat",
			channel: "task",
			actorId: "assistant",
			title: "Book flights to SFO (arrive Oct 13 evening)",
			askType: "errand",
			priority: "P2",
			score: 58,
			reasons: [
				"Suggested by assistant",
				"Fares rising",
				"Travel Desk approval pending",
			],
			due: "2026-09-30T16:00:00.000Z",
			received: "2026-09-24T16:00:00.000Z",
			status: "open",
			topicIds: ["t-trip"],
			suggested: true,
			isSample: true,
		},
		{
			id: "i8",
			threadId: "th-leo-chat",
			channel: "task",
			actorId: "assistant",
			title: "Dinner for 6 near Northwind Seattle, Oct 14",
			askType: "errand",
			priority: "P2",
			score: 55,
			reasons: ["Suggested by assistant", "Goal on Northwind onsite"],
			due: "2026-10-07T16:00:00.000Z",
			received: "2026-09-24T16:00:00.000Z",
			status: "open",
			topicIds: ["t-trip", "t-gsales"],
			suggested: true,
			isSample: true,
		},
		{
			id: "i9",
			threadId: "th-budget-lines",
			channel: "email",
			actorId: "p-kira",
			title: "Approve FY27 tooling line items ($412K)",
			askType: "approve",
			priority: "P2",
			score: 57,
			reasons: ["Approval requested", "Due Wed"],
			due: "2026-09-30T16:00:00.000Z",
			received: "2026-09-24T14:05:00.000Z",
			status: "open",
			topicIds: ["t-budget"],
			isSample: true,
		},
		{
			id: "i10",
			threadId: "th-traveldesk",
			channel: "email",
			actorId: "p-traveldesk",
			title: "Approve Travel Desk itinerary (SFO, Oct 13-15)",
			askType: "approve",
			priority: "P2",
			score: 50,
			reasons: ["Automated but needs action", "Blocks ticketing"],
			due: "2026-09-25T16:00:00.000Z",
			received: "2026-09-24T12:30:00.000Z",
			status: "open",
			topicIds: ["t-trip"],
			isSample: true,
		},
		{
			id: "i11",
			threadId: "th-fabrikam",
			channel: "email",
			actorId: "p-noah",
			title: "Yes/no on holding 64 GPUs for Q1",
			askType: "reply",
			priority: "P2",
			score: 48,
			reasons: ["Direct ask", "Due Oct 1"],
			due: "2026-10-01T16:00:00.000Z",
			received: "2026-09-22T19:15:00.000Z",
			status: "open",
			topicIds: ["t-fabrikam"],
			isSample: true,
		},
		{
			id: "i12",
			threadId: "th-sandbox",
			channel: "email",
			actorId: "p-ben",
			title: "Waiting on Ben: sandbox access",
			askType: "waiting_on",
			priority: "P3",
			score: 35,
			reasons: ["You asked 3 days ago", "Blocks demo prep"],
			due: null,
			received: "2026-09-21T20:10:00.000Z",
			status: "waiting",
			topicIds: ["t-geng"],
			isSample: true,
		},
	],
	reviews: [
		{
			id: "r1",
			kind: "new_topic",
			text: "New topic suggested: Northwind - Security review",
			detail: "6 threads, 3 new northwind.example people",
			refId: "st-gsec",
			actions: ["Accept", "Merge into Northwind - Sales / GTM", "Ignore"],
			status: "open",
			candidate: {
				name: "Northwind - Security review",
				accountId: "northwind",
				mergeCandidate: "t-gsales",
			},
		},
		{
			id: "r2",
			kind: "topic_choice",
			text: "Hugo Lane's Teams chat fits two topics",
			detail: "Northwind Eng 61% / Northwind Sales 55%",
			refId: "th-hugo-chat",
			actions: ["Both", "Northwind Eng", "Northwind Sales"],
			status: "open",
		},
		{
			id: "r3",
			kind: "add_person",
			text: "Add Gia Moreno to Northwind - Sales / GTM?",
			detail: "New on 3 Sales threads this week",
			refId: "p-gia",
			actions: ["Add", "Not now"],
			status: "open",
			topicId: "t-gsales",
		},
		{
			id: "r5",
			kind: "unassigned",
			text: "One loaded thread has no topic",
			detail: "Review the newsletter and decide whether to file it.",
			refId: null,
			actions: ["Review"],
			status: "open",
		},
	],
	accounts: [
		{
			id: "northwind",
			name: "Northwind",
			domain: "northwind.example",
			kind: "client",
			color: "#2d6fd0",
		},
		{
			id: "fabrikam",
			name: "Fabrikam",
			domain: "fabrikam.example",
			kind: "client",
			color: "#5f8a1e",
		},
		{
			id: "contoso",
			name: "Contoso (internal)",
			domain: "contoso.example",
			kind: "internal",
			color: "#3d7a57",
		},
		{
			id: "other",
			name: "Other / vendors",
			domain: "",
			kind: "other",
			color: "#8a9099",
		},
	],
	profile: {
		id: "me",
		name: "Robin Hale",
		initials: "RH",
		email: "robin.hale@contoso.example",
		org: "Contoso",
		role: {
			value: "AI engineering lead",
			source: "learned",
			note: "From email signature - confirm",
		},
		timezone: "America/New_York",
		workingHours: "8:00 - 18:30 ET",
		vips: ["p-ava", "p-ian", "p-jade", "p-erin"],
		style: {
			summary:
				"Short and direct. Warm one-line opener, bullets for asks, signs off '- Robin'.",
			source: "learned",
			confirmed: true,
			examples: [
				"Thanks Ava - quick answers below.",
				"Can you confirm by Fri?",
			],
		},
	},
	liveProfile: null,
	settings: {
		classifierEngineId: "",
		fileAt: 85,
		askAt: 40,
		sourcesJson: {
			email: false,
			calendar: false,
			teams: false,
		},
		memory: { use: true, learn: true },
		version: 1,
	},
	rules: [
		{
			id: "sample-rule-1",
			kind: "never_folder",
			value: "Personal",
			createdBy: "you",
			createdAt: "2026-08-01T00:00:00.000Z",
			isSample: true,
		},
		{
			id: "sample-rule-2",
			kind: "never_sender",
			value: "benefits@contoso.example",
			note: "HR / benefits",
			createdBy: "you",
			createdAt: "2026-08-01T00:00:00.000Z",
			isSample: true,
		},
		{
			id: "sample-rule-3",
			kind: "never_keyword",
			value: "performance review",
			createdBy: "you",
			createdAt: "2026-08-01T00:00:00.000Z",
			isSample: true,
		},
	],
	sources: [
		{
			id: "email",
			label: "Outlook mail",
			mark: "E",
			status: "connected",
			lastSync: "2026-09-24T16:00:00.000Z",
			scope: "Inbox + Sent Items, last 90 days",
			volume: "4,212 messages",
			permission: "Mail.Read (delegated)",
			isSample: true,
		},
		{
			id: "calendar",
			label: "Outlook calendar",
			mark: "C",
			status: "connected",
			lastSync: "2026-09-24T16:00:00.000Z",
			scope: "Primary calendar, -30 / +60 days",
			volume: "318 events",
			permission: "Calendars.Read (delegated)",
			isSample: true,
		},
		{
			id: "teams",
			label: "Teams chats",
			mark: "T",
			status: "needs_permission",
			lastSync: null,
			scope: "1:1 and group chats",
			volume: null,
			permission: "Chat.Read (delegated) - pending approval",
			isSample: true,
		},
		{
			id: "teamsChannels",
			label: "Teams channels",
			mark: "T",
			status: "off",
			lastSync: null,
			scope: "Not in pilot scope",
			volume: null,
			permission: "ChannelMessage.Read.All - not requested",
			isSample: true,
		},
		{
			id: "files",
			label: "OneDrive / SharePoint",
			mark: "F",
			status: "off",
			lastSync: null,
			scope: "Attachments only for now",
			volume: null,
			permission: "Sites.Selected - later",
			isSample: true,
		},
	],
	workspaces: {
		"th-geng-review": {
			goal: "Lock the Oct 15 review: 45-min slot, attendee list, pre-read to Ava by Oct 13.",
			messages: [
				{
					id: "m1",
					fromId: "p-ava",
					at: "2026-09-22T13:14:00.000Z",
					text: "Hi Robin - our eng leadership review on Oct 15 has a slot open. Could your team walk us through the agent architecture? 45 min, about 12 attendees. Let me know by Friday if that works.",
				},
				{
					id: "m2",
					fromId: "p-dan",
					at: "2026-09-22T14:02:00.000Z",
					text: "Reminder: registration for the Northwind Cloud Partner Summit closes Friday!",
					excluded: true,
				},
				{
					id: "m3",
					fromId: "p-hugo",
					at: "2026-09-22T15:30:00.000Z",
					text: "I can drive the live demo if we keep it to the two pilot use cases.",
				},
				{
					id: "m4",
					fromId: "p-ben",
					at: "2026-09-23T20:45:00.000Z",
					text: "We'd want to see how tool permissions are enforced server-side, not just in the UI.",
				},
				{
					id: "m5",
					fromId: "p-dan",
					at: "2026-09-23T21:00:00.000Z",
					text: "Last call for Partner Summit sessions - reply to reserve a seat.",
					excluded: true,
				},
			],
			steps: [
				{
					id: "a1",
					text: "Reply to Ava confirming Oct 15",
					ownerId: "me",
					due: "2026-09-25T16:00:00.000Z",
					status: "draft_ready",
					kind: "reply",
					itemId: "i1",
				},
				{
					id: "a2",
					text: "Send pre-read to Ava's team",
					ownerId: "me",
					due: "2026-10-13T16:00:00.000Z",
					status: "open",
					kind: "task",
				},
				{
					id: "a3",
					text: "Ask Hugo to confirm demo env covers both use cases",
					ownerId: "p-hugo",
					due: null,
					status: "suggested",
					kind: "task",
				},
				{
					id: "a4",
					text: "Sandbox access for pilot team",
					ownerId: "p-ben",
					due: null,
					status: "waiting",
					kind: "waiting_on",
					itemId: "i12",
				},
				{
					id: "a5",
					text: "Book flights to SFO (arrive Oct 13)",
					ownerId: "me",
					due: "2026-09-30T16:00:00.000Z",
					status: "open",
					kind: "errand",
					linkTopicId: "t-trip",
					itemId: "i7",
				},
				{
					id: "a6",
					text: "Share mutual NDA with Northwind legal",
					ownerId: "me",
					due: null,
					status: "done",
					kind: "task",
				},
			],
			assets: [
				{
					name: "Agent architecture v3.pptx",
					kind: "pptx",
					size: "4.2 MB",
					source: "dropped",
					by: "you",
					when: "2026-09-23T16:00:00.000Z",
					id: "th-geng-review-asset-1",
					isSample: true,
				},
				{
					name: "Pilot use cases.docx",
					kind: "docx",
					size: "220 KB",
					source: "attachment",
					by: "Hugo Lane",
					when: "2026-09-20T16:00:00.000Z",
					id: "th-geng-review-asset-2",
					isSample: true,
				},
				{
					name: "Reply to Ava (draft)",
					kind: "draft",
					size: "",
					source: "generated",
					by: "assistant",
					when: "2026-09-24T16:00:00.000Z",
					id: "th-geng-review-asset-3",
					isSample: true,
				},
			],
			drafts: [
				{
					to: "Ava Reed",
					cc: "Ben Carter, Hugo Lane",
					subject: "Re: Agent architecture at our Oct 15 eng review?",
					body: "Hi Ava,\n\nThanks for the slot - Oct 15 works, and 45 minutes is right.\n\n- Hugo will run a live demo of the two pilot use cases.\n- We will send a pre-read by Oct 13.\n- Ben: we will walk through how tool permissions are enforced server-side.\n\nCould you share the attendee list so we can tailor the depth?\n\n- Robin",
					id: "th-geng-review-draft-2",
					isSample: true,
				},
			],
			suggestions: [
				"Outline the pre-read",
				"Hold Oct 15 10:00 PT on my calendar",
				"Ask Hugo to confirm the demo environment",
			],
			sampleChat: [
				{
					id: "th-geng-review-chat-1",
					role: "user",
					text: "Draft a reply to Ava: yes for Oct 15, 45 min works, Hugo demos, pre-read by Oct 13. Ask for the attendee list.",
				},
				{
					id: "th-geng-review-chat-2",
					role: "assistant",
					text: "Draft ready. I kept your usual tone with Ava (warm, brief). I left out Dan Price's two messages because you excluded him from this thread. Ben asked about server-side tool permissions, so I added one line saying we will cover it.",
					citations: [
						"Ava, Tue 9:14 AM",
						"Hugo, Tue 11:30 AM",
						"Ben, Wed 4:45 PM",
						"Topic note: pre-read 48h",
					],
				},
			],
			related: [
				{
					threadId: "th-sandbox",
					why: "Same topic, blocks demo prep",
				},
				{
					threadId: "th-gtm-invite",
					why: "Same account (Northwind)",
				},
				{
					threadId: "th-leo-chat",
					why: "Onsite logistics for Oct 14-15",
				},
			],
			meetings: [
				{
					title: "Northwind eng leadership review",
					when: "Thu Oct 15, 10:00 - 10:45 AM PT",
					state: "Tentative hold",
				},
			],
		},
		"th-elt-chat": {
			goal: "Give Ian a one-page build vs buy recommendation, numbers first, before Friday's ELT.",
			messages: [
				{
					id: "o1",
					fromId: "p-ian",
					at: "2026-09-24T15:50:00.000Z",
					text: "Robin, need your view on the platform ask before Fri. Build vs buy, and what it does to FY27.",
				},
				{
					id: "o2",
					fromId: "p-kira",
					at: "2026-09-24T16:02:00.000Z",
					text: "Tooling lines are in my email from this morning - $412K as proposed.",
				},
				{
					id: "o3",
					fromId: "p-jade",
					at: "2026-09-24T16:15:00.000Z",
					text: "Whatever we land here goes on the board slide, so keep it crisp.",
				},
			],
			steps: [
				{
					id: "b1",
					text: "Reply to Ian with recommendation",
					ownerId: "me",
					due: "2026-09-24T21:00:00.000Z",
					status: "open",
					kind: "reply",
					itemId: "i2",
				},
				{
					id: "b2",
					text: "Confirm 3-year cost assumption with Kira",
					ownerId: "p-kira",
					due: null,
					status: "suggested",
					kind: "task",
				},
				{
					id: "b3",
					text: "Reuse for board AI slide",
					ownerId: "me",
					due: "2026-09-21T16:00:00.000Z",
					status: "open",
					kind: "task",
					linkTopicId: "t-board",
					itemId: "i5",
				},
			],
			assets: [
				{
					name: "Platform options v2.xlsx",
					kind: "xlsx",
					size: "88 KB",
					source: "attachment",
					by: "Kira Stone",
					when: "2026-09-24T16:00:00.000Z",
					id: "th-elt-chat-asset-1",
					isSample: true,
				},
			],
			drafts: [],
			suggestions: [
				"Turn this into a reply to Ian",
				"Draft the board slide from this",
				"What did Ian push back on last time?",
			],
			sampleChat: [
				{
					id: "th-elt-chat-chat-1",
					role: "user",
					text: "Summarize build vs buy tradeoffs from the last 3 ELT threads and Kira's budget email. One page, numbers first.",
				},
				{
					id: "th-elt-chat-chat-2",
					role: "assistant",
					text: "Here is a one-page outline. Buy is faster (8 weeks) but 1.6x the 3-year cost; build reuses the platform team and fits inside the $412K tooling line if we defer one hire. I flagged one number I could not source.",
					citations: [
						"ELT prep chat",
						"Kira, today 10:05 AM",
						"ELT notes Sep 10",
					],
				},
			],
			related: [
				{
					threadId: "th-budget-lines",
					why: "FY27 numbers",
				},
				{
					threadId: "th-board-deck",
					why: "Reuses this outcome",
				},
			],
			meetings: [
				{
					title: "ELT",
					when: "Fri Sep 25, 8:30 - 9:30 AM ET",
					state: "Accepted",
				},
			],
		},
		"th-leo-chat": {
			goal: "Arrive Seattle Oct 13 evening; host the Northwind sales happy hour Oct 14 5-6 PM; dinner for 6 at 7:30 PM.",
			messages: [
				{
					id: "j1",
					fromId: "p-leo",
					at: "2026-09-24T16:40:00.000Z",
					text: "Want me to hold 5-6 PM on Oct 14 for a happy hour with Erin's team? Also - do you want the 5:10 PM or 7:45 PM flight on the 13th?",
				},
			],
			steps: [
				{
					id: "c1",
					text: "Reply to Leo about the happy hour hold",
					ownerId: "me",
					due: "2026-09-25T16:00:00.000Z",
					status: "open",
					kind: "reply",
					itemId: "i6",
				},
				{
					id: "c2",
					text: "Pick flight (5:10 PM vs 7:45 PM, Oct 13)",
					ownerId: "me",
					due: "2026-09-30T16:00:00.000Z",
					status: "open",
					kind: "errand",
					itemId: "i7",
				},
				{
					id: "c3",
					text: "Dinner for 6, Oct 14 7:30 PM",
					ownerId: "p-leo",
					due: "2026-10-07T16:00:00.000Z",
					status: "suggested",
					kind: "errand",
					itemId: "i8",
				},
				{
					id: "c4",
					text: "Approve Travel Desk itinerary",
					ownerId: "me",
					due: "2026-09-25T16:00:00.000Z",
					status: "open",
					kind: "approve",
					itemId: "i10",
				},
			],
			assets: [
				{
					name: "Travel Desk itinerary SFO Oct 13-15.pdf",
					kind: "pdf",
					size: "130 KB",
					source: "attachment",
					by: "Travel Desk",
					when: "2026-09-24T16:00:00.000Z",
					id: "th-leo-chat-asset-1",
					isSample: true,
				},
			],
			drafts: [],
			suggestions: [
				"Draft a note to Leo: hold happy hour + Option A",
				"Compare the two flights",
				"Approve the Travel Desk itinerary",
			],
			sampleChat: [
				{
					id: "th-leo-chat-chat-1",
					role: "user",
					text: "Find dinner options for 6 near Northwind Seattle on Oct 14 at 7:30 PM. Private-ish, client appropriate, one vegetarian.",
				},
				{
					id: "th-leo-chat-chat-2",
					role: "assistant",
					text: "Three options below. I cannot book: there is no reservation connector. I can draft a note to Leo with your pick, or open the booking page.",
					options: [
						{
							name: "Option A - Californian, private room for 8",
							meta: "0.9 mi, $$$, vegetarian tasting menu",
						},
						{
							name: "Option B - Italian, semi-private booth",
							meta: "1.4 mi, $$, strong vegetarian options",
						},
						{
							name: "Option C - Japanese, chef counter for 6",
							meta: "2.1 mi, $$$$, over the entertainment limit",
						},
					],
				},
			],
			related: [
				{
					threadId: "th-traveldesk",
					why: "Itinerary approval",
				},
				{
					threadId: "th-geng-review",
					why: "Reason for the trip",
				},
			],
			meetings: [
				{
					title: "Hold: Northwind sales happy hour",
					when: "Wed Oct 14, 5:00 - 6:00 PM PT",
					state: "Proposed by Leo",
				},
			],
		},
	},
	memories: [
		{
			id: "m-sample-pref-1",
			kind: "preference",
			text: "Keep emails to Northwind short and lead with the decision.",
			state: "active",
			origin: "you",
			confirmed: true,
			about: [],
			source: {
				kind: "ui",
			},
			createdAt: "2026-09-15T16:00:00.000Z",
			updatedAt: "2026-09-15T16:00:00.000Z",
			pinned: false,
			expiresAt: null,
			replacesId: null,
			isSample: true,
		},
		{
			id: "t-geng-note-1",
			kind: "fact",
			text: "Ava prefers a written pre-read 48h before any review.",
			state: "active",
			origin: "you",
			confirmed: true,
			about: [
				{
					type: "topic",
					id: "t-geng",
				},
			],
			source: {
				kind: "topic_note",
			},
			createdAt: "2026-09-18T16:00:00.000Z",
			updatedAt: "2026-09-18T16:00:00.000Z",
			pinned: false,
			expiresAt: null,
			replacesId: null,
			isSample: true,
		},
		{
			id: "t-geng-note-2",
			kind: "fact",
			text: "Pilot scope is limited to 2 use cases (claims triage, contract Q&A).",
			state: "suggested",
			origin: "brain",
			confirmed: false,
			about: [
				{
					type: "topic",
					id: "t-geng",
				},
			],
			source: {
				kind: "topic_note",
				label: "Email from Hugo Lane, Sep 20",
			},
			createdAt: "2026-09-20T16:00:00.000Z",
			updatedAt: "2026-09-20T16:00:00.000Z",
			pinned: false,
			expiresAt: null,
			replacesId: null,
			isSample: true,
		},
		{
			id: "t-gsales-note-1",
			kind: "fact",
			text: "Gia Moreno (procurement) needs pricing in their template, not ours.",
			state: "suggested",
			origin: "brain",
			confirmed: false,
			about: [
				{
					type: "topic",
					id: "t-gsales",
				},
			],
			source: {
				kind: "topic_note",
				label: "Email from Gia Moreno, Sep 23",
			},
			createdAt: "2026-09-23T16:00:00.000Z",
			updatedAt: "2026-09-23T16:00:00.000Z",
			pinned: false,
			expiresAt: null,
			replacesId: null,
			isSample: true,
		},
		{
			id: "t-trip-note-1",
			kind: "fact",
			text: "Keep dinner under the client-entertainment limit; one guest is vegetarian.",
			state: "active",
			origin: "you",
			confirmed: true,
			about: [
				{
					type: "topic",
					id: "t-trip",
				},
			],
			source: {
				kind: "topic_note",
			},
			createdAt: "2026-09-23T16:00:00.000Z",
			updatedAt: "2026-09-23T16:00:00.000Z",
			pinned: false,
			expiresAt: null,
			replacesId: null,
			isSample: true,
		},
		{
			id: "t-elt-note-1",
			kind: "fact",
			text: "Ian wants one page, numbers first.",
			state: "active",
			origin: "you",
			confirmed: true,
			about: [
				{
					type: "topic",
					id: "t-elt",
				},
			],
			source: {
				kind: "topic_note",
			},
			createdAt: "2026-09-10T16:00:00.000Z",
			updatedAt: "2026-09-10T16:00:00.000Z",
			pinned: false,
			expiresAt: null,
			replacesId: null,
			isSample: true,
		},
		{
			id: "th-geng-review-fact-2",
			kind: "fact",
			text: "Pilot scope is limited to 2 use cases.",
			state: "suggested",
			origin: "brain",
			confirmed: false,
			about: [
				{
					type: "thread",
					id: "th-geng-review",
				},
			],
			source: {
				kind: "thread_fact",
				threadId: "th-geng-review",
				label: "Email from Hugo, Sep 20",
				personId: "p-hugo",
			},
			createdAt: "2026-09-24T16:00:00.000Z",
			updatedAt: "2026-09-24T16:00:00.000Z",
			pinned: false,
			expiresAt: null,
			replacesId: null,
			isSample: true,
		},
		{
			id: "th-geng-review-fact-3",
			kind: "fact",
			text: "You are onsite in Seattle Oct 14-15.",
			state: "active",
			origin: "you",
			confirmed: true,
			about: [
				{
					type: "thread",
					id: "th-geng-review",
				},
			],
			source: {
				kind: "thread_fact",
				threadId: "th-geng-review",
				label: "Topic - Northwind onsite",
			},
			createdAt: "2026-09-24T16:00:00.000Z",
			updatedAt: "2026-09-24T16:00:00.000Z",
			pinned: false,
			expiresAt: null,
			replacesId: null,
			isSample: true,
		},
		{
			id: "th-geng-review-fact-4",
			kind: "fact",
			text: "Hugo owns the demo environment.",
			state: "active",
			origin: "you",
			confirmed: true,
			about: [
				{
					type: "thread",
					id: "th-geng-review",
				},
			],
			source: {
				kind: "thread_fact",
				threadId: "th-geng-review",
				label: "Brain - people",
			},
			createdAt: "2026-09-24T16:00:00.000Z",
			updatedAt: "2026-09-24T16:00:00.000Z",
			pinned: false,
			expiresAt: null,
			replacesId: null,
			isSample: true,
		},
		{
			id: "th-elt-chat-fact-2",
			kind: "fact",
			text: "Tooling line items total $412K for FY27.",
			state: "active",
			origin: "you",
			confirmed: true,
			about: [
				{
					type: "thread",
					id: "th-elt-chat",
				},
			],
			source: {
				kind: "thread_fact",
				threadId: "th-elt-chat",
				label: "Email from Kira, today",
				personId: "p-kira",
			},
			createdAt: "2026-09-24T16:00:00.000Z",
			updatedAt: "2026-09-24T16:00:00.000Z",
			pinned: false,
			expiresAt: null,
			replacesId: null,
			isSample: true,
		},
		{
			id: "th-elt-chat-fact-3",
			kind: "fact",
			text: "Jade will reuse the recommendation on the board slide.",
			state: "suggested",
			origin: "brain",
			confirmed: false,
			about: [
				{
					type: "thread",
					id: "th-elt-chat",
				},
			],
			source: {
				kind: "thread_fact",
				threadId: "th-elt-chat",
				label: "ELT prep chat",
			},
			createdAt: "2026-09-24T16:00:00.000Z",
			updatedAt: "2026-09-24T16:00:00.000Z",
			pinned: false,
			expiresAt: null,
			replacesId: null,
			isSample: true,
		},
		{
			id: "th-leo-chat-fact-2",
			kind: "fact",
			text: "Travel Desk itinerary is waiting for your approval.",
			state: "active",
			origin: "you",
			confirmed: true,
			about: [
				{
					type: "thread",
					id: "th-leo-chat",
				},
			],
			source: {
				kind: "thread_fact",
				threadId: "th-leo-chat",
				label: "Travel Desk email, today",
			},
			createdAt: "2026-09-24T16:00:00.000Z",
			updatedAt: "2026-09-24T16:00:00.000Z",
			pinned: false,
			expiresAt: null,
			replacesId: null,
			isSample: true,
		},
	],
	openThreadIds: ["th-geng-review", "th-elt-chat", "th-leo-chat"],
	sequence: 1,
};

/** Return a fresh session; no sample room ID is sent to the backend. */
export function createInitialCollaborationState(): CollaborationState {
	return structuredClone(SAMPLE_STATE);
}
