import { action, computed, makeObservable, observable } from "mobx";
import type { RoomStore } from "@/stores";
import type { AbstractPixelMessage, PixelMessage } from "@/types";

/**
 * Abstract Message Store
 */
export abstract class AbstractMessageStore {
	/**
	 * Id of the message
	 */
	id: string = "";

	/**
	 * Unique react key for the message. Only should be used to render.
	 */
	readonly key: string;

	/**
	 * Is the message visible to the user
	 */
	visible: boolean = false;

	/**
	 * Store the room
	 */
	room: RoomStore = null;

	/**
	 * Track if it is an root, input, or response message
	 */
	abstract type: "ROOT" | "PLAN" | "INPUT" | "OUTPUT";

	/**
	 * Parent of the message
	 */
	parent: AbstractMessageStore = null;

	/**
	 * Current position of message
	 */
	position: number = -1;

	/**
	 * Children messages
	 */
	children: AbstractMessageStore[] = [];

	/**
	 * Active Child Position
	 */
	activeChildPosition: number = -1;

	/**
	 * Track if it is an root, input, or response message
	 */
	abstract parts: AbstractPixelMessage["parts"];

	/**
	 * Tokens used in the message, used for cost calculation
	 */
	tokens: number = 0;

	/**
	 * Model Id used for the message
	 */
	modelId: string;

	/**
	 * Model Type used for the message
	 */
	modelType: string;

	/**
	 * Ornaments for the message, used for extra properties that are not essential
	 */
	ornaments: {
		modelName?: string;
		compactionSummaryIds?: string;
	};

	/**
	 * Date the message was created
	 */
	dateCreated: Date;

	/**
	 * Whether this message was generated by the platform (not the user or LLM).
	 * Used to hide compaction anchor messages from branch navigation.
	 */
	platform_generated: boolean = false;

	/**
	 * Whether this message is a compaction anchor node (anchorInput or anchorResponse).
	 * Used by preCompactionHistory to exclude anchor nodes from the above-divider list.
	 * Not used as a render filter — visible is the authoritative render gate.
	 */
	isCompactionAnchor: boolean = false;

	/**
	 *
	 * @param room
	 * @param message
	 */
	constructor(room: RoomStore, message: AbstractPixelMessage) {
		this.room = room;

		// set the key
		this.key = `room-${room.roomId}-${Date.now()}-${Math.floor(Math.random() * 100000000)}`;

		this.id = message.messageId;
		this.visible = message.visible;
		this.platform_generated = message.platform_generated ?? false;
		this.isCompactionAnchor = message.isCompactionAnchor ?? false;
		this.tokens = message.tokens;
		this.modelId = message.modelId;
		this.modelType = message.modelType;
		this.ornaments = {
			modelName: message.ornaments?.modelName,
			compactionSummaryIds: message.ornaments?.compactionSummaryIds,
		};

		makeObservable(this, {
			room: observable,
			id: observable,
			parent: observable,
			position: observable,
			children: observable,
			activeChildPosition: observable,
			tokens: observable,
			modelId: observable,
			modelType: observable,
			ornaments: observable,
			isCompactionAnchor: observable,
			siblings: computed,
			previousSibling: computed,
			nextSibling: computed,
			activeChild: computed,
			connectParent: action,
			addChild: action,
			removeChild: action,
			activateMessage: action,
			sync: action,
		});
	}

	/**
	 * Getters
	 */

	/**
	 * Check if there are siblings.
	 * Platform-generated messages (e.g. compaction anchors) are excluded so
	 * they never appear as navigable branches in the UI.
	 */
	get siblings() {
		return this.parent.children.filter((c) => !c.platform_generated);
	}

	/**
	 * Get the previous sibling, skipping platform-generated messages.
	 */
	get previousSibling() {
		const siblings = this.siblings;
		const idx = siblings.indexOf(this);
		if (idx <= 0) return null;
		return siblings[idx - 1];
	}

	/**
	 * Get the next sibling, skipping platform-generated messages.
	 */
	get nextSibling() {
		const siblings = this.siblings;
		const idx = siblings.indexOf(this);
		if (idx === -1 || idx >= siblings.length - 1) return null;
		return siblings[idx + 1];
	}

	/**
	 * Get the active child
	 */
	get activeChild() {
		return this.children[this.activeChildPosition] || null;
	}

	/** Actions */
	/**
	 * Sync store properties from the pixel message
	 */
	sync(message: PixelMessage) {
		this.dateCreated = (() => {
			const raw = message.dateCreated;
			const normalized = /Z|[+-]\d{2}:?\d{2}$/.test(raw)
				? raw
				: `${raw.replace(" ", "T")}Z`;
			return new Date(normalized);
		})();
	}

	/**
	 * Connect the parent and store the position
	 */
	connectParent = (parentMessage: AbstractMessageStore, position: number) => {
		// store the parent and position
		this.parent = parentMessage;
		this.position = position;
	};

	/**
	 * Add a child message
	 */
	addChild = (message: AbstractMessageStore) => {
		// store it
		this.children.push(message);

		// last idx is the position
		const position = this.children.length - 1;

		// connect the child to the parent
		message.connectParent(this, position);

		// set as the active message
		message.activateMessage();
	};

	/**
	 * Remove a child message
	 */
	removeChild = (message: AbstractMessageStore) => {
		if (!message) {
			return;
		}

		const index = this.children.findIndex(
			(child) => child.id === message.id,
		);
		if (index === -1) {
			return;
		}

		// remove the child
		const [removed] = this.children.splice(index, 1);

		// reset parent linkage on removed child
		if (removed) {
			removed.connectParent(null, -1);
		}

		// reindex remaining children
		this.children.forEach((child, position) => {
			child.position = position;
		});

		// update active child position
		if (this.activeChildPosition === index) {
			this.activeChildPosition = this.children.length
				? Math.min(index, this.children.length - 1)
				: -1;
		} else if (this.activeChildPosition > index) {
			this.activeChildPosition -= 1;
		}
	};

	/**
	 * Set the current message as active
	 */
	activateMessage = () => {
		this.parent.activeChildPosition = this.position;
	};
}
