import { ScrollArea } from "@semoss/ui/next";

export interface WorkspaceMembersListProps {
	/**
	 * WorkspaceId
	 */
	workspaceId: string;

	/**
	 * Search the members by name
	 */
	search: string;
}

export const WorkspaceMembersList = ({
	workspaceId,
}: WorkspaceMembersListProps) => {
	return (
		<ScrollArea className="h-full w-full">
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
			<div>{workspaceId}</div>
		</ScrollArea>
	);
};
