import { DATABASE_WORKBENCH_PANEL_TYPES } from "@semoss/engine-workbench";

export const DATABASE_WORKBENCH_PANELS = {
	SCHEMA: DATABASE_WORKBENCH_PANEL_TYPES.COLUMNS,
	QUERY: DATABASE_WORKBENCH_PANEL_TYPES.QUERY,
	RESULTS: DATABASE_WORKBENCH_PANEL_TYPES.RESULTS,
} as const;
