/**
 * Generate a color based on the input data.
 *
 * @param {object} data The data object with the input data.
 * @param {string|number} color The value to generate a color from.
 * @returns {string} A color string in the format #RRGGBB or hsl(hue, saturation, lightness).
 */
export const newColor = (data, color) => {
    if (data.option['_state']['fields']['colorDataType'] == 'NUMBER') {
        // If the color data type is a number, generate a color by mapping the value to a hue.
        // The hue is calculated as (value * 37) % 360.
        // The saturation and lightness are set to 70% and 50% respectively.
        let colour = color != 'NaN' ? valueToHSL(color) : '#000000';
        return colour;
    }
    if (data.option['_state']['fields']['colorDataType'] == 'STRING') {
        // If the color data type is a string, generate a color by hashing the string.
        // The hash is calculated as the sum of the character codes of the string.
        // The color is then generated by mapping the hash to a color using the hsl color space.
        let colour = color != 'NaN' ? stringToColor(color) : '000000';
        return colour;
    }
};

/**
 * Maps a value to a hue in the hsl color space.
 *
 * @param {number} value The value to map to a hue.
 * @returns {string} A color string in the format hsl(hue, saturation, lightness).
 */
function valueToHSL(value) {
    const hue = (parseInt(value, 10) * 37) % 360;
    return `hsl(${hue}, 70%, 50%)`;
}

/**
 * Maps a string to a color by hashing the string.
 *
 * @param {string} str The string to map to a color.
 * @returns {string} A color string in the format #RRGGBB.
 */
function stringToColor(str) {
    let hash = 0;
    for (let i = 0; i < str?.length; i++) {
        hash = str?.charCodeAt(i) + ((hash << 5) - hash);
    }
    let color = '#';
    for (let i = 0; i < 3; i++) {
        const value = (hash >> (i * 8)) & 0xff;
        color += ('00' + value.toString(16)).slice(-2);
    }
    return color;
}
