import ASTER from "@/assets/img/ASTER.png";
import ATHENA from "@/assets/img/ATHENA.png";
import BIGQUERY from "@/assets/img/BIGQUERY.png";
import CASSANDRA from "@/assets/img/CASSANDRA.png";
import CLICKHOUSE from "@/assets/img/CLICKHOUSE.png";
import CSV from "@/assets/img/CSV.svg";
import DATABRICKS from "@/assets/img/DATABRICKS.png";
import DATASTAX from "@/assets/img/DATASTAX.png";
import DB2 from "@/assets/img/DB2.png";
import DERBY from "@/assets/img/DERBY.png";
import ELASTIC_SEARCH from "@/assets/img/ELASTIC_SEARCH.svg";
import EXCEL from "@/assets/img/EXCEL.png";
import FILE_EXCEL from "@/assets/img/file-excel.svg";
import H2_DB from "@/assets/img/H2_DB.png";
import HIVE from "@/assets/img/HIVE.jpg";
import IMPALA from "@/assets/img/IMPALA.png";
import MARIA_DB from "@/assets/img/MARIA_DB.png";
import MYSQL from "@/assets/img/MYSQL.png";
import NEO4J from "@/assets/img/NEO4J.png";
import OPEN_SEARCH from "@/assets/img/OPEN_SEARCH.png";
import ORACLE from "@/assets/img/ORACLE.png";
import PHOENIX from "@/assets/img/PHOENIX.png";
import POSTGRES from "@/assets/img/POSTGRES.png";
import REDSHIFT from "@/assets/img/REDSHIFT.png";
import SAP_HANA from "@/assets/img/SAP_HANA.png";
import SEMOSS from "@/assets/img/SEMOSS_BLUE_LOGO.svg";
import SNOWFLAKE from "@/assets/img/SNOWFLAKE.png";
import SQL_SERVER from "@/assets/img/SQL_SERVER.png";
import SQLITE from "@/assets/img/SQLITE.png";
import TERADATA from "@/assets/img/TERADATA.png";
import TIBCO from "@/assets/img/TIBCO.png";
import TINKER from "@/assets/img/TINKER.png";
import TRINO from "@/assets/img/TRINO.jpg";
import TSV from "@/assets/img/TSV.svg";
import ZIP from "@/assets/img/ZIP.png";

export const DATABASE_CONNECTION = {
	"File Uploads": [
		{
			name: "CSV",
			disable: false,
			icon: CSV,
			fields: [
				{
					key: "DATABASE_NAME",
					label: "Enter Database Name",
					value: "",
					section: "general",
					category: "General",
					type: "text",
					disabled: false,
					required: true,
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Enter Database Description",
					value: "",
					section: "general",
					category: "General",
					type: "text",
					disabled: false,
					required: false,
				},
				{
					key: "DATABASE_TAG",
					label: "Enter Database Tag",
					value: "",
					section: "general",
					category: "General",
					type: "tags",
					disabled: false,
					required: false,
				},
				{
					key: "DELIMITER",
					label: "Enter Delimiter",
					value: ",",
					section: "Database",
					category: "Database",
					type: "text",
					disabled: false,
					required: false,
				},
				{
					key: "DATABASE_TYPE",
					label: "Enter Database Type",
					value: "",
					section: "Database",
					category: "Database",
					type: "select",
					options: {
						options: [
							{ display: "H2", value: "h2" },
							{ display: "R", value: "r" },
						],
					},
					disabled: false,
					required: true,
				},
				{
					key: "METAMODEL_TYPE",
					label: "Enter Metamodel Type",
					value: "",
					section: "Database",
					type: "select",
					category: "Database",
					options: {
						options: [
							{
								display: "As Flat Table",
								value: "asFlatTable",
							},
							{
								display: "As Suggested Metamodel",
								value: "asSuggestedMetaModel",
							},
							{
								display: "From Scratch",
								value: "fromScratch",
							},
							{
								display: "From Prop File",
								value: "frompropFile",
							},
						],
					},
					disabled: false,
					required: true,
					rules: {
						conditionalOptions: [
							{
								whenField: "DATABASE_TYPE",
								whenValue: "r",
								allowedValues: ["asFlatTable"],
								restrictOtherValues: true,
							},
						],
					},
				},
				{
					key: "FILE_UPLOAD",
					label: "File Upload",
					value: null,
					category: "File Upload",
					section: "Database",
					options: {
						extensions: [".csv"],
					},
					type: "file-upload",
					disabled: false,
					required: true,
					// rules: {
					//   required: {
					//     value: true,
					//     message: "Please upload file / files.",
					//   },
					// },
				},
			],
		},
		{
			name: "Excel",
			disable: false,
			icon: EXCEL,
			fields: [
				{
					key: "DATABASE_NAME",
					label: "Enter Database Name",
					value: "",
					section: "general",
					category: "General",
					type: "text",
					disabled: false,
					required: true,
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Enter Database Description",
					value: "",
					section: "general",
					category: "General",
					type: "text",
					disabled: false,
					required: false,
				},
				{
					key: "DATABASE_TAG",
					label: "Enter Database Tag",
					value: "",
					section: "general",
					category: "General",
					type: "tags",
					disabled: false,
					required: false,
				},
				{
					key: "DATABASE_TYPE",
					label: "Enter Database Type",
					value: "",
					section: "Database",
					category: "Database",
					type: "select",
					options: {
						options: [
							{ display: "H2", value: "h2" },
							{ display: "R", value: "r" },
						],
					},
					disabled: false,
					required: true,
				},
				{
					key: "METAMODEL_TYPE",
					label: "Enter Metamodel Type",
					value: "",
					section: "Database",
					type: "select",
					category: "Database",
					options: {
						options: [
							{
								display: "As Flat Table",
								value: "asFlatTable",
							},
						],
					},
					disabled: false,
					required: true,
					rules: {
						conditionalOptions: [
							{
								whenField: "DATABASE_TYPE",
								whenValue: "r",
								allowedValues: ["asFlatTable"],
								restrictOtherValues: true,
							},
						],
					},
				},
				{
					key: "FILE_UPLOAD",
					label: "File Upload",
					value: null,
					options: {
						extensions: [".xlsx", ".xls", ".xlsm"],
					},
					type: "file-upload",
					category: "File Upload",
					disabled: false,
					required: true,
					rules: {
						required: {
							value: true,
							message: "Please upload file / files.",
						},
					},
				},
			],
		},
		{
			name: "TSV",
			disable: false,
			icon: TSV,
			fields: [
				{
					key: "DATABASE_NAME",
					label: "Enter Database Name",
					value: "",
					section: "general",
					category: "General",
					type: "text",
					disabled: false,
					required: true,
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Enter Database Description",
					value: "",
					section: "general",
					category: "General",
					type: "text",
					disabled: false,
					required: false,
				},
				{
					key: "DATABASE_TAG",
					label: "Enter Database Tag",
					value: "",
					section: "general",
					category: "General",
					type: "tags",
					disabled: false,
					required: false,
				},
				{
					key: "DELIMITER",
					label: "Enter Delimiter",
					value: "\t",
					section: "Database",
					category: "Database",
					type: "text",
					disabled: false,
					required: false,
				},
				{
					key: "DATABASE_TYPE",
					label: "Enter Database Type",
					value: "",
					section: "Database",
					category: "Database",
					type: "select",
					options: {
						options: [
							{ display: "H2", value: "h2" },
							{ display: "R", value: "r" },
						],
					},
					disabled: false,
					required: true,
				},
				{
					key: "METAMODEL_TYPE",
					label: "Enter Metamodel Type",
					value: "",
					section: "Database",
					category: "Database",
					type: "select",
					options: {
						options: [
							{
								display: "As Flat Table",
								value: "asFlatTable",
							},
							{
								display: "As Suggested Metamodel",
								value: "asSuggestedMetaModel",
							},
							{
								display: "From Scratch",
								value: "fromScratch",
							},
							{
								display: "From Prop File",
								value: "frompropFile",
							},
						],
					},
					disabled: false,
					required: true,
					rules: {
						conditionalOptions: [
							{
								whenField: "DATABASE_TYPE",
								whenValue: "r",
								allowedValues: ["asFlatTable"],
								restrictOtherValues: true,
							},
						],
					},
				},
				{
					key: "FILE_UPLOAD",
					label: "File Upload",
					value: null,
					category: "File Upload",
					section: "Database",
					options: {
						extensions: [".tsv"],
					},
					type: "file-upload",
					disabled: false,
					required: true,
					// rules: {
					//   required: {
					//     value: true,
					//     message: "Please upload file / files.",
					//   },
					// },
				},
			],
		},
		{
			name: "SQLite",
			disable: true,
			icon: SQLITE,
			fields: [],
		},
		{
			name: "H2",
			disable: true,
			icon: H2_DB,
			fields: [],
		},
		{
			name: "Neo4J",
			disable: true,
			icon: NEO4J,
			fields: [],
		},
		{
			name: "Tinker",
			disable: true,
			icon: TINKER,
			fields: [],
		},
	],
	Connections: [
		{
			name: "Aster",
			disable: false,
			icon: ASTER,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "ASTER_DB",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
					required: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
					required: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
					required: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
					required: false,
				},
			],
		},
		{
			name: "Athena",
			disable: false,
			icon: ATHENA,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "ATHENA",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "region",
					label: "Region",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "accessKey",
					label: "Access Key",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "secretKey",
					label: "Secret Key",
					value: "",
					type: "password",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "output",
					label: "Output",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					required: false,
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					required: false,
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},
		{
			name: "BigQuery",
			disable: false,
			icon: BIGQUERY,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "BIG_QUERY",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "https://www.googleapis.com/bigquery/v2",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "projectId",
					label: "Project",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "oauthType",
					label: "OAuth Type",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "oauthServiceAcctEmail",
					label: "OAuth Service Account",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "oauthPvtKeyPath",
					label: "OAuth Service Account Key",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
		},
		{
			name: "Cassandra",
			disable: false,
			icon: CASSANDRA,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "CASSANDRA",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "9042",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},
		{
			name: "Clickhouse",
			disable: false,
			icon: CLICKHOUSE,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "CLICKHOUSE",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "9042",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "database",
					label: "Database",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},
		{
			name: "DATABRICKS",
			disable: false,
			icon: DATABRICKS,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "DATABRICKS",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "httpPath",
					label: "HTTP Path",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "UID",
					label: "UID",
					value: "token",
					type: "text",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "PWD",
					label: "Personal Access Token",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "database",
					label: "Database",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},
		{
			name: "DataStax",
			disable: false,
			icon: DATASTAX,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "DATASTAX",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "graph",
					label: "GRAPH",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "token",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "token",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
			],
		},
		{
			name: "DB2",
			disable: false,
			icon: DB2,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "DB2",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "446",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},
		{
			name: "Derby",
			disable: false,
			icon: DERBY,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "DERBY",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "1527",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},

		{
			name: "Elastic Search",
			disable: false,
			icon: ELASTIC_SEARCH,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "ELASTIC_SEARCH",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "9200",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "httpType",
					label: "HTTP Type",
					value: "https",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
		},
		{
			name: "H2",
			disable: false,
			icon: H2_DB,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "H2_DB",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},
		{
			name: "Hive",
			disable: false,
			icon: HIVE,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "HIVE",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "1000",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},
		{
			name: "Impala",
			disable: false,
			icon: IMPALA,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "IMPALA",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "21050",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},
		{
			name: "MariaDB",
			disable: false,
			icon: MARIA_DB,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "MARIA_DB",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "3306",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},
		{
			name: "MySQL",
			disable: false,
			icon: MYSQL,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "MYSQL",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "3306",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},
		{
			name: "Open Search",
			disable: false,
			icon: OPEN_SEARCH,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "OPEN_SEARCH",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "9200",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "httpPath",
					label: "HTTP Path",
					value: "https",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
		},
		{
			name: "Oracle",
			disable: false,
			icon: ORACLE,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "ORACLE",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "service",
					label: "SID Service",
					value: "1521",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},
		{
			name: "Phoenix",
			disable: false,
			icon: PHOENIX,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "PHOENIX",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "8765",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},
		{
			name: "Postgres",
			disable: false,
			icon: POSTGRES,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "POSTGRES",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "5432",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "database",
					label: "Database",
					value: "postgres",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "public",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},
		{
			name: "Redshift",
			disable: false,
			icon: REDSHIFT,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "REDSHIFT",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "5439",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "database",
					label: "Database",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},
		{
			name: "SAP Hana",
			disable: false,
			icon: SAP_HANA,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "SAP_HANA",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]" ) ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "30015",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},
		{
			name: "SEMOSS",
			disable: false,
			icon: SEMOSS,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "SEMOSS",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "443",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "project",
					label: "Project Id",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "insight",
					label: "Insight Id",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "endpoint",
					label: "Endpoint",
					value: "Monolith",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "protocol",
					label: "Protocol",
					value: "https",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "sub_url",
					label: "Sub URL",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},
		{
			name: "Snowflake",
			disable: false,
			icon: SNOWFLAKE,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "SNOWFLAKE",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "443",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "warehouse",
					label: "Warehouse",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "role",
					label: "Role",
					value: "PUBLIC",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "database",
					label: "Database",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},

				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},
		{
			name: "SQL Server",
			disable: false,
			icon: SQL_SERVER,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "SQL_SERVER",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "1433",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "database",
					label: "Database",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "dbo",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},

		{
			name: "SQLITE",
			disable: false,
			icon: SQLITE,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "SQLITE",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "1000",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},
		{
			name: "Teradata",
			disable: false,
			icon: TERADATA,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "TERADATA",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "database",
					label: "Database",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},
		{
			name: "Tibco",
			disable: false,
			icon: TIBCO,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "TIBCO",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "1433",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					required: true,
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},
		{
			name: "Trino",
			disable: false,
			icon: TRINO,
			fields: [
				{
					key: "dbDriver",
					label: "Driver Name",
					value: "TRINO",
					type: "text",
					disabled: true,
					required: true,
					hidden: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
				},
				{
					key: "DATABASE_DESCRIPTION",
					label: "Database Description",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "DATABASE_TAGS",
					label: "Tags",
					value: "",
					type: "tags",
					disabled: false,
					required: false,
					category: "General",
				},
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "1433",
					type: "number",
					disabled: false,
					required: true,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "catalog",
					label: "Catalog",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: [
				{
					key: "FETCH_SIZE",
					label: "Fetch Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "CONNECTION_TIMEOUT",
					label: "Connection Timeout",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "USE_CONNECTION_POOLING",
					label: "Use Connection Pooling",
					value: false,
					required: false,
					type: "checkbox",
					disabled: false,
				},
				{
					key: "POOL_MIN_SIZE",
					label: "Pool Min Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
				{
					key: "POOL_MAX_SIZE",
					label: "Pool Max Size",
					value: "",
					rules: { min: 0 },
					type: "number",
					disabled: false,
				},
			],
		},
	],
};

export const CATEGORY_DESCRIPTIONS = {
	General:
		"Contains descriptive and organizational details about the database, such as name, description, and tags.",
	Settings:
		"Defines the technical configuration needed to connect to the database, including host, port, schema, and connection parameters.",
	Credentials:
		"Stores authentication details required to securely access the database, such as username and password.",
};

export const ENGINE_IMAGES = {
	DATABASE: [
		{
			name: "ZIP",
			icon: ZIP,
		},
		{
			name: "CSV",
			icon: CSV,
		},
		{
			name: "EXCEL",
			icon: EXCEL,
		},
		{
			name: "TSV",
			icon: TSV,
		},
		{
			name: "SQLITE",
			icon: SQLITE,
		},
		{
			name: "H2_DB",
			icon: H2_DB,
		},
		{
			name: "NEO4J",
			icon: NEO4J,
		},
		{
			name: "TINKER",
			icon: TINKER,
		},
		{
			name: "ASTER_DB",
			icon: ASTER,
		},
		{
			name: "ATHENA",
			icon: ATHENA,
		},
		{
			name: "BIG_QUERY",
			icon: BIGQUERY,
		},
		{
			name: "CASSANDRA",
			icon: CASSANDRA,
		},
		{
			name: "CLICKHOUSE",
			icon: CLICKHOUSE,
		},
		{
			name: "DATABRICKS",
			icon: DATABRICKS,
		},
		{
			name: "DATASTAX",
			icon: DATASTAX,
		},
		{
			name: "DB2",
			icon: DB2,
		},
		{
			name: "DERBY",
			icon: DERBY,
		},
		{
			name: "ELASTIC_SEARCH",
			icon: ELASTIC_SEARCH,
		},
		{
			name: "H2",
			icon: H2_DB,
		},
		{
			name: "HIVE",
			icon: HIVE,
		},
		{
			name: "IMPALA",
			icon: IMPALA,
		},
		{
			name: "MARIA_DB",
			icon: MARIA_DB,
		},
		{
			name: "MYSQL",
			icon: MYSQL,
		},
		{
			name: "OPEN_SEARCH",
			icon: OPEN_SEARCH,
		},
		{
			name: "ORACLE",
			icon: ORACLE,
		},
		{
			name: "PHOENIX",
			icon: PHOENIX,
		},
		{
			name: "POSTGRES",
			icon: POSTGRES,
		},
		{
			name: "REDSHIFT",
			icon: REDSHIFT,
		},
		{
			name: "SAP_HANA",
			icon: SAP_HANA,
		},
		{
			name: "SEMOSS",
			icon: SEMOSS,
		},
		{
			name: "SNOWFLAKE",
			icon: SNOWFLAKE,
		},
		{
			name: "SQL_SERVER",
			icon: SQL_SERVER,
		},
		{
			name: "SQLITE",
			icon: SQLITE,
		},
		{
			name: "TERADATA",
			icon: TERADATA,
		},
		{
			name: "TIBCO",
			icon: TIBCO,
		},
		{
			name: "TRINO",
			icon: TRINO,
		},
	],
};

export const CSV_UPLOAD_ICONS = {
	FILE_EXCEL,
};
