import ASTER from "@/assets/img/ASTER.png";
import ATHENA from "@/assets/img/ATHENA.png";
import BIGQUERY from "@/assets/img/BIGQUERY.png";
import CASSANDRA from "@/assets/img/CASSANDRA.svg";
import CLICKHOUSE from "@/assets/img/CLICKHOUSE.png";
import CSV from "@/assets/img/CSV.svg";
import DATABRICKS from "@/assets/img/DATABRICKS.png";
import DATASTAX from "@/assets/img/DATASTAX.png";
import DB2 from "@/assets/img/DB2.png";
import DERBY from "@/assets/img/DERBY.png";
import ELASTIC_SEARCH from "@/assets/img/ELASTIC_SEARCH.svg";
import EXCEL from "@/assets/img/EXCEL.png";
import FILE_EXCEL from "@/assets/img/file-excel.svg";
import H2_DB from "@/assets/img/H2_DB.png";
import HIVE from "@/assets/img/HIVE.jpg";
import IMPALA from "@/assets/img/IMPALA.png";
import MARIA_DB from "@/assets/img/MARIA_DB.png";
import MYSQL from "@/assets/img/MYSQL.svg";
import NEO4J from "@/assets/img/NEO4J.png";
import OPEN_SEARCH from "@/assets/img/OPEN_SEARCH.png";
import ORACLE from "@/assets/img/ORACLE.svg";
import PHOENIX from "@/assets/img/PHOENIX.png";
import POSTGRES from "@/assets/img/POSTGRES.svg";
import REDSHIFT from "@/assets/img/REDSHIFT.png";
import SAP_HANA from "@/assets/img/SAP_HANA.png";
import SEMOSS from "@/assets/img/SEMOSS_BLUE_LOGO.svg";
import SNOWFLAKE from "@/assets/img/SNOWFLAKE.png";
import SQL_SERVER from "@/assets/img/SQL_SERVER.png";
import SQLITE from "@/assets/img/SQLITE.svg";
import TERADATA from "@/assets/img/TERADATA.png";
import TIBCO from "@/assets/img/TIBCO.png";
import TINKER from "@/assets/img/TINKER.png";
import TRINO from "@/assets/img/TRINO.jpg";
import TSV from "@/assets/img/TSV.svg";
import ZIP from "@/assets/img/ZIP.png";
import type { FormField } from "../shared/import-form.types";
import {
	CHECK_ENGINE_NAME_MESSAGE,
	COMMON_FILE_GENERAL_FIELDS,
	COMMON_JDBC_ADVANCED,
	COMMON_JDBC_GENERAL_FIELDS,
	dbDriverField,
	jdbcConnectionFields,
	NAME_PATTERN_RULE,
} from "./database-form.bases";

// ---------------------------------------------------------------------------
// Shared field constants reused across CSV / TSV / TXT
// ---------------------------------------------------------------------------

const DELIMITED_DATABASE_TYPE_FIELD: FormField = {
	key: "DATABASE_TYPE",
	label: "Enter Database Type",
	value: "h2",
	section: "Database",
	category: "Database",
	type: "select",
	options: {
		options: [
			{ display: "H2", value: "h2" },
			{ display: "R", value: "r" },
			{ display: "RDF", value: "rdf" },
		],
	},
	disabled: false,
	required: true,
	displayRules: {
		hideOtherFields: [{ key: "CUSTOM_BASE_URI", value: ["h2", "r"] }],
	},
};

const DELIMITED_METAMODEL_TYPE_FIELD: FormField = {
	key: "METAMODEL_TYPE",
	label: "Enter Metamodel Type",
	value: "asFlatTable",
	section: "Database",
	type: "select",
	category: "Database",
	options: {
		options: [
			{ display: "As Flat Table", value: "asFlatTable" },
			{
				display: "As Suggested Metamodel",
				value: "asSuggestedMetaModel",
			},
			{ display: "From Prop File", value: "fromPropFile" },
		],
	},
	disabled: false,
	required: true,
	rules: {
		conditionalOptions: [
			{
				whenField: "DATABASE_TYPE",
				whenValue: "r",
				allowedValues: ["asFlatTable"],
				restrictOtherValues: true,
			},
		],
	},
};

const CUSTOM_BASE_URI_FIELD: FormField = {
	key: "CUSTOM_BASE_URI",
	label: "Custom URI",
	value: "http://semoss.org/ontologies",
	section: "Database",
	category: "Database",
	type: "text",
	disabled: false,
	required: false,
	hidden: true,
};

const PROP_FILE_UPLOAD_FIELD: FormField = {
	key: "PROP_FILE_UPLOAD",
	label: "Prop File (.json)",
	value: null,
	category: "File Upload",
	section: "Database",
	options: { extensions: [".json"] },
	type: "file-upload",
	disabled: false,
	required: false,
	hidden: true,
};

// ---------------------------------------------------------------------------
// UPLOAD_MODE radio field reused by H2 and SQLite file-upload forms
// ---------------------------------------------------------------------------

function uploadModeField(uploadLabel: string): FormField {
	return {
		key: "UPLOAD_MODE",
		label: "Connection Type",
		value: "empty",
		category: "File Upload",
		type: "radio",
		options: {
			options: [
				{ display: "Create Empty Database", value: "empty" },
				{ display: uploadLabel, value: "file" },
			],
		},
		disabled: false,
		required: true,
		displayRules: {
			hideOtherFields: [
				{ key: "FILE_UPLOAD", value: ["empty"] },
				{ key: "schema", value: ["empty"] },
			],
		},
	};
}

// ---------------------------------------------------------------------------
// SAP Hana uses a slightly different CheckEngineName pixel expression
// ---------------------------------------------------------------------------

const SAP_HANA_NAME_FIELD: FormField = {
	key: "NAME",
	label: "Catalog Name",
	value: "",
	type: "text",
	disabled: false,
	required: true,
	category: "General",
	rules: {
		pattern: NAME_PATTERN_RULE,
		custom: {
			value: 'META | CheckEngineName ( "[VALUE]" ) ;',
			message: CHECK_ENGINE_NAME_MESSAGE,
		},
	},
};

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

export const DATABASE_CONNECTION = {
	"File Uploads": [
		{
			name: "CSV",
			disable: false,
			icon: CSV,
			fields: [
				...COMMON_FILE_GENERAL_FIELDS,
				{
					key: "DELIMITER",
					label: "Enter Delimiter",
					value: ",",
					section: "Database",
					category: "Database",
					type: "text",
					disabled: true,
					hidden: true,
					required: false,
				},
				DELIMITED_DATABASE_TYPE_FIELD,
				DELIMITED_METAMODEL_TYPE_FIELD,
				CUSTOM_BASE_URI_FIELD,
				{
					key: "FILE_UPLOAD",
					label: "File Upload",
					value: null,
					category: "File Upload",
					section: "Database",
					options: { extensions: [".csv"] },
					type: "file-upload",
					disabled: false,
					required: true,
				},
				PROP_FILE_UPLOAD_FIELD,
			],
		},
		{
			name: "Excel",
			disable: false,
			icon: EXCEL,
			fields: [
				...COMMON_FILE_GENERAL_FIELDS,
				{
					key: "DATABASE_TYPE",
					label: "Enter Database Type",
					value: "h2",
					section: "Database",
					category: "Database",
					type: "select",
					options: {
						options: [
							{ display: "H2", value: "h2" },
							{ display: "RDF", value: "rdf" },
						],
					},
					disabled: false,
					required: true,
					displayRules: {
						hideOtherFields: [
							{ key: "CUSTOM_BASE_URI", value: ["h2"] },
						],
					},
				},
				{
					key: "METAMODEL_TYPE",
					label: "Enter Metamodel Type",
					value: "",
					section: "Database",
					type: "select",
					category: "Database",
					options: {
						options: [
							{ display: "As Flat Table", value: "asFlatTable" },
							{
								display: "Excel Loader Sheet Format",
								value: "excelLoaderSheetFormat",
							},
						],
					},
					disabled: false,
					required: true,
					rules: {
						conditionalOptions: [
							{
								whenField: "DATABASE_TYPE",
								whenValue: "rdf",
								allowedValues: ["excelLoaderSheetFormat"],
								restrictOtherValues: true,
							},
						],
					},
				},
				CUSTOM_BASE_URI_FIELD,
				{
					key: "FILE_UPLOAD",
					label: "File Upload",
					value: null,
					options: {
						extensions: [".xlsx", ".xls", ".xlsm"],
					},
					type: "file-upload",
					category: "File Upload",
					disabled: false,
					required: true,
					rules: {
						required: {
							value: true,
							message: "Please upload file / files.",
						},
					},
				},
			],
		},
		{
			name: "TSV",
			disable: false,
			icon: TSV,
			fields: [
				...COMMON_FILE_GENERAL_FIELDS,
				{
					key: "DELIMITER",
					label: "Enter Delimiter",
					value: "\t",
					section: "Database",
					category: "Database",
					type: "text",
					disabled: true,
					hidden: true,
					required: false,
				},
				DELIMITED_DATABASE_TYPE_FIELD,
				DELIMITED_METAMODEL_TYPE_FIELD,
				CUSTOM_BASE_URI_FIELD,
				{
					key: "FILE_UPLOAD",
					label: "File Upload",
					value: null,
					category: "File Upload",
					section: "Database",
					options: { extensions: [".tsv"] },
					type: "file-upload",
					disabled: false,
					required: true,
				},
				PROP_FILE_UPLOAD_FIELD,
			],
		},
		{
			name: "TXT",
			disable: false,
			icon: CSV,
			fields: [
				...COMMON_FILE_GENERAL_FIELDS,
				{
					key: "DELIMITER",
					label: "Enter Delimiter",
					value: ",",
					section: "Database",
					category: "Database",
					type: "text",
					disabled: false,
					hidden: false,
					required: false,
				},
				DELIMITED_DATABASE_TYPE_FIELD,
				DELIMITED_METAMODEL_TYPE_FIELD,
				CUSTOM_BASE_URI_FIELD,
				{
					key: "FILE_UPLOAD",
					label: "File Upload",
					value: null,
					category: "File Upload",
					section: "Database",
					options: { extensions: [".txt"] },
					type: "file-upload",
					disabled: false,
					required: true,
				},
				PROP_FILE_UPLOAD_FIELD,
			],
		},
		{
			name: "H2",
			disable: false,
			icon: H2_DB,
			fields: [
				dbDriverField("H2_DB"),
				...COMMON_JDBC_GENERAL_FIELDS,
				uploadModeField("Upload Existing H2 Database"),
				{
					key: "FILE_UPLOAD",
					label: "File Upload",
					value: null,
					category: "File Upload",
					options: { extensions: [".mv.db"] },
					type: "file-upload",
					disabled: false,
					required: false,
					hidden: true,
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					category: "Credentials",
					type: "text",
					disabled: false,
					required: false,
					hidden: true,
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					category: "Credentials",
					type: "text",
					disabled: false,
					required: false,
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					category: "Credentials",
					type: "password",
					disabled: false,
					required: false,
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					category: "Credentials",
					type: "text",
					disabled: true,
					required: false,
					hidden: true,
				},
			],
		},
		{
			name: "SQLite",
			disable: false,
			icon: SQLITE,
			fields: [
				dbDriverField("SQLITE"),
				...COMMON_JDBC_GENERAL_FIELDS,
				uploadModeField("Upload Existing SQLite Database"),
				{
					key: "FILE_UPLOAD",
					label: "File Upload",
					value: null,
					category: "File Upload",
					options: { extensions: [".sqlite"] },
					type: "file-upload",
					disabled: false,
					required: false,
					hidden: true,
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					category: "Credentials",
					type: "text",
					disabled: false,
					required: false,
					hidden: true,
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					category: "Credentials",
					type: "text",
					disabled: false,
					required: false,
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					category: "Credentials",
					type: "password",
					disabled: false,
					required: false,
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					category: "Credentials",
					type: "text",
					disabled: true,
					required: false,
					hidden: true,
				},
			],
		},
		{
			name: "Neo4J",
			disable: true,
			icon: NEO4J,
			fields: [],
		},
		{
			name: "Tinker",
			disable: true,
			icon: TINKER,
			fields: [],
		},
	],
	Connections: [
		// -----------------------------------------------------------------------
		// Standard JDBC forms — driver value and port default are the only
		// differences; all field sets, labels, and categories are identical
		// -----------------------------------------------------------------------
		{
			name: "Aster",
			disable: false,
			icon: ASTER,
			fields: [
				dbDriverField("ASTER_DB"),
				...COMMON_JDBC_GENERAL_FIELDS,
				...jdbcConnectionFields(),
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		// -----------------------------------------------------------------------
		// Non-standard: Athena
		// -----------------------------------------------------------------------
		{
			name: "Athena",
			disable: false,
			icon: ATHENA,
			fields: [
				dbDriverField("ATHENA"),
				...COMMON_JDBC_GENERAL_FIELDS,
				{
					key: "region",
					label: "Region",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "accessKey",
					label: "Access Key",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "secretKey",
					label: "Secret Key",
					value: "",
					type: "password",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "output",
					label: "Output",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		// -----------------------------------------------------------------------
		// Non-standard: BigQuery (no advanced section)
		// -----------------------------------------------------------------------
		{
			name: "BigQuery",
			disable: false,
			icon: BIGQUERY,
			fields: [
				dbDriverField("BIG_QUERY"),
				...COMMON_JDBC_GENERAL_FIELDS,
				{
					key: "hostname",
					label: "Host Name",
					value: "https://www.googleapis.com/bigquery/v2",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "projectId",
					label: "Project",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "oauthType",
					label: "OAuth Type",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "oauthServiceAcctEmail",
					label: "OAuth Service Account",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "oauthPvtKeyPath",
					label: "OAuth Service Account Key",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
		},
		{
			name: "Cassandra",
			disable: false,
			icon: CASSANDRA,
			fields: [
				dbDriverField("CASSANDRA"),
				...COMMON_JDBC_GENERAL_FIELDS,
				...jdbcConnectionFields({ portDefault: "9042" }),
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		// -----------------------------------------------------------------------
		// Non-standard: Clickhouse (extra database field between port and schema)
		// -----------------------------------------------------------------------
		{
			name: "Clickhouse",
			disable: false,
			icon: CLICKHOUSE,
			fields: [
				dbDriverField("CLICKHOUSE"),
				...COMMON_JDBC_GENERAL_FIELDS,
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "9042",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "database",
					label: "Database",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		// -----------------------------------------------------------------------
		// Non-standard: Databricks
		// -----------------------------------------------------------------------
		{
			name: "Databricks",
			disable: false,
			icon: DATABRICKS,
			fields: [
				dbDriverField("DATABRICKS"),
				...COMMON_JDBC_GENERAL_FIELDS,
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "httpPath",
					label: "HTTP Path",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "UID",
					label: "UID",
					value: "token",
					type: "text",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "PWD",
					label: "Personal Access Token",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "database",
					label: "Database",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		// -----------------------------------------------------------------------
		// Non-standard: DataStax (no advanced section)
		// -----------------------------------------------------------------------
		{
			name: "DataStax",
			disable: false,
			icon: DATASTAX,
			fields: [
				dbDriverField("DATASTAX"),
				...COMMON_JDBC_GENERAL_FIELDS,
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "graph",
					label: "GRAPH",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "token",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "token",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
			],
		},
		{
			name: "DB2",
			disable: false,
			icon: DB2,
			fields: [
				dbDriverField("DB2"),
				...COMMON_JDBC_GENERAL_FIELDS,
				...jdbcConnectionFields({ portDefault: "446" }),
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		{
			name: "Derby",
			disable: false,
			icon: DERBY,
			fields: [
				dbDriverField("DERBY"),
				...COMMON_JDBC_GENERAL_FIELDS,
				...jdbcConnectionFields({ portDefault: "1527" }),
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		// -----------------------------------------------------------------------
		// Non-standard: Elastic Search (httpType instead of schema, no advanced)
		// -----------------------------------------------------------------------
		{
			name: "Elastic Search",
			disable: false,
			icon: ELASTIC_SEARCH,
			fields: [
				dbDriverField("ELASTIC_SEARCH"),
				...COMMON_JDBC_GENERAL_FIELDS,
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "9200",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "httpType",
					label: "HTTP Type",
					value: "https",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
		},
		// H2 in Connections tab (JDBC connection, not file upload)
		{
			name: "H2",
			disable: false,
			icon: H2_DB,
			fields: [
				dbDriverField("H2_DB"),
				...COMMON_JDBC_GENERAL_FIELDS,
				...jdbcConnectionFields({
					schemaRequired: true,
					connectionUrlRequired: true,
				}),
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		{
			name: "Hive",
			disable: false,
			icon: HIVE,
			fields: [
				dbDriverField("HIVE"),
				...COMMON_JDBC_GENERAL_FIELDS,
				...jdbcConnectionFields({ portDefault: "1000" }),
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		{
			name: "Impala",
			disable: false,
			icon: IMPALA,
			fields: [
				dbDriverField("IMPALA"),
				...COMMON_JDBC_GENERAL_FIELDS,
				...jdbcConnectionFields({ portDefault: "21050" }),
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		{
			name: "MariaDB",
			disable: false,
			icon: MARIA_DB,
			fields: [
				dbDriverField("MARIA_DB"),
				...COMMON_JDBC_GENERAL_FIELDS,
				...jdbcConnectionFields({ portDefault: "3306" }),
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		{
			name: "MySQL",
			disable: false,
			icon: MYSQL,
			fields: [
				dbDriverField("MYSQL"),
				...COMMON_JDBC_GENERAL_FIELDS,
				...jdbcConnectionFields({ portDefault: "3306" }),
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		// -----------------------------------------------------------------------
		// Non-standard: Open Search (httpPath instead of schema, no advanced)
		// -----------------------------------------------------------------------
		{
			name: "Open Search",
			disable: false,
			icon: OPEN_SEARCH,
			fields: [
				dbDriverField("OPEN_SEARCH"),
				...COMMON_JDBC_GENERAL_FIELDS,
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "9200",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "httpPath",
					label: "HTTP Path",
					value: "https",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
		},
		// -----------------------------------------------------------------------
		// Non-standard: Oracle (SID Service field instead of schema)
		// -----------------------------------------------------------------------
		{
			name: "Oracle",
			disable: false,
			icon: ORACLE,
			fields: [
				dbDriverField("ORACLE"),
				...COMMON_JDBC_GENERAL_FIELDS,
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "service",
					label: "SID Service",
					value: "1521",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		{
			name: "Phoenix",
			disable: false,
			icon: PHOENIX,
			fields: [
				dbDriverField("PHOENIX"),
				...COMMON_JDBC_GENERAL_FIELDS,
				...jdbcConnectionFields({ portDefault: "8765" }),
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		// -----------------------------------------------------------------------
		// Non-standard: Postgres (database + schema with non-empty defaults)
		// -----------------------------------------------------------------------
		{
			name: "Postgres",
			disable: false,
			icon: POSTGRES,
			fields: [
				dbDriverField("POSTGRES"),
				...COMMON_JDBC_GENERAL_FIELDS,
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "5432",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "database",
					label: "Database",
					value: "postgres",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "public",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		// -----------------------------------------------------------------------
		// Non-standard: Redshift (database field required)
		// -----------------------------------------------------------------------
		{
			name: "Redshift",
			disable: false,
			icon: REDSHIFT,
			fields: [
				dbDriverField("REDSHIFT"),
				...COMMON_JDBC_GENERAL_FIELDS,
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "5439",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "database",
					label: "Database",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		// SAP Hana uses a different CheckEngineName pixel expression
		{
			name: "SAP Hana",
			disable: false,
			icon: SAP_HANA,
			fields: [
				dbDriverField("SAP_HANA"),
				SAP_HANA_NAME_FIELD,
				...COMMON_JDBC_GENERAL_FIELDS.slice(1),
				...jdbcConnectionFields({ portDefault: "30015" }),
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		// -----------------------------------------------------------------------
		// Non-standard: SEMOSS
		// -----------------------------------------------------------------------
		{
			name: "SEMOSS",
			disable: false,
			icon: SEMOSS,
			fields: [
				dbDriverField("SEMOSS"),
				...COMMON_JDBC_GENERAL_FIELDS,
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "443",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "project",
					label: "Project Id",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "insight",
					label: "Insight Id",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "endpoint",
					label: "Endpoint",
					value: "Monolith",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "protocol",
					label: "Protocol",
					value: "https",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "sub_url",
					label: "Sub URL",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		// -----------------------------------------------------------------------
		// Non-standard: Snowflake (warehouse, role, database, schema required)
		// -----------------------------------------------------------------------
		{
			name: "Snowflake",
			disable: false,
			icon: SNOWFLAKE,
			fields: [
				dbDriverField("SNOWFLAKE"),
				...COMMON_JDBC_GENERAL_FIELDS,
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "443",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "warehouse",
					label: "Warehouse",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "role",
					label: "Role",
					value: "PUBLIC",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "database",
					label: "Database",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		// -----------------------------------------------------------------------
		// Non-standard: SQL Server (database + schema with "dbo" default)
		// -----------------------------------------------------------------------
		{
			name: "SQL Server",
			disable: false,
			icon: SQL_SERVER,
			fields: [
				dbDriverField("SQL_SERVER"),
				...COMMON_JDBC_GENERAL_FIELDS,
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "port",
					label: "Port",
					value: "1433",
					type: "number",
					disabled: false,
					rules: { min: 0 },
					category: "Settings",
				},
				{
					key: "database",
					label: "Database",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "schema",
					label: "Schema",
					value: "dbo",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		// SQLITE in Connections tab (no schema field)
		{
			name: "SQLITE",
			disable: false,
			icon: SQLITE,
			fields: [
				dbDriverField("SQLITE"),
				...COMMON_JDBC_GENERAL_FIELDS,
				...jdbcConnectionFields({
					portDefault: "1000",
					noSchema: true,
				}),
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		// -----------------------------------------------------------------------
		// Non-standard: Teradata (hostname + database only, no port / schema)
		// -----------------------------------------------------------------------
		{
			name: "Teradata",
			disable: false,
			icon: TERADATA,
			fields: [
				dbDriverField("TERADATA"),
				...COMMON_JDBC_GENERAL_FIELDS,
				{
					key: "hostname",
					label: "Host Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "database",
					label: "Database",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "USERNAME",
					label: "Username",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "PASSWORD",
					label: "Password",
					value: "",
					type: "password",
					disabled: false,
					required: false,
					category: "Credentials",
				},
				{
					key: "additional",
					label: "Additional Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "CONNECTION_URL",
					label: "JDBC Url",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		{
			name: "Tibco",
			disable: false,
			icon: TIBCO,
			fields: [
				dbDriverField("TIBCO"),
				...COMMON_JDBC_GENERAL_FIELDS,
				...jdbcConnectionFields({
					portDefault: "1433",
					portRequired: true,
					schemaRequired: true,
				}),
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
		{
			name: "Trino",
			disable: false,
			icon: TRINO,
			fields: [
				dbDriverField("TRINO"),
				...COMMON_JDBC_GENERAL_FIELDS,
				...jdbcConnectionFields({ portDefault: "1433" }),
			],
			advanced: COMMON_JDBC_ADVANCED,
		},
	],
};

export const CATEGORY_DESCRIPTIONS = {
	General:
		"Contains descriptive and organizational details about the database, such as name, description, and tags.",
	Database:
		"Select the database engine type and how the data should be imported.",
	"File Upload": "Upload the file to import.",
	Settings:
		"Defines the technical configuration needed to connect to the database, including host, port, schema, and connection parameters.",
	Credentials:
		"Stores authentication details required to securely access the database, such as username and password.",
};

export const ENGINE_IMAGES = {
	DATABASE: [
		{ name: "ASTER_DB", icon: ASTER },
		{ name: "ATHENA", icon: ATHENA },
		{ name: "BIG_QUERY", icon: BIGQUERY },
		{ name: "CASSANDRA", icon: CASSANDRA },
		{ name: "CLICKHOUSE", icon: CLICKHOUSE },
		{ name: "CSV", icon: CSV },
		{ name: "DATABRICKS", icon: DATABRICKS },
		{ name: "DATASTAX", icon: DATASTAX },
		{ name: "DB2", icon: DB2 },
		{ name: "DERBY", icon: DERBY },
		{ name: "ELASTIC_SEARCH", icon: ELASTIC_SEARCH },
		{ name: "EXCEL", icon: EXCEL },
		{ name: "H2", icon: H2_DB },
		{ name: "H2_DB", icon: H2_DB },
		{ name: "HIVE", icon: HIVE },
		{ name: "IMPALA", icon: IMPALA },
		{ name: "MARIA_DB", icon: MARIA_DB },
		{ name: "MYSQL", icon: MYSQL },
		{ name: "NEO4J", icon: NEO4J },
		{ name: "OPEN_SEARCH", icon: OPEN_SEARCH },
		{ name: "ORACLE", icon: ORACLE },
		{ name: "PHOENIX", icon: PHOENIX },
		{ name: "POSTGRES", icon: POSTGRES },
		{ name: "REDSHIFT", icon: REDSHIFT },
		{ name: "SAP_HANA", icon: SAP_HANA },
		{ name: "SEMOSS", icon: SEMOSS },
		{ name: "SNOWFLAKE", icon: SNOWFLAKE },
		{ name: "SQL_SERVER", icon: SQL_SERVER },
		{ name: "SQLITE", icon: SQLITE },
		{ name: "SQLITE", icon: SQLITE },
		{ name: "TERADATA", icon: TERADATA },
		{ name: "TIBCO", icon: TIBCO },
		{ name: "TINKER", icon: TINKER },
		{ name: "TRINO", icon: TRINO },
		{ name: "TSV", icon: TSV },
		{ name: "ZIP", icon: ZIP },
	],
};

export const CSV_UPLOAD_ICONS = {
	FILE_EXCEL,
};
