import AWS_COMPREHEND from "@/assets/img/AWS_COMPREHEND.png";
import AWS_POLLY from "@/assets/img/AWS_POLLY.png";
import AWS_TEXTRACT from "@/assets/img/AWS_TEXTRACT.png";
import AWS_TRANSCRIBE from "@/assets/img/AWS_TRANSCRIBE.png";
import AZURE_SPEECH_TO_TEXT from "@/assets/img/AZURE_SPEECH_TO_TEXT.png";
import GOOGLE_OCR from "@/assets/img/GOOGLE_OCR.png";
import GOOGLE_SPEECH_TO_TEXT from "@/assets/img/GOOGLE_SPEECH_TO_TEXT.png";
import RESTAPI from "@/assets/img/REST-API.svg";

export const FUNCTION_CONNECTIONS = {
	description: {
		General:
			"Choose between hosted OpenAI services for managed reliability, or custom-deployed environments for greater control over API usage and performance.",
		Settings:
			"Configure your model type, deployment parameters, and response behavior to align with your specific OpenAI integration.",
		Credentials:
			"Enter your OpenAI API key to securely authenticate and enable access to the OpenAI endpoints.",
	},
	Functions: [
		{
			name: "AWS Image Text Extraction",
			disable: false,
			icon: AWS_TEXTRACT,
			description: "Extracts text from images using Amazon Textract",
			link: "https://docs.aws.amazon.com/textract/latest/dg/what-is.html",
			fields: [
				{
					key: "FUNCTION_TYPE",
					label: "Function Type",
					value: "AWS_TEXTRACT",
					type: "select",
					options: [
						{
							display: "AWS TEXTRACT",
							value: "AWS_TEXTRACT",
						},
						{
							display: "AWS REKOGNITION",
							value: "AWS_REKOGNITION",
						},
					],
					disabled: false,
					hidden: false,
					required: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
					category: "General",
				},
				{
					key: "ACCESS_KEY",
					label: "Access Key",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "SECRET_KEY",
					label: "Secret Key",
					value: "",
					type: "password",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "REGION",
					label: "Region",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "S3BUCKETENGINEID",
					label: "S3 Bucket Engine Id",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FUNCTION_NAME",
					label: "Function Name (metadata)",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FUNCTION_DESCRIPTION",
					label: "Function Description (metadata)",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FUNCTION_REQUIRED_PARAMETERS",
					label: "Function Required Parameters",
					value: '["isFilePresentInS3","filePath"]',
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
			],
		},
		{
			name: "AWS Polly",
			disable: false,
			icon: AWS_POLLY,
			description: "Converts text to lifelike speech using Amazon Polly",
			link: "https://docs.aws.amazon.com/polly/latest/dg/what-is.html",
			fields: [
				{
					key: "FUNCTION_TYPE",
					label: "Function Type",
					value: "AWS_POLLY",

					type: "text",
					disabled: true,
					required: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "General",
				},
				{
					key: "ACCESS_KEY",
					label: "Access Key",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "SECRET_KEY",
					label: "Secret Key",
					value: "",
					type: "password",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "REGION",
					label: "Region",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FUNCTION_NAME",
					label: "Function Name (metadata)",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FUNCTION_DESCRIPTION",
					label: "Function Description (metadata)",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FUNCTION_REQUIRED_PARAMETERS",
					label: "Function Required Parameters",
					value: '["extractedText","nameOfTheAudioFile"]',
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
			],
		},
		{
			name: "AWS Transcribe",
			disable: false,
			icon: AWS_TRANSCRIBE,
			description: "Converts speech to text using Amazon Transcribe",
			link: "https://docs.aws.amazon.com/transcribe/latest/dg/what-is.html",
			fields: [
				{
					key: "FUNCTION_TYPE",
					label: "Function Type",
					value: "AWS_Transcribe",

					type: "text",
					disabled: true,
					required: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
					category: "General",
				},
				{
					key: "ACCESS_KEY",
					label: "Access Key",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "SECRET_KEY",
					label: "Secret Key",
					value: "",
					type: "password",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "REGION",
					label: "Region",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "S3BUCKETENGINEID",
					label: "S3 Bucket Engine Id",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FUNCTION_NAME",
					label: "Function Name (metadata)",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FUNCTION_DESCRIPTION",
					label: "Function Description (metadata)",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FUNCTION_REQUIRED_PARAMETERS",
					label: "Function Required Parameters",
					value: '["isFilePresentInS3","filePath"]',
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
			],
		},
		{
			name: "AWS Comprehend",
			disable: false,
			icon: AWS_COMPREHEND,
			description: "Natural language processing using Amazon Comprehend",
			link: "https://docs.aws.amazon.com/comprehend/latest/dg/what-is.html",
			fields: [
				{
					key: "FUNCTION_TYPE",
					label: "Function Type",
					value: "AWS_COMPREHEND",
					type: "text",
					disabled: true,
					required: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
					category: "General",
				},
				{
					key: "ACCESS_KEY",
					label: "Access Key",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "SECRET_KEY",
					label: "Secret Key",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "REGION",
					label: "Region",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FUNCTION_REQUIRED_PARAMETERS",
					label: "Function Required Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FUNCTION_NAME",
					label: "Function Name (metadata)",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FUNCTION_DESCRIPTION",
					label: "Function Description (metadata)",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
			],
		},
		{
			name: "Azure Document Intelligence",
			disable: false,
			icon: RESTAPI,
			description:
				"Extracts text and data from documents using Azure Document Intelligence",
			link: "https://learn.microsoft.com/en-us/azure/cognitive-services/form-recognizer/overview",
			fields: [
				{
					key: "FUNCTION_TYPE",
					label: "Function Type",
					value: "AZURE_DOCUMENT_INTELLIGENCE_CUSTOM_EMBEDDINGS",
					type: "text",
					disabled: true,
					required: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
					category: "General",
				},
				{
					key: "URL",
					label: "URL",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "API_KEY",
					label: "API Key",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Credentials",
				},
			],
		},
		{
			name: "Azure Speech To Text",
			disable: false,
			icon: AZURE_SPEECH_TO_TEXT,
			description: "Converts speech to text using Azure Speech to Text",
			link: "https://learn.microsoft.com/en-us/azure/ai-services/speech-service/index-text-to-speech",
			fields: [
				{
					key: "FUNCTION_TYPE",
					label: "Function Type",
					value: "AZURE SPEECH TO TEXT",
					type: "text",
					disabled: true,
					required: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
					category: "General",
				},
				{
					key: "SPEECH_KEY",
					label: "Speech Key",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "SPEECH_REGION",
					label: "Speech region",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FUNCTION_REQUIRED_PARAMETERS",
					label: "Function Required Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FUNCTION_NAME",
					label: "Function Name (metadata)",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FUNCTION_DESCRIPTION",
					label: "Function Description (metadata)",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
			],
		},
		{
			name: "Google Speech To Text",
			disable: false,
			icon: GOOGLE_SPEECH_TO_TEXT,
			description: "Converts speech to text using Google Speech-to-Text",
			link: "https://cloud.google.com/speech-to-text/docs",
			fields: [
				{
					key: "FUNCTION_TYPE",
					label: "Function Type",
					value: "GOOGLE_SPEECH_TO_TEXT",

					type: "text",
					disabled: true,
					required: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
					category: "General",
				},
				{
					key: "GOOGLE_BUCKET_ENGINEID",
					label: "Google Bucket Engine Id",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "FUNCTION_NAME",
					label: "Function Name (metadata)",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "FUNCTION_DESCRIPTION",
					label: "Function Description (metadata)",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "FUNCTION_REQUIRED_PARAMETERS",
					label: "Function Required Parameters",
					value: '["isFilePresentInBucket","filePath"]',
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FILE",
					label: "Upload Service Account File",
					value: null,
					type: "file-upload",
					disabled: false,
					secondary: true,
					required: true,
					category: "Settings",
				},
			],
		},
		{
			name: "Google OCR",
			disable: false,
			icon: GOOGLE_OCR,
			description:
				"Extracts text from images using Google Cloud Vision OCR",
			link: "https://cloud.google.com/vision/docs/ocr",
			fields: [
				{
					key: "FUNCTION_TYPE",
					label: "Function Type",
					value: "GOOGLE_OCR",

					type: "text",
					disabled: true,
					required: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
					category: "General",
				},
				{
					key: "PROJECT_ID",
					label: "Project Id",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "PROCESSOR_ID",
					label: "Processor Id",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "REGION",
					label: "Region",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FILE",
					label: "Upload Service Account File",
					value: null,
					type: "file-upload",
					disabled: false,
					secondary: true,
					required: true,
					category: "Settings",
				},
				{
					key: "GOOGLE_BUCKET_ENGINEID",
					label: "Google Bucket Engine Id",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FUNCTION_NAME",
					label: "Function Name (metadata)",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FUNCTION_DESCRIPTION",
					label: "Function Description (metadata)",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FUNCTION_REQUIRED_PARAMETERS",
					label: "Function Required Parameters",
					value: '["isFilePresentInBucket","filePath"]',
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
			],
		},
		{
			name: "REST",
			disable: false,
			icon: RESTAPI,
			description: "Connect to any RESTful API endpoint",
			link: " https://restfulapi.net/",
			fields: [
				{
					key: "FUNCTION_TYPE",
					label: "Function Type",
					value: "REST",
					type: "text",
					disabled: true,
					required: true,
					category: "General",
				},
				{
					key: "NAME",
					label: "Catalog Name",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					rules: {
						pattern: {
							value: /^[\w\-\s]+$/,
							message:
								"Catalog names can only contain alphanumeric characters and dashes.",
						},
						custom: {
							value: 'CheckEngineName ( "[VALUE]") ;',
							message:
								"This Catalog name has already been used, please try another.",
						},
					},
					category: "General",
				},
				{
					key: "URL",
					label: "URL",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "HTTP_METHOD",
					label: "Http Method",
					value: "POST",
					type: "select",
					options: [
						{
							display: "GET",
							value: "GET",
						},
						{
							display: "HEAD",
							value: "HEAD",
						},
						{
							display: "POST",
							value: "POST",
						},
						{
							display: "PUT",
							value: "PUT",
						},
					],
					disabled: false,
					required: true,
					category: "Credentials",
				},
				{
					key: "CONTENT_TYPE",
					label: "POST Message Body Type",
					value: "json",
					type: "select",
					options: [
						{
							display: "json",
							value: "json",
						},
						{
							display: "x-www-form-urlencoded",
							value: "x-www-form-urlencoded",
						},
					],
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "HEADERS",
					label: "Http Headers",
					value: "",
					type: "text",
					disabled: false,
					required: false,
					category: "Settings",
				},
				{
					key: "FUNCTION_PARAMETERS",
					label: "Function Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FUNCTION_REQUIRED_PARAMETERS",
					label: "Function Required Parameters",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FUNCTION_NAME",
					label: "Function Name (metadata)",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
				{
					key: "FUNCTION_DESCRIPTION",
					label: "Function Description (metadata)",
					value: "",
					type: "text",
					disabled: false,
					required: true,
					category: "Settings",
				},
			],
		},
	],
};
