import { DayOfWeek, Frequencies, Month } from './job.types';

export const timezones = [
    'Acre Time',
    'Afghanistan Time',
    'Alaska Standard Time',
    'Alma-Ata Time',
    'Amazon Time',
    'Anadyr Time',
    'Aqtau Time',
    'Aqtobe Time',
    'Arabia Standard Time',
    'Argentine Time',
    'Armenia Time',
    'Atlantic Standard Time',
    'Australian Central Standard Time (Northern Territory)',
    'Australian Central Standard Time (South Australia)',
    'Australian Central Standard Time (South Australia/New South Wales)',
    'Australian Central Western Standard Time',
    'Australian Eastern Standard Time (Macquarie)',
    'Australian Eastern Standard Time (New South Wales)',
    'Australian Eastern Standard Time (Queensland)',
    'Australian Eastern Standard Time (Tasmania)',
    'Australian Eastern Standard Time (Victoria)',
    'Australian Western Standard Time',
    'Azerbaijan Time',
    'Azores Time',
    'Bangladesh Time',
    'Bhutan Time',
    'Bolivia Time',
    'Bougainville Standard Time',
    'Brasilia Time',
    'Brunei Time',
    'Cape Verde Time',
    'Central African Time',
    'Central European Time',
    'Central Indonesia Time',
    'Central Standard Time',
    'Chamorro Standard Time',
    'Chatham Standard Time',
    'Chile Time',
    'China Standard Time',
    'Choibalsan Time',
    'Christmas Island Time',
    'Chuuk Time',
    'Cocos Islands Time',
    'Colombia Time',
    'Cook Is. Time',
    'Coordinated Universal Time',
    'Cuba Standard Time',
    'Davis Time',
    "Dumont-d'Urville Time",
    'East Indonesia Time',
    'Easter Is. Time',
    'Eastern African Time',
    'Eastern European Time',
    'Eastern Greenland Time',
    'Eastern Standard Time',
    'Ecuador Time',
    'Falkland Is. Time',
    'Fernando de Noronha Time',
    'Fiji Time',
    'French Guiana Time',
    'French Southern & Antarctic Lands Time',
    'Galapagos Time',
    'Gambier Time',
    'Georgia Time',
    'Ghana Mean Time',
    'Gilbert Is. Time',
    'GMT+01:00',
    'GMT+02:00',
    'GMT+03:00',
    'GMT+04:00',
    'GMT+05:00',
    'GMT+06:00',
    'GMT+07:00',
    'GMT+08:00',
    'GMT+09:00',
    'GMT+10:00',
    'GMT+11:00',
    'GMT+12:00',
    'GMT+13:00',
    'GMT+14:00',
    'GMT-01:00',
    'GMT-02:00',
    'GMT-03:00',
    'GMT-04:00',
    'GMT-05:00',
    'GMT-06:00',
    'GMT-07:00',
    'GMT-08:00',
    'GMT-09:00',
    'GMT-10:00',
    'GMT-11:00',
    'GMT-12:00',
    'Greenwich Mean Time',
    'Gulf Standard Time',
    'Guyana Time',
    'Hawaii Standard Time',
    'Hong Kong Time',
    'Hovd Time',
    'India Standard Time',
    'Indian Ocean Territory Time',
    'Indochina Time',
    'Iran Standard Time',
    'Irkutsk Time',
    'Israel Standard Time',
    'Japan Standard Time',
    'Kirgizstan Time',
    'Korea Standard Time',
    'Kosrae Time',
    'Krasnoyarsk Time',
    'Line Is. Time',
    'Lord Howe Standard Time',
    'Magadan Time',
    'Malaysia Time',
    'Maldives Time',
    'Marquesas Time',
    'Marshall Islands Time',
    'Mauritius Time',
    'Mawson Time',
    'Middle Europe Time',
    'Moscow Standard Time',
    'Mountain Standard Time',
    'Myanmar Time',
    'Nauru Time',
    'Nepal Time',
    'New Caledonia Time',
    'New Zealand Standard Time',
    'Newfoundland Standard Time',
    'Niue Time',
    'Norfolk Time',
    'Novosibirsk Time',
    'Omsk Time',
    'Oral Time',
    'Pacific Standard Time',
    'Pakistan Time',
    'Palau Time',
    'Papua New Guinea Time',
    'Paraguay Time',
    'Peru Time',
    'Petropavlovsk-Kamchatski Time',
    'Philippines Standard Time',
    'Phoenix Is. Time',
    'Pierre & Miquelon Standard Time',
    'Pitcairn Standard Time',
    'Pohnpei Time',
    'Qyzylorda Time',
    'Reunion Time',
    'Rothera Time',
    'Sakhalin Time',
    'Samara Time',
    'Samoa Standard Time',
    'Seychelles Time',
    'Singapore Time',
    'Solomon Is. Time',
    'South Africa Standard Time',
    'South Georgia Standard Time',
    'Srednekolymsk Time',
    'Suriname Time',
    'Syowa Time',
    'Tahiti Time',
    'Tajikistan Time',
    'Timor-Leste Time',
    'Tokelau Time',
    'Tonga Time',
    'Turkmenistan Time',
    'Tuvalu Time',
    'Ulaanbaatar Time',
    'Uruguay Time',
    'Ust-Nera Time',
    'Uzbekistan Time',
    'Vanuatu Time',
    'Venezuela Time',
    'Vladivostok Time',
    'Vostok Time',
    'Wake Time',
    'Wallis & Futuna Time',
    'West Indonesia Time',
    'West Samoa Standard Time',
    'Western African Time',
    'Western European Time',
    'Western Greenland Time',
    'Xinjiang Standard Time',
    'Yakutsk Time',
    'Yekaterinburg Time',
];

export const DaysOfWeek: Array<{
    day: DayOfWeek;
    value: 0 | 1 | 2 | 3 | 4 | 5 | 6;
}> = [
    {
        day: 'Sunday',
        value: 0,
    },
    {
        day: 'Monday',
        value: 1,
    },
    {
        day: 'Tuesday',
        value: 2,
    },
    {
        day: 'Wednesday',
        value: 3,
    },
    {
        day: 'Thursday',
        value: 4,
    },
    {
        day: 'Friday',
        value: 5,
    },
    {
        day: 'Saturday',
        value: 6,
    },
];

export const Months: Array<{
    month: Month;
    value: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
    days: 28 | 29 | 30 | 31;
}> = [
    {
        month: 'January',
        value: 1,
        days: 31,
    },
    {
        month: 'February',
        value: 2,
        days: 29,
    },
    {
        month: 'March',
        value: 3,
        days: 31,
    },
    {
        month: 'April',
        value: 4,
        days: 30,
    },
    {
        month: 'May',
        value: 5,
        days: 31,
    },
    {
        month: 'June',
        value: 6,
        days: 30,
    },
    {
        month: 'July',
        value: 7,
        days: 31,
    },
    {
        month: 'August',
        value: 8,
        days: 31,
    },
    {
        month: 'September',
        value: 9,
        days: 30,
    },
    {
        month: 'October',
        value: 10,
        days: 31,
    },
    {
        month: 'November',
        value: 11,
        days: 30,
    },
    {
        month: 'December',
        value: 12,
        days: 31,
    },
];

export const FrequencyDaily = 'Daily';
export const FrequencyWeekly = 'Weekly';
export const FrequencyMonthly = 'Monthly';
export const FrequencyYearly = 'Yearly';

export const FrequencyOptions: Frequencies[] = [
    FrequencyDaily,
    FrequencyWeekly,
    FrequencyMonthly,
    FrequencyYearly,
];
