export const mock_data = [
	{
		CONTEXT: "testing",
		CREATED_BY: "user1",
		DATE_CREATED: "2024-06-01T12:00:00Z",
		ID: "prompt1",
		INTENT: "Generate a summary of the latest news articles.",
		TITLE: "News Summary Prompt",
		VERSION: "1.0",
		CATEGORY: "Summarization",
	},
	{
		CONTEXT: "testing",
		CREATED_BY: "user2",
		DATE_CREATED: "2024-06-02T12:00:00Z",
		ID: "prompt2",
		INTENT: "Create a list of potential interview questions for a software engineering role.",
		TITLE: "Interview Questions Prompt",
		VERSION: "1.0",
		CATEGORY: "Question Generation",
	},
	{
		CONTEXT: "testing",
		CREATED_BY: "user3",
		DATE_CREATED: "2024-06-03T12:00:00Z",
		ID: "prompt3",
		INTENT: "Write a creative story based on the following keywords: 'space', 'adventure', 'friendship'.",
		TITLE: "Creative Story Prompt",
		VERSION: "1.0",
		CATEGORY: "Creative Writing",
	},
	{
		CONTEXT: "testing",
		CREATED_BY: "user4",
		DATE_CREATED: "2024-06-04T12:00:00Z",
		ID: "prompt4",
		INTENT: "Generate a list of healthy meal ideas for a week.",
		TITLE: "Healthy Meal Ideas Prompt",
		VERSION: "1.0",
		CATEGORY: "Health & Wellness",
	},
];
