import {
	Activity,
	AppWindow,
	Bell,
	Brain,
	Clock,
	Code2,
	Database,
	GitBranch,
	GitMerge,
	Globe,
	Layers,
	Mail,
	Play,
	RefreshCw,
	RotateCcw,
	Server,
	Shield,
	Shuffle,
	SlidersHorizontal,
	Wand2,
	Workflow,
	Zap,
} from "lucide-react";
import type React from "react";
import type { WorkflowNodeType } from "@/pages/workflow/workflow.types";

export const NODE_ICONS: Record<
	WorkflowNodeType,
	React.ComponentType<{ className?: string }>
> = {
	trigger: Play,
	"database-engine": Database,
	"storage-engine": Server,
	"vector-engine": Brain,
	"model-engine": Activity,
	"function-engine": Zap,
	app: AppWindow,
	"custom-pixel": Code2,
	"for-each": Layers,
	conditional: GitBranch,
	"sub-workflow": Workflow,
	"while-loop": RefreshCw,
	"try-catch": Shield,
	wait: Clock,
	"set-variable": SlidersHorizontal,
	email: Mail,
	"http-request": Globe,
	notification: Bell,
	switch: Shuffle,
	retry: RotateCcw,
	parallel: GitMerge,
	transform: Wand2,
};

export const NODE_COLORS: Record<WorkflowNodeType, string> = {
	trigger: "bg-emerald-500",
	"database-engine": "bg-blue-500",
	"storage-engine": "bg-orange-500",
	"vector-engine": "bg-purple-500",
	"model-engine": "bg-pink-500",
	"function-engine": "bg-yellow-500",
	app: "bg-cyan-500",
	"custom-pixel": "bg-slate-500",
	"for-each": "bg-indigo-500",
	conditional: "bg-amber-500",
	"sub-workflow": "bg-teal-600",
	"while-loop": "bg-violet-500",
	"try-catch": "bg-rose-500",
	wait: "bg-sky-500",
	"set-variable": "bg-lime-600",
	email: "bg-blue-600",
	"http-request": "bg-teal-500",
	notification: "bg-amber-600",
	switch: "bg-fuchsia-500",
	retry: "bg-orange-600",
	parallel: "bg-indigo-600",
	transform: "bg-emerald-600",
};

export const NODE_LABELS: Record<WorkflowNodeType, string> = {
	trigger: "Trigger",
	"database-engine": "Database",
	"storage-engine": "Storage",
	"vector-engine": "Vector",
	"model-engine": "Model",
	"function-engine": "Function",
	app: "App",
	"custom-pixel": "Custom Pixel",
	"for-each": "For Each",
	conditional: "Conditional",
	"sub-workflow": "Sub-Workflow",
	"while-loop": "While Loop",
	"try-catch": "Try / Catch",
	wait: "Wait",
	"set-variable": "Set Variable",
	email: "Send Email",
	"http-request": "HTTP Request",
	notification: "Notification",
	switch: "Switch",
	retry: "Retry",
	parallel: "Parallel",
	transform: "Transform",
};
