import type {
	FieldConfig,
	FormBuilderState,
	TableConfig,
} from "./form-builder.types";

// ---------------------------------------------------------------------------
// Shared CSS (Tailwind CDN + shadcn-inspired tokens)
// ---------------------------------------------------------------------------

function generateStylesCss(): string {
	return `/* Generated by SEMOSS Form Builder */
:root {
    --background: 0 0% 100%;
    --foreground: 240 10% 3.9%;
    --card: 0 0% 100%;
    --card-foreground: 240 10% 3.9%;
    --popover: 0 0% 100%;
    --popover-foreground: 240 10% 3.9%;
    --primary: 240 5.9% 10%;
    --primary-foreground: 0 0% 98%;
    --secondary: 240 4.8% 95.9%;
    --secondary-foreground: 240 5.9% 10%;
    --muted: 240 4.8% 95.9%;
    --muted-foreground: 240 3.8% 46.1%;
    --accent: 240 4.8% 95.9%;
    --accent-foreground: 240 5.9% 10%;
    --destructive: 0 84.2% 60.2%;
    --destructive-foreground: 0 0% 98%;
    --border: 240 5.9% 90%;
    --input: 240 5.9% 90%;
    --ring: 240 5.9% 10%;
    --radius: 0.5rem;
    --success: 142 76% 36%;
}

* { box-sizing: border-box; margin: 0; padding: 0; }

body {
    font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont,
        "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
    background: hsl(var(--background));
    color: hsl(var(--foreground));
    line-height: 1.5;
}

/* Layout */
.app-container { max-width: 1200px; margin: 0 auto; padding: 2rem; }

/* Nav */
nav {
    display: flex;
    gap: 0.5rem;
    padding: 1rem 0;
    border-bottom: 1px solid hsl(var(--border));
    margin-bottom: 2rem;
    flex-wrap: wrap;
}
nav a, nav button {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    padding: 0.5rem 1rem;
    border-radius: var(--radius);
    font-size: 0.875rem;
    font-weight: 500;
    background: hsl(var(--secondary));
    color: hsl(var(--secondary-foreground));
    text-decoration: none;
    border: none;
    cursor: pointer;
    transition: background 0.15s;
}
nav a:hover, nav button:hover { background: hsl(var(--accent)); }
nav a.active, nav button.active {
    background: hsl(var(--primary));
    color: hsl(var(--primary-foreground));
}

/* Card */
.card {
    border: 1px solid hsl(var(--border));
    border-radius: var(--radius);
    background: hsl(var(--card));
    padding: 1.5rem;
    margin-bottom: 1.5rem;
}
.card-title {
    font-size: 1.25rem;
    font-weight: 600;
    margin-bottom: 1rem;
}
.card-description {
    color: hsl(var(--muted-foreground));
    font-size: 0.875rem;
    margin-bottom: 1rem;
}

/* Form */
.form-group { margin-bottom: 1rem; }
.form-group label {
    display: block;
    font-size: 0.875rem;
    font-weight: 500;
    margin-bottom: 0.375rem;
    color: hsl(var(--foreground));
}
.form-group label .required { color: hsl(var(--destructive)); margin-left: 2px; }
.field-help {
    display: block;
    font-size: 0.75rem;
    color: hsl(var(--muted-foreground));
    margin-top: 0.25rem;
}

input[type="text"],
input[type="number"],
input[type="email"],
input[type="password"],
input[type="date"],
textarea,
select {
    width: 100%;
    padding: 0.5rem 0.75rem;
    border: 1px solid hsl(var(--input));
    border-radius: var(--radius);
    font-size: 0.875rem;
    background: hsl(var(--background));
    color: hsl(var(--foreground));
    outline: none;
    transition: border-color 0.15s, box-shadow 0.15s;
}
input:focus, textarea:focus, select:focus {
    border-color: hsl(var(--ring));
    box-shadow: 0 0 0 2px hsl(var(--ring) / 0.2);
}
textarea { min-height: 80px; resize: vertical; }

/* Checkbox / Radio row */
.check-row {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    margin-bottom: 0.25rem;
}
.check-row input { width: auto; }

/* Buttons */
.btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    padding: 0.5rem 1rem;
    border-radius: var(--radius);
    font-size: 0.875rem;
    font-weight: 500;
    cursor: pointer;
    border: 1px solid transparent;
    transition: background 0.15s, color 0.15s;
}
.btn-primary {
    background: hsl(var(--primary));
    color: hsl(var(--primary-foreground));
}
.btn-primary:hover { opacity: 0.9; }
.btn-destructive {
    background: hsl(var(--destructive));
    color: hsl(var(--destructive-foreground));
}
.btn-destructive:hover { opacity: 0.9; }
.btn-outline {
    background: transparent;
    border-color: hsl(var(--input));
    color: hsl(var(--foreground));
}
.btn-outline:hover { background: hsl(var(--accent)); }

/* Table */
.table-wrapper { overflow-x: auto; -webkit-overflow-scrolling: touch; margin-top: 1rem; }
.data-table { width: 100%; border-collapse: collapse; min-width: 600px; }
.data-table th, .data-table td {
    text-align: left;
    padding: 0.75rem;
    border-bottom: 1px solid hsl(var(--border));
    font-size: 0.875rem;
    white-space: nowrap;
}
.data-table th {
    font-weight: 600;
    background: hsl(var(--muted));
    position: sticky;
    top: 0;
    z-index: 1;
}
.data-table tbody tr:hover { background: hsl(var(--accent)); }

/* Previous value hint on update form */
.prev-value {
    display: block;
    font-size: 0.75rem;
    color: hsl(var(--muted-foreground));
    margin-top: 0.25rem;
    font-style: italic;
}

/* Action buttons in table */
.action-cell { display: flex; gap: 0.5rem; }

/* Alert / Toast */
.alert {
    padding: 0.75rem 1rem;
    border-radius: var(--radius);
    font-size: 0.875rem;
    margin-bottom: 1rem;
    display: none;
}
.alert-success {
    background: hsl(var(--success) / 0.1);
    color: hsl(var(--success));
    border: 1px solid hsl(var(--success) / 0.3);
}
.alert-error {
    background: hsl(var(--destructive) / 0.1);
    color: hsl(var(--destructive));
    border: 1px solid hsl(var(--destructive) / 0.3);
}

/* Spinner */
.spinner {
    display: none;
    width: 1.25rem;
    height: 1.25rem;
    border: 2px solid hsl(var(--muted));
    border-top-color: hsl(var(--primary));
    border-radius: 50%;
    animation: spin 0.6s linear infinite;
    margin-left: 0.5rem;
    vertical-align: middle;
}
@keyframes spin { to { transform: rotate(360deg); } }

/* Dialog overlay */
.dialog-overlay {
    display: none;
    position: fixed;
    inset: 0;
    background: rgba(0,0,0,0.5);
    z-index: 50;
    align-items: center;
    justify-content: center;
    overflow-y: auto;
    padding: 2rem 0;
}
.dialog-overlay.open { display: flex; }
.dialog-content {
    background: hsl(var(--card));
    border-radius: var(--radius);
    padding: 1.5rem;
    max-width: 420px;
    width: 90%;
    max-height: 85vh;
    overflow-y: auto;
    box-shadow: 0 10px 25px rgba(0,0,0,0.1);
}
.dialog-actions { display: flex; gap: 0.5rem; justify-content: flex-end; margin-top: 1rem; }

/* Pagination */
.pagination {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 0.75rem 0;
    font-size: 0.875rem;
    color: hsl(var(--muted-foreground));
}

/* Empty state */
.empty-state {
    text-align: center;
    padding: 3rem;
    color: hsl(var(--muted-foreground));
}

/* Toggle switch */
.toggle-switch {
    position: relative;
    display: inline-block;
    width: 44px;
    height: 24px;
    flex-shrink: 0;
}
.toggle-switch input { display: none; }
.toggle-slider {
    position: absolute;
    inset: 0;
    background: hsl(var(--muted));
    border-radius: 12px;
    cursor: pointer;
    transition: background 0.2s;
}
.toggle-slider::before {
    content: "";
    position: absolute;
    width: 18px;
    height: 18px;
    left: 3px;
    bottom: 3px;
    background: white;
    border-radius: 50%;
    transition: transform 0.2s;
}
.toggle-switch input:checked + .toggle-slider { background: hsl(var(--primary)); }
.toggle-switch input:checked + .toggle-slider::before { transform: translateX(20px); }

/* Edit dialog (wide modal) */
.dialog-content.wide { max-width: 600px; }
.dialog-content .form-group { margin-bottom: 0.75rem; }
`;
}

// ---------------------------------------------------------------------------
// Shared JS (SEMOSS Pixel API helpers)
// ---------------------------------------------------------------------------

function generateAppJs(state: FormBuilderState): string {
	const { databaseId } = state;
	return `// Generated by SEMOSS Form Builder
const DATABASE_ID = "${databaseId}";

// ---- SEMOSS API helpers ----
function getBaseUrl() {
    // Detect the SEMOSS module base from the current page URL
    // portals are served at: {MODULE}/public_home/{appId}/portals/
    const path = window.location.pathname;
    const idx = path.indexOf("/public_home/");
    if (idx !== -1) return path.substring(0, idx);
    // Fallback: assume /Monolith
    return "/Monolith";
}

let _insightId = null;

async function getInsightId() {
    if (_insightId) return _insightId;
    // Bootstrap a server-side insight so all queries share context
    const base = getBaseUrl();
    const url = base + "/api/engine/runPixel";
    const body = new URLSearchParams();
    body.append("expression", "GetUserInfo();");
    body.append("insightId", "new");
    const response = await fetch(url, {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: body,
    });
    const json = await response.json();
    if (json.insightID) {
        _insightId = json.insightID;
    }
    return _insightId;
}

async function runPixel(pixel) {
    const base = getBaseUrl();
    const url = base + "/api/engine/runPixel";
    const insightId = await getInsightId();
    const body = new URLSearchParams();
    body.append("expression", pixel);
    if (insightId) body.append("insightId", insightId);
    const response = await fetch(url, {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: body,
    });
    const json = await response.json();
    if (json.pixelReturn && json.pixelReturn.length > 0) {
        const ret = json.pixelReturn[0];
        if (ret.operationType && ret.operationType.toString().includes("ERROR")) {
            throw new Error(ret.output || "Pixel query failed");
        }
        return ret.output;
    }
    return json;
}

// Build encode tags via concatenation so the literal </encode> never
// appears in the source file (which would break SaveAsset's own <encode> wrapper).
var ENC_OPEN = '<' + 'encode>';
var ENC_CLOSE = '<' + '/encode>';

async function queryDatabase(sql) {
    var pixel = 'SqlQuery(database=["' + DATABASE_ID + '"], query=["' + ENC_OPEN + sql + ENC_CLOSE + '"]);';
    return runPixel(pixel);
}

async function commitDatabase(sql) {
    var pixel = 'SqlQuery(database=["' + DATABASE_ID + '"], query=["' + ENC_OPEN + sql + ENC_CLOSE + '"], commit=[true]);';
    return runPixel(pixel);
}

// ---- Alert helpers ----
function showAlert(id, message, type) {
    const el = document.getElementById(id);
    if (!el) return;
    el.textContent = message;
    el.className = "alert alert-" + type;
    el.style.display = "block";
    setTimeout(function() { el.style.display = "none"; }, 4000);
}

// ---- Navigation ----
function navigateTo(page) {
    window.location.href = page;
}

// ---- Escape HTML ----
function escapeHtml(str) {
    if (str == null) return "";
    return String(str).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
}

// ---- Parse SEMOSS SqlQuery result into array of objects ----
function parseResult(result) {
    if (!result) { console.warn("[FormApp] parseResult: empty result"); return []; }
    if (Array.isArray(result)) return result;

    // Normalise: find headers + values from all known SEMOSS response shapes
    var headers = null;
    var values  = null;

    // Shape 1 (standard): { data: { headers:[], values:[][] } }
    if (result.data && result.data.headers && result.data.values) {
        headers = result.data.headers;
        values  = result.data.values;
    }
    // Shape 2 (flat): { headers:[], values:[][] }
    else if (result.headers && result.values) {
        headers = result.headers;
        values  = result.values;
    }
    // Shape 3 (headerInfo at top, data.values): { data: { values:[][] }, headerInfo:[{alias}] }
    else if (result.data && result.data.values && result.headerInfo) {
        headers = result.headerInfo.map(function(h) { return h.alias || h.header; });
        values  = result.data.values;
    }
    // Shape 4 (headerInfo nested inside data): { data: { values:[][], headerInfo:[{alias}] } }
    else if (result.data && result.data.values && result.data.headerInfo) {
        headers = result.data.headerInfo.map(function(h) { return h.alias || h.header; });
        values  = result.data.values;
    }

    // Handle column-oriented data: values is an object { colName: [...] }
    if (headers && values && !Array.isArray(values) && typeof values === "object") {
        var rowCount = 0;
        headers.forEach(function(h) {
            if (Array.isArray(values[h]) && values[h].length > rowCount) rowCount = values[h].length;
        });
        var rows = [];
        for (var r = 0; r < rowCount; r++) {
            var obj = {};
            headers.forEach(function(h) { obj[h] = Array.isArray(values[h]) ? values[h][r] : null; });
            rows.push(obj);
        }
        return rows;
    }

    if (headers && Array.isArray(values)) {
        return values.map(function(row) {
            var obj = {};
            headers.forEach(function(h, i) { obj[h] = row[i]; });
            return obj;
        });
    }

    // Shape 5 (plain object with column arrays, no headers key)
    if (!Array.isArray(result) && typeof result === "object" && !result.data) {
        var keys = Object.keys(result);
        if (keys.length > 0 && Array.isArray(result[keys[0]])) {
            var count = result[keys[0]].length;
            var out = [];
            for (var i = 0; i < count; i++) {
                var o = {};
                keys.forEach(function(k) { o[k] = Array.isArray(result[k]) ? result[k][i] : null; });
                out.push(o);
            }
            return out;
        }
    }

    console.warn("[FormApp] parseResult: unrecognised shape", JSON.stringify(result).substring(0, 500));
    return [];
}

// ---- Case-insensitive row value getter (SEMOSS headers may differ in case) ----
function rowGet(row, col) {
    if (row[col] !== undefined) return row[col];
    var lc = col.toLowerCase();
    var keys = Object.keys(row);
    for (var i = 0; i < keys.length; i++) {
        if (keys[i].toLowerCase() === lc) return row[keys[i]];
    }
    return null;
}
`;
}

// ---------------------------------------------------------------------------
// Per-table page generators
// ---------------------------------------------------------------------------

/** Determine which columns to show when browsing a table's records. */
function getReadableColumns(table: TableConfig): FieldConfig[] {
	// Prefer explicitly configured read fields
	if (table.fields.read && table.fields.read.length > 0) {
		return table.fields.read.filter((f) => f.visible);
	}
	// Fall back to other operation fields
	const fallbackOps: Array<keyof typeof table.fields> = [
		"update",
		"delete",
		"create",
	];
	for (const op of fallbackOps) {
		const f = table.fields[op];
		if (f && f.length > 0) {
			return f.filter((field) => field.visible);
		}
	}
	// Last resort: synthesize from raw table columns
	return table.columns.map((col, i) => ({
		columnName: col.column,
		label: col.column,
		widgetType: "text" as const,
		placeholder: "",
		required: false,
		visible: true,
		order: i,
		dbType: col.type,
	}));
}

function fieldToInputHtml(field: FieldConfig, idPrefix: string): string {
	const id = `${idPrefix}-${field.columnName}`;
	const req = field.required ? '<span class="required">*</span>' : "";
	const helpHtml = field.helpText
		? `\n    <span class="field-help">${field.helpText}</span>`
		: "";

	switch (field.widgetType) {
		case "textarea":
			return `<div class="form-group">
    <label for="${id}">${field.label}${req}</label>
    <textarea id="${id}" name="${field.columnName}" placeholder="${field.placeholder}"${field.required ? " required" : ""}>${field.defaultValue || ""}</textarea>${helpHtml}
</div>`;

		case "select": {
			const opts = (field.options || [])
				.map((o) => {
					const sel = o === field.defaultValue ? " selected" : "";
					return `<option value="${o}"${sel}>${o}</option>`;
				})
				.join("\n        ");
			return `<div class="form-group">
    <label for="${id}">${field.label}${req}</label>
    <select id="${id}" name="${field.columnName}"${field.required ? " required" : ""}>
        <option value="">Select...</option>
        ${opts}
    </select>${helpHtml}
</div>`;
		}

		case "checkbox": {
			const checkedVal = field.checkedValue || "1";
			const checked =
				field.defaultValue === "1" || field.defaultValue === "true"
					? " checked"
					: "";
			return `<div class="form-group">
    <div class="check-row">
        <input type="checkbox" id="${id}" name="${field.columnName}" value="${checkedVal}"${checked}>
        <label for="${id}">${field.label}${req}</label>
    </div>${helpHtml}
</div>`;
		}

		case "radio":
			return `<div class="form-group">
    <label>${field.label}${req}</label>
    ${(field.options || ["Yes", "No"])
		.map(
			(o, i) =>
				`<div class="check-row">
        <input type="radio" id="${id}-${i}" name="${field.columnName}" value="${o}"${o === field.defaultValue ? " checked" : ""}${i === 0 && field.required ? " required" : ""}>
        <label for="${id}-${i}">${o}</label>
    </div>`,
		)
		.join("\n    ")}${helpHtml}
</div>`;

		case "toggle": {
			const checkedVal = field.checkedValue || "1";
			const checked =
				field.defaultValue === "1" || field.defaultValue === "true"
					? " checked"
					: "";
			return `<div class="form-group">
    <div class="check-row">
        <label class="toggle-switch">
            <input type="checkbox" id="${id}" name="${field.columnName}" value="${checkedVal}"${checked}>
            <span class="toggle-slider"></span>
        </label>
        <label for="${id}">${field.label}${req}</label>
    </div>${helpHtml}
</div>`;
		}

		default: {
			const val = field.defaultValue
				? ` value="${field.defaultValue}"`
				: "";
			return `<div class="form-group">
    <label for="${id}">${field.label}${req}</label>
    <input type="${field.widgetType}" id="${id}" name="${field.columnName}" placeholder="${field.placeholder}"${val}${field.required ? " required" : ""}>${helpHtml}
</div>`;
		}
	}
}

function generateCreatePage(table: TableConfig): string {
	const fields = table.fields.create.filter((f) => f.visible);
	const formFields = fields
		.sort((a, b) => a.order - b.order)
		.map((f) => fieldToInputHtml(f, "create"))
		.join("\n");

	const collectValues = fields
		.map((f) => {
			if (f.widgetType === "checkbox" || f.widgetType === "toggle") {
				const cv = JSON.stringify(f.checkedValue || "1");
				const uv = JSON.stringify(f.uncheckedValue || "0");
				return `    const v_${f.columnName} = document.getElementById("create-${f.columnName}").checked ? ${cv} : ${uv};`;
			}
			if (f.widgetType === "radio") {
				return `    const v_${f.columnName} = (document.querySelector('input[name="${f.columnName}"]:checked') || {}).value || "";`;
			}
			return `    const v_${f.columnName} = document.getElementById("create-${f.columnName}").value;`;
		})
		.join("\n");

	const buildSqlParts = fields
		.map((f) => {
			if (f.widgetType === "number") {
				return `    vals.push(v_${f.columnName} !== "" && v_${f.columnName} !== null ? v_${f.columnName} : "NULL");`;
			}
			if (f.widgetType === "checkbox" || f.widgetType === "toggle") {
				return `    vals.push(!isNaN(v_${f.columnName}) ? v_${f.columnName} : "'" + String(v_${f.columnName}).replace(/'/g, "''") + "'");`;
			}
			return `    vals.push("'" + String(v_${f.columnName}).replace(/'/g, "''") + "'");`;
		})
		.join("\n");

	const sqlColumns = fields.map((f) => f.columnName).join(", ");

	return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create ${table.table}</title>
    <link rel="stylesheet" href="styles.css">
    <script src="app.js"></script>
</head>
<body>
<div class="app-container">
    <nav id="main-nav"></nav>

    <div class="card">
        <div class="card-title">Create ${table.table}</div>
        <div class="card-description">Add a new record to the ${table.table} table.</div>

        <div id="alert" class="alert"></div>

        <form id="create-form" onsubmit="handleCreate(event)">
${formFields}
            <button type="submit" class="btn btn-primary">
                Create Record <span id="spinner" class="spinner"></span>
            </button>
        </form>
    </div>
</div>

<script src="nav.js"></script>
<script>
async function handleCreate(e) {
    e.preventDefault();
    var spinner = document.getElementById("spinner");
    spinner.style.display = "inline-block";

${collectValues}

    var vals = [];
${buildSqlParts}

    try {
        var sql = "INSERT INTO ${table.table} (${sqlColumns}) VALUES (" + vals.join(", ") + ")";
        await commitDatabase(sql);
        showAlert("alert", "Record created successfully!", "success");
        document.getElementById("create-form").reset();
    } catch (err) {
        showAlert("alert", "Error: " + err.message, "error");
    } finally {
        spinner.style.display = "none";
    }
}
</script>
</body>
</html>
`;
}

// ---------------------------------------------------------------------------
// Dedicated Update page (lookup-based)
// ---------------------------------------------------------------------------

function generateUpdatePage(table: TableConfig): string {
	const lookupField = table.lookupField || table.columns[0]?.column || "id";
	const allColumns = table.columns.map((c) => c.column);

	const updateFields = (
		table.fields.update && table.fields.update.length > 0
			? table.fields.update
			: getReadableColumns(table)
	)
		.filter((f) => f.visible)
		.sort((a, b) => a.order - b.order);

	const populateFields = updateFields
		.map((f) => {
			const prevHint = `        var prev_${f.columnName} = document.getElementById("prev-${f.columnName}"); if (prev_${f.columnName}) prev_${f.columnName}.textContent = "Previous: " + (rowGet(row, "${f.columnName}") != null ? rowGet(row, "${f.columnName}") : "(empty)");`;
			if (f.widgetType === "checkbox" || f.widgetType === "toggle") {
				const cv = JSON.stringify(f.checkedValue || "1");
				return `        document.getElementById("edit-${f.columnName}").checked = String(rowGet(row, "${f.columnName}")) === ${cv};\n${prevHint}`;
			}
			if (f.widgetType === "select") {
				return `        document.getElementById("edit-${f.columnName}").value = rowGet(row, "${f.columnName}") != null ? rowGet(row, "${f.columnName}") : "";\n${prevHint}`;
			}
			if (f.widgetType === "radio") {
				return `        var radioVal_${f.columnName} = rowGet(row, "${f.columnName}") != null ? String(rowGet(row, "${f.columnName}")) : "";
        document.querySelectorAll('input[name="${f.columnName}"]').forEach(function(r) { r.checked = r.value === radioVal_${f.columnName}; });\n${prevHint}`;
			}
			return `        document.getElementById("edit-${f.columnName}").value = rowGet(row, "${f.columnName}") != null ? rowGet(row, "${f.columnName}") : "";\n${prevHint}`;
		})
		.join("\n");

	// Augmented form fields with previous-value hints injected after each form-group
	const formFieldsWithPrev = updateFields
		.map(
			(f) =>
				`${fieldToInputHtml(f, "edit")}\n            <span class="prev-value" id="prev-${f.columnName}"></span>`,
		)
		.join("\n            ");

	const collectValues = updateFields
		.map((f) => {
			if (f.widgetType === "checkbox" || f.widgetType === "toggle") {
				const cv = JSON.stringify(f.checkedValue || "1");
				const uv = JSON.stringify(f.uncheckedValue || "0");
				return `    var v_${f.columnName} = document.getElementById("edit-${f.columnName}").checked ? ${cv} : ${uv};`;
			}
			if (f.widgetType === "radio") {
				return `    var v_${f.columnName} = (document.querySelector('input[name="${f.columnName}"]:checked') || {}).value || "";`;
			}
			return `    var v_${f.columnName} = document.getElementById("edit-${f.columnName}").value;`;
		})
		.join("\n");

	const buildSetParts = updateFields
		.map((f) => {
			if (f.widgetType === "number") {
				return `    setParts.push("${f.columnName} = " + (v_${f.columnName} !== "" && v_${f.columnName} !== null ? v_${f.columnName} : "NULL"));`;
			}
			if (f.widgetType === "checkbox" || f.widgetType === "toggle") {
				return `    setParts.push("${f.columnName} = " + (!isNaN(v_${f.columnName}) ? v_${f.columnName} : "'" + String(v_${f.columnName}).replace(/'/g, "''") + "'"));`;
			}
			return `    setParts.push("${f.columnName} = '" + String(v_${f.columnName}).replace(/'/g, "''") + "'");`;
		})
		.join("\n");

	return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update ${table.table}</title>
    <link rel="stylesheet" href="styles.css">
    <script src="app.js"></script>
</head>
<body>
<div class="app-container">
    <nav id="main-nav"></nav>

    <div class="card">
        <div class="card-title">Update ${table.table}</div>
        <div class="card-description">Search for a record, review its current values, and make changes.</div>

        <div id="alert" class="alert"></div>

        <!-- Record lookup -->
        <div class="form-group">
            <label for="lookup-search">Find Record by ${lookupField}</label>
            <input type="text" id="lookup-search" placeholder="Type to search…" autocomplete="off">
        </div>
        <div class="form-group">
            <select id="record-select" size="6" style="width:100%;font-size:0.875rem;">
                <option value="" disabled selected>Loading records…</option>
            </select>
        </div>
    </div>

    <!-- Edit form (hidden until a record is selected) -->
    <div class="card" id="edit-card" style="display:none;">
        <div class="card-title">Edit Record</div>
        <div id="edit-alert" class="alert"></div>
        <form id="edit-form" onsubmit="handleUpdate(event)">
            ${formFieldsWithPrev}
            <div style="display:flex;gap:0.5rem;margin-top:1rem;">
                <button type="submit" class="btn btn-primary">
                    Save Changes <span id="edit-spinner" class="spinner"></span>
                </button>
                <button type="button" class="btn btn-outline" onclick="clearSelection()">Cancel</button>
            </div>
        </form>
    </div>
</div>

<script src="nav.js"></script>
<script>
var allData = [];
var selectedRow = null;
var LOOKUP_FIELD = "${lookupField}";
var ALL_COLUMNS = ${JSON.stringify(allColumns)};

async function loadRecords() {
    try {
        var sql = "SELECT ${allColumns.join(", ")} FROM ${table.table}";
        var result = await queryDatabase(sql);
        allData = parseResult(result);
        renderSelect();
        // Auto-select if query param provided
        var params = new URLSearchParams(window.location.search);
        var preselect = params.get("lookup");
        if (preselect) {
            var idx = allData.findIndex(function(r) { return String(rowGet(r, LOOKUP_FIELD)) === preselect; });
            if (idx !== -1) selectRecord(idx);
        }
    } catch (err) {
        showAlert("alert", "Error loading records: " + err.message, "error");
    }
}

function renderSelect(filter) {
    var sel = document.getElementById("record-select");
    var lc = (filter || "").toLowerCase();
    var html = "";
    allData.forEach(function(row, idx) {
        var label = rowGet(row, LOOKUP_FIELD) != null ? String(rowGet(row, LOOKUP_FIELD)) : "(empty)";
        if (lc && label.toLowerCase().indexOf(lc) === -1) return;
        var selected = selectedRow === idx ? " selected" : "";
        html += '<option value="' + idx + '"' + selected + '>' + escapeHtml(label) + '</option>';
    });
    if (!html) html = '<option value="" disabled>No matching records</option>';
    sel.innerHTML = html;
}

document.getElementById("lookup-search").addEventListener("input", function() {
    renderSelect(this.value);
});

document.getElementById("record-select").addEventListener("change", function() {
    var idx = parseInt(this.value, 10);
    if (!isNaN(idx)) selectRecord(idx);
});

function selectRecord(idx) {
    selectedRow = idx;
    var row = allData[idx];
    if (!row) return;
${populateFields}
    document.getElementById("edit-card").style.display = "";
    document.getElementById("edit-card").scrollIntoView({ behavior: "smooth", block: "start" });
}

function clearSelection() {
    selectedRow = null;
    document.getElementById("edit-card").style.display = "none";
    document.getElementById("edit-form").reset();
    document.getElementById("record-select").selectedIndex = -1;
    // Clear previous-value hints
    document.querySelectorAll(".prev-value").forEach(function(el) { el.textContent = ""; });
}

async function handleUpdate(e) {
    e.preventDefault();
    if (selectedRow == null) return;
    var spinner = document.getElementById("edit-spinner");
    spinner.style.display = "inline-block";

    var originalRow = allData[selectedRow];

${collectValues}

    var setParts = [];
${buildSetParts}

    var conditions = ALL_COLUMNS.map(function(c) {
        var val = rowGet(originalRow, c);
        if (val == null) return c + " IS NULL";
        if (typeof val === "number") return c + " = " + val;
        return c + " = '" + String(val).replace(/'/g, "''") + "'";
    }).join(" AND ");

    try {
        var sql = "UPDATE ${table.table} SET " + setParts.join(", ") + " WHERE " + conditions;
        await commitDatabase(sql);
        showAlert("alert", "Record updated successfully!", "success");
        clearSelection();
        loadRecords();
    } catch (err) {
        showAlert("edit-alert", "Error: " + err.message, "error");
    } finally {
        spinner.style.display = "none";
    }
}

loadRecords();
</script>
</body>
</html>
`;
}

function generateReadPage(table: TableConfig): string {
	const columns = getReadableColumns(table).sort((a, b) => a.order - b.order);

	const thCells = columns
		.map((f) => `<th>${f.label}</th>`)
		.join("\n            ");
	const hasUpdate = table.operations.includes("update");
	const hasDelete = table.operations.includes("delete");
	const hasActions = hasUpdate || hasDelete;
	const colCount = columns.length + (hasActions ? 1 : 0);

	// Lookup field for linking to the dedicated update page
	const lookupField = table.lookupField || table.columns[0]?.column || "id";
	const tableLower = table.table.toLowerCase();

	return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${table.table} Records</title>
    <link rel="stylesheet" href="styles.css">
    <script src="app.js"></script>
</head>
<body>
<div class="app-container">
    <nav id="main-nav"></nav>

    <div class="card">
        <div class="card-title">${table.table} Records</div>
        <div class="card-description">Browse and manage records in the ${table.table} table.</div>

        <div id="alert" class="alert"></div>

        <div style="display:flex;gap:0.5rem;margin-bottom:1rem;">
            <input type="text" id="search-input" placeholder="Search..." style="max-width:300px;">
            <button class="btn btn-outline" onclick="loadData()">Refresh</button>
        </div>

        <div class="table-wrapper">
        <table class="data-table">
            <thead>
                <tr>
                    ${thCells}${hasActions ? "\n                    <th>Actions</th>" : ""}
                </tr>
            </thead>
            <tbody id="table-body">
                <tr><td colspan="${colCount}" class="empty-state">Loading...</td></tr>
            </tbody>
        </table>
        </div>

        <div class="pagination">
            <span id="page-info"></span>
            <div style="display:flex;gap:0.5rem;">
                <button class="btn btn-outline" id="prev-btn" onclick="prevPage()" disabled>Previous</button>
                <button class="btn btn-outline" id="next-btn" onclick="nextPage()">Next</button>
            </div>
        </div>
    </div>
</div>

${
	hasDelete
		? `<div class="dialog-overlay" id="delete-dialog" onclick="if(event.target===this)closeDeleteDialog()">
    <div class="dialog-content">
        <div class="card-title">Confirm Delete</div>
        <p>Are you sure you want to delete this record? This action cannot be undone.</p>
        <div class="dialog-actions">
            <button class="btn btn-outline" onclick="closeDeleteDialog()">Cancel</button>
            <button class="btn btn-destructive" id="confirm-delete-btn">Delete</button>
        </div>
    </div>
</div>`
		: ""
}

<script src="nav.js"></script>
<script>
var PAGE_SIZE = 20;
var currentPage = 0;
var allData = [];

var COLUMNS = ${JSON.stringify(columns.map((c) => c.columnName))};

async function loadData() {
    try {
        var sql = "SELECT ${columns.map((c) => c.columnName).join(", ")} FROM ${table.table}";
        var result = await queryDatabase(sql);
        allData = parseResult(result);
        currentPage = 0;
        renderTable();
    } catch (err) {
        showAlert("alert", "Error loading data: " + err.message, "error");
    }
}

function renderTable() {
    var search = (document.getElementById("search-input").value || "").toLowerCase();
    var filtered = allData;
    if (search) {
        filtered = allData.filter(function(row) {
            return COLUMNS.some(function(c) { return String(rowGet(row, c) != null ? rowGet(row, c) : "").toLowerCase().indexOf(search) !== -1; });
        });
    }

    var start = currentPage * PAGE_SIZE;
    var pageData = filtered.slice(start, start + PAGE_SIZE);
    var tbody = document.getElementById("table-body");

    if (pageData.length === 0) {
        tbody.innerHTML = '<tr><td colspan="${colCount}" class="empty-state">No records found.</td></tr>';
    } else {
        tbody.innerHTML = pageData.map(function(row, idx) {
            var cells = COLUMNS.map(function(c) { return "<td>" + escapeHtml(rowGet(row, c)) + "</td>"; }).join("");
            ${
				hasActions
					? `var actions = '<td class="action-cell">'
                ${hasUpdate ? `+ '<a class=\\"btn btn-outline\\" href=\\"update-${tableLower}.html?lookup=' + encodeURIComponent(rowGet(row, '${lookupField}')) + '\\">Edit</a>'` : ""}
                ${hasDelete ? `+ '<button class=\\"btn btn-destructive\\" onclick=\\"openDeleteDialog(' + (start + idx) + ')\\">Delete</button>'` : ""}
                + '</td>';`
					: "var actions = '';"
			}
            return "<tr>" + cells + actions + "</tr>";
        }).join("");
    }

    document.getElementById("page-info").textContent = "Showing " + (filtered.length ? (start + 1) : 0) + "-" + Math.min(start + PAGE_SIZE, filtered.length) + " of " + filtered.length;
    document.getElementById("prev-btn").disabled = currentPage === 0;
    document.getElementById("next-btn").disabled = start + PAGE_SIZE >= filtered.length;
}

function prevPage() { currentPage--; renderTable(); }
function nextPage() { currentPage++; renderTable(); }

document.getElementById("search-input").addEventListener("input", function() {
    currentPage = 0;
    renderTable();
});

${
	hasDelete
		? `
var deleteIdx = null;
function openDeleteDialog(idx) {
    deleteIdx = idx;
    document.getElementById("delete-dialog").classList.add("open");
}
function closeDeleteDialog() {
    document.getElementById("delete-dialog").classList.remove("open");
    deleteIdx = null;
}
document.getElementById("confirm-delete-btn").addEventListener("click", async function() {
    if (deleteIdx == null) return;
    var row = allData[deleteIdx];
    var conditions = COLUMNS.map(function(c) {
        var val = rowGet(row, c);
        if (val == null) return c + " IS NULL";
        if (typeof val === "number") return c + " = " + val;
        return c + " = '" + String(val).replace(/'/g, "''") + "'";
    }).join(" AND ");
    try {
        await commitDatabase("DELETE FROM ${table.table} WHERE " + conditions);
        showAlert("alert", "Record deleted.", "success");
        closeDeleteDialog();
        loadData();
    } catch (err) {
        showAlert("alert", "Error: " + err.message, "error");
    }
});
`
		: ""
}

loadData();
</script>
</body>
</html>
`;
}

// ---------------------------------------------------------------------------
// Nav & Index generators
// ---------------------------------------------------------------------------

/** Check whether a table needs a browse / listing page. */
function needsBrowsePage(table: TableConfig): boolean {
	return (
		table.operations.includes("read") ||
		table.operations.includes("update") ||
		table.operations.includes("delete")
	);
}

function generateNavJs(state: FormBuilderState): string {
	const links: { label: string; href: string }[] = [
		{ label: "Home", href: "index.html" },
	];

	for (const table of state.tables) {
		// Show a "Create" link if the table has create
		if (table.operations.includes("create")) {
			links.push({
				label: `+ New ${table.table}`,
				href: `create-${table.table.toLowerCase()}.html`,
			});
		}
		// Show a "Records" link if the table has read, update, or delete
		if (needsBrowsePage(table)) {
			links.push({
				label: `${table.table} Records`,
				href: `read-${table.table.toLowerCase()}.html`,
			});
		}
		// Show a dedicated "Edit" link if the table has update
		if (table.operations.includes("update")) {
			links.push({
				label: `Edit ${table.table}`,
				href: `update-${table.table.toLowerCase()}.html`,
			});
		}
	}

	return `// Generated navigation
(function() {
    var NAV_LINKS = ${JSON.stringify(links, null, 4)};
    var nav = document.getElementById("main-nav");
    if (!nav) return;
    var current = window.location.pathname.split("/").pop() || "index.html";
    nav.innerHTML = NAV_LINKS.map(function(link) {
        var active = current === link.href ? ' class="active"' : "";
        return '<a href="' + link.href + '"' + active + '>' + link.label + '</a>';
    }).join("");
})();
`;
}

function generateIndexHtml(state: FormBuilderState): string {
	const tableCards = state.tables
		.map((t) => {
			const buttons: string[] = [];

			if (t.operations.includes("create")) {
				buttons.push(
					`<a href="create-${t.table.toLowerCase()}.html" class="btn btn-outline">Create New</a>`,
				);
			}
			if (needsBrowsePage(t)) {
				buttons.push(
					`<a href="read-${t.table.toLowerCase()}.html" class="btn btn-outline">View Records</a>`,
				);
			}
			if (t.operations.includes("update")) {
				buttons.push(
					`<a href="update-${t.table.toLowerCase()}.html" class="btn btn-outline">Edit Records</a>`,
				);
			}

			return `
            <div class="card">
                <div class="card-title">${t.table}</div>
                <div class="card-description">${t.columns.length} columns · ${t.operations.join(", ").toUpperCase()} enabled</div>
                <div style="display:flex;gap:0.5rem;flex-wrap:wrap;">
                    ${buttons.join("\n                    ")}
                </div>
            </div>`;
		})
		.join("\n");

	return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${state.appName}</title>
    <link rel="stylesheet" href="styles.css">
    <script src="app.js"></script>
</head>
<body>
<div class="app-container">
    <nav id="main-nav"></nav>

    <div class="card">
        <div class="card-title">${state.appName}</div>
        <div class="card-description">${state.appDescription || "Manage your data with ease."}</div>
    </div>

    <div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:1rem;">
        ${tableCards}
    </div>
</div>

<script src="nav.js"></script>
</body>
</html>
`;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface GeneratedFile {
	/** Relative path under portals/ */
	path: string;
	/** File content */
	content: string;
}

/**
 * Generate all files for the CODE app from the form builder state.
 */
export function generateFormAppFiles(state: FormBuilderState): GeneratedFile[] {
	const files: GeneratedFile[] = [
		{ path: "styles.css", content: generateStylesCss() },
		{ path: "app.js", content: generateAppJs(state) },
		{ path: "nav.js", content: generateNavJs(state) },
		{ path: "index.html", content: generateIndexHtml(state) },
	];

	for (const table of state.tables) {
		const ops = new Set(table.operations);

		if (ops.has("create")) {
			files.push({
				path: `create-${table.table.toLowerCase()}.html`,
				content: generateCreatePage(table),
			});
		}

		if (ops.has("update")) {
			files.push({
				path: `update-${table.table.toLowerCase()}.html`,
				content: generateUpdatePage(table),
			});
		}

		// Generate a single read/browse page that also handles delete via modal
		if (needsBrowsePage(table)) {
			files.push({
				path: `read-${table.table.toLowerCase()}.html`,
				content: generateReadPage(table),
			});
		}
	}

	return files;
}
