export const FENCED_HTML_RE = /```html[ \t]*\n([\s\S]*?)(?:\n```|$)/i;

export const KNOWN_SHIKI_LANGS = new Set([
	"c",
	"r",
	"go",
	"js",
	"ts",
	"py",
	"rb",
	"rs",
	"kt",
	"sh",
	"cs",
	"md",
	"html",
	"css",
	"javascript",
	"typescript",
	"python",
	"ruby",
	"rust",
	"kotlin",
	"swift",
	"java",
	"scala",
	"bash",
	"zsh",
	"fish",
	"sql",
	"yaml",
	"yml",
	"json",
	"xml",
	"toml",
	"ini",
	"markdown",
	"dockerfile",
	"graphql",
	"svelte",
	"vue",
	"jsx",
	"tsx",
	"scss",
	"less",
	"sass",
	"php",
	"perl",
	"lua",
	"haskell",
	"erlang",
	"elixir",
	"clojure",
	"cpp",
	"csharp",
	"objc",
	"groovy",
	"powershell",
	"batch",
	"nginx",
	"terraform",
	"hcl",
	"proto",
	"protobuf",
	"txt",
	"text",
	"plaintext",
]);

export const CODE_LANG_EXT: Record<string, string> = {
	javascript: "js",
	typescript: "ts",
	python: "py",
	ruby: "rb",
	rust: "rs",
	kotlin: "kt",
	swift: "swift",
	csharp: "cs",
	cpp: "cpp",
	bash: "sh",
	zsh: "sh",
	fish: "sh",
	sh: "sh",
	powershell: "ps1",
	sql: "sql",
	html: "html",
	css: "css",
	scss: "scss",
	less: "less",
	sass: "scss",
	json: "json",
	yaml: "yaml",
	yml: "yml",
	xml: "xml",
	toml: "toml",
	markdown: "md",
	go: "go",
	java: "java",
	php: "php",
	lua: "lua",
	perl: "pl",
	haskell: "hs",
	elixir: "ex",
	erlang: "erl",
	clojure: "clj",
	scala: "scala",
	groovy: "groovy",
	r: "r",
	c: "c",
	js: "js",
	ts: "ts",
	py: "py",
	rb: "rb",
	rs: "rs",
	kt: "kt",
	cs: "cs",
	md: "md",
	pixel: "pixel",
};

export const CODE_LANG_LABELS: Record<string, string> = {
	javascript: "JavaScript",
	typescript: "TypeScript",
	python: "Python",
	ruby: "Ruby",
	rust: "Rust",
	kotlin: "Kotlin",
	swift: "Swift",
	csharp: "C#",
	cpp: "C++",
	bash: "Bash",
	zsh: "Zsh",
	fish: "Fish",
	powershell: "PowerShell",
	sql: "SQL",
	html: "HTML",
	css: "CSS",
	scss: "SCSS",
	less: "Less",
	sass: "Sass",
	json: "JSON",
	yaml: "YAML",
	yml: "YAML",
	xml: "XML",
	toml: "TOML",
	markdown: "Markdown",
	dockerfile: "Dockerfile",
	graphql: "GraphQL",
	go: "Go",
	java: "Java",
	php: "PHP",
	lua: "Lua",
	perl: "Perl",
	haskell: "Haskell",
	elixir: "Elixir",
	erlang: "Erlang",
	clojure: "Clojure",
	scala: "Scala",
	groovy: "Groovy",
	svelte: "Svelte",
	vue: "Vue",
	jsx: "JSX",
	tsx: "TSX",
	nginx: "Nginx",
	terraform: "Terraform",
	hcl: "HCL",
	protobuf: "Protobuf",
	proto: "Protobuf",
	plaintext: "Plain Text",
	text: "Text",
	txt: "Text",
	js: "JavaScript",
	ts: "TypeScript",
	py: "Python",
	rb: "Ruby",
	rs: "Rust",
	kt: "Kotlin",
	cs: "C#",
	sh: "Shell",
	md: "Markdown",
	r: "R",
	c: "C",
	pixel: "Pixel",
};

export const createHtmlResponseFilePath = (): string => {
	return `save-html-response-${Date.now()}.html`;
};

export const createCodeFilePath = (lang: string): string => {
	const ext = CODE_LANG_EXT[lang] ?? lang;
	return `save-code-response-${Date.now()}.${ext}`;
};
