/* eslint-disable prettier/prettier */
import {
	AlertTriangle,
	BarChart2,
	Bell,
	Bookmark,
	CalendarDays,
	Camera,
	CircleAlert,
	CirclePlus,
	CircleUser,
	CircleX,
	Clock,
	Cloud,
	Copy,
	Download,
	FileUp,
	Folder,
	Heart,
	Home,
	List,
	type LucideIcon,
	Mail,
	Menu,
	MessageSquare,
	Pencil,
	Save,
	Search,
	Send,
	Settings,
	Share2,
	ShoppingCart,
	Smartphone,
	Smile,
	SquarePlus,
	ThumbsDown,
	ThumbsUp,
	Trash2,
	Volume2,
	VolumeX,
} from "lucide-react";

export const iconMap: { [key: string]: LucideIcon } = {
	Icon: Smile,
	Face: Smile,
	Home: Home,
	"Add Box": SquarePlus,
	"Add Circle": CirclePlus,
	Upload: FileUp,
	Save: Save,
	Bookmark: Bookmark,
	Heart: Heart,
	Delete: Trash2,
	Folder: Folder,
	Copy: Copy,
	Menu: Menu,
	List: List,
	Settings: Settings,
	Search: Search,
	Edit: Pencil,
	Share: Share2,
	Download: Download,
	Send: Send,
	Email: Mail,
	Comment: MessageSquare,
	Calendar: CalendarDays,
	Clock: Clock,
	Chart: BarChart2,
	Like: ThumbsUp,
	Dislike: ThumbsDown,
	Volume: Volume2,
	"Volume Off": VolumeX,
	Issue: AlertTriangle,
	Error: CircleAlert,
	Acount: CircleUser,
	Iphone: Smartphone,
	Camera: Camera,
	Cancel: CircleX,
	Cloud: Cloud,
	"Shopping Cart": ShoppingCart,
	Bell: Bell,
};
