import * as Icons from "@mui/icons-material";
import { SvgIconProps } from "@mui/material";

export const iconMap: { [key: string]: React.ComponentType<SvgIconProps> } = {
    Default: Icons.InsertEmoticonOutlined,
    Home: Icons.HomeOutlined,
    AddBox: Icons.AddBoxOutlined,
    AddCircle: Icons.AddCircleOutline,
    Upload: Icons.UploadFileOutlined,
    Save: Icons.SaveAltOutlined,
    Bookmark: Icons.BookmarkBorderOutlined,
    Heart: Icons.FavoriteBorderOutlined,
    Delete: Icons.DeleteOutline,
    Folder: Icons.FolderOutlined,
    Copy: Icons.ContentCopyOutlined,
    Menu: Icons.MenuOutlined,
    List: Icons.ListOutlined,
    Settings: Icons.SettingsOutlined,
    Search: Icons.SearchOutlined,
    Edit: Icons.EditOutlined,
    Share: Icons.ShareOutlined,
    Download: Icons.GetAppOutlined,
    Send: Icons.SendOutlined,
    Email: Icons.EmailOutlined,
    Comment: Icons.CommentOutlined,
    Calendar: Icons.DateRangeOutlined,
    Clock: Icons.AccessTimeOutlined,
    Chart: Icons.InsertChartOutlined,
    Like: Icons.ThumbUpAltOutlined,
    Dislike: Icons.ThumbDownOutlined,
    Volume: Icons.VolumeUpOutlined,
    VolumeOff: Icons.VolumeOffOutlined,
    Face: Icons.FaceOutlined,
    Sad: Icons.MoodBadOutlined,
    Problem: Icons.ReportProblemOutlined,
    Error: Icons.ErrorOutlineOutlined,
    Acount: Icons.AccountCircleOutlined,
    Iphone: Icons.PhoneIphoneOutlined,
    Camera: Icons.CameraAltOutlined,
    Cancel: Icons.CancelOutlined,
    Cloud: Icons.CloudOutlined,
};
