/* eslint-disable prettier/prettier */
import * as Icons from "@mui/icons-material";
import { SvgIconProps } from "@mui/material";

export const iconMap: { [key: string]: React.ComponentType<SvgIconProps> } = {
    "Icon": Icons.InsertEmoticonOutlined,
    "Face": Icons.Face,
    "Home": Icons.HomeOutlined,
    "Add Box": Icons.AddBoxOutlined,
    "Add Circle": Icons.AddCircleOutline,
    "Upload": Icons.UploadFileOutlined,
    "Save": Icons.SaveAltOutlined,
    "Bookmark": Icons.BookmarkBorderOutlined,
    "Heart": Icons.FavoriteBorderOutlined,
    "Delete": Icons.DeleteOutline,
    "Folder": Icons.FolderOutlined,
    "Copy": Icons.ContentCopyOutlined,
    "Menu": Icons.MenuOutlined,
    "List": Icons.ListOutlined,
    "Settings": Icons.SettingsOutlined,
    "Search": Icons.SearchOutlined,
    "Edit": Icons.EditOutlined,
    "Share": Icons.ShareOutlined,
    "Download": Icons.GetAppOutlined,
    "Send": Icons.SendOutlined,
    "Email": Icons.EmailOutlined,
    "Comment": Icons.CommentOutlined,
    "Calendar": Icons.DateRangeOutlined,
    "Clock": Icons.AccessTimeOutlined,
    "Chart": Icons.InsertChartOutlined,
    "Like": Icons.ThumbUpAltOutlined,
    "Dislike": Icons.ThumbDownOutlined,
    "Volume": Icons.VolumeUpOutlined,
    "Volume Off": Icons.VolumeOffOutlined,
    "Issue": Icons.ReportProblemOutlined,
    "Error": Icons.ErrorOutlineOutlined,
    "Acount": Icons.AccountCircleOutlined,
    "Iphone": Icons.PhoneIphoneOutlined,
    "Camera": Icons.CameraAltOutlined,
    "Cancel": Icons.CancelOutlined,
    "Cloud": Icons.CloudOutlined,
};
