name: local-openai-agent
version: 1.0.0
models:
  - name: local-llama3Model
    provider: openai
    model: 4801422a-5c62-421e-a00c-05c6a9e15de8
    apiKey: 6784299d-0020-4135-ad47-7f58254876db:50d0368d-c451-48f7-846f-6ec1da34e197
    apiBase: http://localhost:9090/Monolith/api/model/openai
    roles:
      - chat
    capabilities:
      - tool_use
    enabled: true
  - name: js-openai
    provider: openai
    model: 4acbe913-df40-4ac0-b28a-daa5ad91b172
    apiKey: d927668b-b3fd-4b44-ac02-634fdd2589b0:5014ccc3-439d-4b36-aa39-5a33c9fc35ed
    apiBase: https://workshop.cfg.deloitte.com/cfg-ai-demo/Monolith/api/model/openai
    roles:
      - chat
    capabilities:
      - tool_use
    enabled: true
  - name: GPT-4o Mini
    provider: openai
    model: gpt-4o-mini
    apiKey: cf3489c5332444c68ff9dd01147a5a88
    enabled: true
preferences:
  chat:
    defaultModel: js-openai
