export const stepsOne = [
    {
        name: 'Connect to Database',
        description: '',
    },
    {
        name: 'Copy Database',
        description: '',
    },
    {
        name: 'Upload Database',
        description: '',
    },
    {
        name: 'Build Database',
        description: '',
    },
    {
        name: 'Add Storage',
        description: '',
    },
    {
        name: 'Add Model',
        description: '',
    },
];

export const stepsTwo = {
    ['Drag and Drop Data']: [
        'CSV',
        'Excel',
        'TSV',
        'SQLite',
        'H2',
        'Neo4J',
        'Tinker',
    ],
    ['Connect to an External Database']: [
        'Aster',
        'Athena',
        'BigQuery',
        'Cassandra',
        'Clickhouse',
        'DATABRICKS',
        'DataStax',
        'DB2',
        'Derby',
        'Elastic Search',
        'H2',
        'Hive',
        'Impala',
        'MariaDB',
        'MySQL',
        'Open Search',
        'Oracle',
        'Phoenix',
        'Postgres',
        'Redshift',
        'SAP Hana',
        'SEMOSS',
        'Snowflake',
        'SQL Server',
        'SQLITE',
        'Teradata',
        'Tibco',
        'Trino',
    ],
    ['Add Storage']: [
        'Amazon S3',
        'Citrix FileShare',
        'Cloudflare R2',
        'Dreamhost',
        'Dropbox',
        'FTP',
        'Google Cloud Storage',
        'Google Drive',
        'IBM COS S3',
        'Microsoft Azure Blob Storage',
        'Microsoft OneDrive',
        'Oracle Object Storage',
        'Minio',
        'SFTP',
        'Yandex Disk',
    ],
};
