/** Component IDs shared by workbench state, commands, and renderers. */
export const WORKBENCH_COMPONENTS = {
	AGENT_EDITOR: "project-agent-editor",
	ASSISTANT: "workbench-assistant",
	FILE_EXPLORER: "engine-file-explorer",
	FILE_EDITOR: "engine-file-editor",
	MCP_EDITOR: "engine-mcp-editor",
	DATABASE_COLUMNS: "database-columns",
	DATABASE_QUERY: "database-query",
	DATABASE_RESULTS: "database-results",
	VECTOR_DOCUMENTS: "vector-documents",
	STORAGE_EXPLORER: "storage-file-explorer",
	MODEL_CHAT: "model-chat",
	MODEL_CHAT_SETTINGS: "model-chat-settings",
	MODEL_CHAT_HISTORY: "model-chat-history",
	ENGINE_SETTINGS: "engine-settings",
	PROJECT_FILE_EXPLORER: "project-file-explorer",
	PROJECT_FILE_EDITOR: "project-file-editor",
	PROJECT_MCP_EDITOR: "project-mcp-editor",
	PROJECT_TERMINAL: "project-terminal",
	PROJECT_SETTINGS: "project-settings",
	PROJECT_INSIGHT_EXPLORER: "project-insight-explorer",
	PROJECT_APP_RENDERER: "project-app-renderer",
	PROJECT_ENGINES: "project-engines",
} as const;
