/** Component IDs shared by workbench state, commands, and renderers. */
export const WORKBENCH_COMPONENTS = {
	AGENT_EDITOR: "project-agent-editor",
	ASSISTANT: "workbench-assistant",
	FILE_EXPLORER: "file-explorer",
	FILE_CODE_EDITOR: "file-code-editor",
	FILE_DOWNLOAD: "file-download",
	FILE_IMAGE_VIEWER: "file-image-viewer",
	FILE_MARKDOWN_EDITOR: "file-markdown-editor",
	FILE_NOTEBOOK_EDITOR: "file-notebook-editor",
	FILE_PDF_VIEWER: "file-pdf-viewer",
	FILE_PPTX_VIEWER: "file-pptx-viewer",
	FILE_MCP_EDITOR: "file-mcp-editor",
	DATABASE_COLUMNS: "database-columns",
	DATABASE_QUERY: "database-query",
	DATABASE_RESULTS: "database-results",
	VECTOR_DOCUMENTS: "vector-documents",
	STORAGE_EXPLORER: "storage-file-explorer",
	MODEL_CHAT: "model-chat",
	MODEL_CHAT_SETTINGS: "model-chat-settings",
	MODEL_CHAT_HISTORY: "model-chat-history",
	ENGINE_SETTINGS: "engine-settings",
	GIT_VERSION: "git-version",
	GIT_DIFF: "git-diff",
	PROJECT_TERMINAL: "project-terminal",
	PROJECT_SETTINGS: "project-settings",
	PROJECT_INSIGHT_EXPLORER: "project-insight-explorer",
	PROJECT_APP_RENDERER: "project-app-renderer",
	PROJECT_ENGINES: "project-engines",
} as const;
