// Generated by scan-components.mjs
export interface ComponentProperty {
    name: string;
    type: string;
    default: any;
    description: string;
}

export interface ComponentOption {
    value: string;
    label: string;
    properties: ComponentProperty[];
}

export const componentRegistry: ComponentOption[] = [
    {
        value: 'counter-box/index',
        label: 'Counter Box',
        properties: [
            {
                name: 'initialCount',
                type: 'number',
                default: 0,
                description: 'Starting value for the counter',
            },
            {
                name: 'color',
                type: 'string',
                default: '#1976d2',
                description: 'Color for the counter and button',
            },
        ],
    },
    {
        value: 'notification-card/index',
        label: 'Notification Card',
        properties: [
            {
                name: 'title',
                type: 'string',
                default: 'Notification',
                description: 'Title of the notification',
            },
            {
                name: 'message',
                type: 'string',
                default: 'This is a notification message',
                description: 'Main message of the notification',
            },
            {
                name: 'type',
                type: 'string',
                default: 'info',
                description:
                    'Type of notification: error, warning, info, or success',
            },
            {
                name: 'showIcon',
                type: 'boolean',
                default: true,
                description: 'Whether to show the notification icon',
            },
        ],
    },
    {
        value: 'progress-stats/index',
        label: 'Progress Stats',
        properties: [
            {
                name: 'title',
                type: 'string',
                default: 'Progress',
                description: 'Title of the progress stats',
            },
            {
                name: 'current',
                type: 'number',
                default: 65,
                description: 'Current value',
            },
            {
                name: 'total',
                type: 'number',
                default: 100,
                description: 'Total value',
            },
            {
                name: 'showPercentage',
                type: 'boolean',
                default: true,
                description: 'Show percentage alongside the progress bar',
            },
            {
                name: 'progressColor',
                type: 'string',
                default: '#2196f3',
                description: 'Color of the progress bar',
            },
            {
                name: 'size',
                type: 'string',
                default: 'medium',
                description: 'Size of the component: small, medium, or large',
            },
        ],
    },
    {
        value: 'welcome-card/index',
        label: 'Welcome Card',
        properties: [
            {
                name: 'title',
                type: 'string',
                default: 'Welcome!',
                description: 'Main title of the card',
            },
            {
                name: 'subtitle',
                type: 'string',
                default: 'Have a great day',
                description: 'Subtitle text below the main title',
            },
        ],
    },
];

export default componentRegistry;
