#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged || {
  echo "ERROR: Linting issues were found in the committed files. Please address them before proceeding."
  exit 1
}

# npx lint-staged
