#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Linting all staged files
npx lint-staged --concurrent false --relative || {
  echo "ERROR: Linting issues were found. Please address them before proceeding."
  exit 1
}

# Linting @semoss/renderer
# npx nx lint @semoss/renderer || {
#   echo "ERROR: Linting issues were found in the libs/renderer. Please address them before proceeding."
#   exit 1
# }

# Testing all projects/libs if vite config is present
npx vitest --watch=false --passWithNoTests --changed || {
  echo "ERROR: Testing issues were found in the committed files. Please address them before proceeding."
  exit 1
}
