#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'INFO: This project uses a pre-push hook to run unit tests automatically.'

echo 'Checking for new or changed test files...'

# # Determine the common ancestor commit with your base branch
# BASE_COMMIT=$(git merge-base origin/vitesting-2 HEAD)

# # List changed files between BASE_COMMIT and HEAD that match test
# CHANGED_TEST_FILES=$(git diff --name-only "$BASE_COMMIT" HEAD | grep -E '(\.test\.|\.spec\.)')

# if [ -z "$CHANGED_TEST_FILES" ]; then
#     echo "No new or changed test files detected."

#     exit 0
# else
#     echo "Detected changed test files:"
#     echo "$CHANGED_TEST_FILES"
#     echo "Running Vitest on changed test files..."
#     npx run test $CHANGED_TEST_FILES || {
#         echo "Vitests failed. Aborting push."
#         exit 1
#     }
# fi    

npx run test -- --run || {
  echo "ERROR: The unit tests failed. Please address the issues before proceeding."
  exit 1
}