name: CI
on:
    push:
        branches:
            - dev
            - main
            - 776-update-frontend-build-tooling-and-node-version
    pull_request:
        branches:
            - dev
            - main
    workflow_dispatch:

env:
    MAVEN_OPTS: '-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true'
    MAVEN_CLI_OPTS: '-s ./settings.xml --batch-mode'
    FF_USE_FASTZIP: 'true'
    GPG_PASS_PHRASE: ${{ secrets.GPG_PASS_PHRASE }}
    RELEASE: ${{ vars.RELEASE }}
    MAVEN_REPO_TOKEN: ${{ vars.MAVEN_REPO_TOKEN }}
    MAVEN_REPO_TOKEN_PASS: ${{ vars.MAVEN_REPO_TOKEN_PASS }}
    MAVEN_CENTRAL_PORTAL_REPO_USERNAME: ${{ vars.MAVEN_CENTRAL_PORTAL_REPO_USERNAME }}
    MAVEN_CENTRAL_PORTAL_REPO_PASSWORD: ${{ vars.MAVEN_CENTRAL_PORTAL_REPO_PASSWORD }}
    
jobs:
    pnpm_build_dev:
        runs-on: self-hosted
        if: ${{ vars.RELEASE != 'TRUE'  && (github.event_name =='push' || github.event_name =='pull_request')  }}
        container:
            image: node:18.16.1-bullseye  #nvm image which can use multiple versions of node
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

              #install node 24 - set to node 24
              #pnpm install and build
              #download semoss bi - rename semoss bi to lagacy 
              #install and switch to node 18 
              #pnpm install and build 
              #copy legacy into semoss-ui/packages/legacy 

             # ---------- Build semoss-ui (Node 24) -----------                
            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                version: 10.13.1

            - name: Set up Node.js 24
              uses: actions/setup-node@v4
              with:
                node-version: '24'
                cache: "pnpm"

            #- name: Install pnpm
            #  run: npm install -g pnpm@10.13

            - name: Install dependencies and build (semoss-ui)
              run: |
                pnpm install
                pnpm run build

            # ---------- Download and Set Up semoss/bi -----------
            - name: Remove previous legacy folder
              run: rm -rf packages/legacy

            - name: Download SEMOSS/bi repository
              run: |
                mkdir -p tmp
                curl -L -u "${{ secrets.SEMOSS_GITHUB_USERNAME }}:${{ secrets.SEMOSS_GITHUB_PAT }}" -o tmp/main.zip https://github.com/SEMOSS/bi/archive/refs/heads/main.zip
                unzip tmp/main.zip -d tmp/
                rm tmp/main.zip

            - name: Move SEMOSS/bi to packages/legacy
              run: |
                mv tmp/bi-main ./packages/legacy
                rm -rf tmp/
            
            # # https://github.com/SEMOSS/bi/issues/1
            # - name: Delete contents of legacy folder
            #   run: |
            #       echo "Remove and recreate the legacy folder"
            #       rm -rf legacy
            #       mkdir legacy
            #       ls -als

            # - name: Download contents of SEMOSS/bi project
            #   run: |
            #       echo "Download SEMOSS/bi as a zip file"
            #       mkdir -p tmp
            #       curl -L -u "${{ secrets.SEMOSS_GITHUB_USERNAME }}:${{ secrets.SEMOSS_GITHUB_PAT }}" -o tmp/main.zip https://github.com/SEMOSS/bi/archive/refs/heads/main.zip
            #       echo "Unzip contents of the SEMOSS/bi to the tmp folder"
            #       unzip tmp/main.zip -d tmp/
            #       echo "Delete the playsheet folder from semoss/bi files"
            #       rm -rf tmp/bi-main/playsheet/
            #       ls -als tmp/bi-main/
            #       echo "Remove zip file"
            #       rm tmp/main.zip
            
            # - name: Move SEMOSS/bi files into the legacy folder
            #   run: |
            #       echo "Move contents of SEMOSS/bi into legacy folder"
            #       cp -r tmp/bi-main/. legacy/
            #       echo "Delete tmp folder"
            #       rm -rf tmp/
            #       echo "list files under legacy folder"
            #       ls -als legacy

            # ---------- Build SEMOSS/bi (Node 18) -----------
            - name: Set up Node.js 18 for SEMOSS/bi
              uses: actions/setup-node@v4
              with:
                node-version: '18'

            - name: Install pnpm in Node 18 session
              run: npm install -g pnpm@10.13

            - name: Install dependencies and build (SEMOSS/bi)
              working-directory: packages/legacy
              run: |
                pnpm install --ignore-workspace
                pnpm rebuild node-sass
                pnpm run build

            # - name: Cache node modules and Maven repository
            #   uses: actions/cache@v4
            #   with:
            #       path: |
            #           node_modules
            #           .m2/repository
            #           dist
            #           index.html
            #           .nx/cache
            #       key: ${{ github.ref_name }}

            # - name: Install dependencies
            #   run: |
            #       apt-get update
            #       apt-get install -y maven
            #       npm install -g pnpm@10.10
            #       pnpm install
            
            # # - name: Install nvm and node 24
            # #   run: |
            # #       curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
            # #       export NVM_DIR="$HOME/.nvm"
            # #       [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            # #       nvm install 24
            # #       nvm use 24
            # #       node --version

            # - name: Build
            #   env:
            #       NX_REJECT_UNKNOWN_LOCAL_CACHE: 0
            #   run: npx nx run-many -t build -p @semoss/client @semoss/legacy

            - name: Maven clean install
              run: |
                  /usr/share/maven/bin/mvn $MAVEN_CLI_OPTS clean install -Dci.version=${{ vars.VERSION }}-SNAPSHOT
                  rm -rf .m2/repository/org/semoss

            # - name: Save artifacts
            #   if: success()
            #   uses: actions/upload-artifact@v4
            #   with:
            #       name: semossweb-artifact
            #       path: target/semossweb-${{ vars.VERSION }}-SNAPSHOT.war

            # - name: Delete old artifacts
            #   run: |
            #     echo "Deleting old artifacts..."
            #     ARTIFACTS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            #       "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | jq -r '.artifacts | sort_by(.created_at) | reverse | .[1:] | .[].id')
            #     for ARTIFACT_ID in $ARTIFACTS; do
            #       curl -s -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            #         "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID"
            #     done
            #   env:
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    pnpm_build_deploy:
        runs-on: self-hosted
        if: ${{ vars.RELEASE != 'TRUE'  && github.event_name =='workflow_dispatch' }}
        container:
            image: node:18.16.1-bullseye
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            # - name: Cache node modules and Maven repository
            #   uses: actions/cache@v4
            #   with:
            #       path: |
            #           node_modules
            #           .m2/repository
            #           dist
            #           index.html
            #       key: ${{ github.ref_name }}

            - name: Delete contents of legacy folder
              run: |
                  echo "Remove and recreate the legacy folder"
                  rm -rf legacy
                  mkdir legacy
                  ls -als

            - name: Download contents of SEMOSS/bi project
              run: |
                  echo "Download SEMOSS/bi as a zip file"
                  mkdir -p tmp
                  curl -L -u "${{ secrets.SEMOSS_GITHUB_USERNAME }}:${{ secrets.SEMOSS_GITHUB_PAT }}" -o tmp/main.zip https://github.com/SEMOSS/bi/archive/refs/heads/main.zip
                  echo "Unzip contents of the SEMOSS/bi to the tmp folder"
                  unzip tmp/main.zip -d tmp/
                  echo "Delete the playsheet folder from semoss/bi files"
                  rm -rf tmp/bi-main/playsheet/
                  ls -als tmp/bi-main/
                  echo "Remove zip file"
                  rm tmp/main.zip
            
            - name: Move SEMOSS/bi files into the legacy folder
              run: |
                  echo "Move contents of SEMOSS/bi into legacy folder"
                  cp -r tmp/bi-main/. legacy/
                  echo "Delete tmp folder"
                  rm -rf tmp/
                  echo "list files under legacy folder"
                  ls -als legacy

            - name: Install dependencies
              run: |
                  echo "Event Name: ${{ github.event_name }}"
                  echo "Release: ${{ vars.RELEASE }}"
                  apt-get update
                  apt-get install -y maven
                  npm install -g pnpm@10.10
                  pnpm install

            - name: Build
              env:
                  NX_REJECT_UNKNOWN_LOCAL_CACHE: 0
              run: npx nx run-many -t build -p @semoss/client @semoss/legacy --verbose

            - name: Deploy with Maven
              shell: bash
              run: |
                  REF_NAME=$( echo $GITHUB_REF | sed 's|refs/heads/||')
                  if [[ "$REF_NAME" != 'dev' && "$REF_NAME" != 'main' ]]; then
                    mvn clean install -DfailIfNoTests=false -Dci.version=${{ vars.VERSION }}-SNAPSHOT
                  elif [[ "$REF_NAME" == 'dev' || "$REF_NAME" == 'main' ]]; then
                    mvn $MAVEN_CLI_OPTS deploy -P deploy -Dci.version=${{ vars.VERSION }}-SNAPSHOT
                  fi
              env:
                  GITHUB_REF: ${{ github.ref }}

            - name: Remove cache to save space
              run: rm -rf .m2/repository/org/semoss

            - name: Upload WAR to Nexus
              if: github.ref_name != 'dev' && github.ref_name != 'main'
              env:
                  NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
                  NEUXS_PASSWORD: ${{secrets.NEUXS_PASSWORD }}
                  GITHUB_REF: ${{ github.ref }}
              run: |
                  REF_NAME=$( echo $GITHUB_REF | sed 's|refs/heads/||')
                  WAR_FILE=$(ls target/*.war | head -n 1)
                  if [ -f "$WAR_FILE" ]; then
                    echo "Uploading WAR file: (basename $WAR_FILE)"
                    curl -v -u "$NEXUS_USERNAME:$NEUXS_PASSWORD" \
                    --upload-file "$WAR_FILE" \
                    "https://artifact.semoss.org/repository/semoss-ui-hosted-repo/$REF_NAME/$(basename $WAR_FILE)"
                  else
                    echo "No WAR file found in the target directory."
                  fi

            # - name: Save artifacts
            #   if: success()
            #   uses: actions/upload-artifact@v4
            #   with:
            #       name: semossweb-artifact
            #       path: target/semossweb-${{ vars.VERSION }}-SNAPSHOT.war

            # - name: Delete old artifacts
            #   run: |
            #     echo "Deleting old artifacts..."
            #     ARTIFACTS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            #       "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | jq -r '.artifacts | sort_by(.created_at) | reverse | .[1:] | .[].id')
            #     for ARTIFACT_ID in $ARTIFACTS; do
            #       curl -s -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            #         "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID"
            #     done
            #   env:
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    pnpm_build_release:
        runs-on: self-hosted
        if: ${{ vars.RELEASE == 'TRUE' && github.event_name == 'workflow_dispatch' && (github.ref_name == 'main' || github.ref_name == 'dev') }}
        container:
            image: node:18.16.1-bullseye
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  echo "Event Name: ${{ github.event_name }}"
                  echo "Release: ${{ vars.RELEASE }}"
                  apt-get update
                  apt-get install -y maven
                  npm install -g pnpm@10.10
                  pnpm install

            - name: Build
              env:
                  NX_REJECT_UNKNOWN_LOCAL_CACHE: 0
              run: npx nx run-many -t build -p @semoss/client @semoss/legacy --verbose

            - name: Download contents of SEMOSS/bi project
              run: |
                  echo "Download SEMOSS/bi as a zip file"
                  mkdir -p tmp
                  curl -L -u "${{ secrets.SEMOSS_GITHUB_USERNAME }}:${{ secrets.SEMOSS_GITHUB_PAT }}" -o tmp/main.zip https://github.com/SEMOSS/bi/archive/refs/heads/main.zip
                  echo "Unzip contents of the SEMOSS/bi to the tmp folder"
                  unzip tmp/main.zip -d tmp/
                  echo "Delete the playsheet folder from semoss/bi files"
                  rm -rf tmp/bi-main/playsheet/
                  ls -als tmp/bi-main/
                  echo "Remove zip file"
                  rm tmp/main.zip
            
            - name: Move SEMOSS/bi files into the legacy folder
              run: |
                  echo "Move contents of SEMOSS/bi into legacy folder"
                  cp -r tmp/bi-main/. legacy/
                  echo "Delete tmp folder"
                  rm -rf tmp/
                  echo "list files under legacy folder"
                  ls -als legacy

            - name: Install dependencies
              run: |
                  echo "Event Name: ${{ github.event_name }}"
                  echo "Release: ${{ vars.RELEASE }}"
                  apt-get update
                  apt-get install -y maven
                  npm install -g pnpm@10.10
                  pnpm install
                  
            - name: Deploy with Maven
              shell: bash
              run: |
                  mvn $MAVEN_CLI_OPTS deploy -P deploy -Dci.version=${{ vars.VERSION }}
              env:
                  GITHUB_REF: ${{ github.ref }}

            - name: Remove cache to save space
              run: rm -rf .m2/repository/org/semoss
